apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-anubis-key
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:XLxSKFsbAE07Xwl0YPeYIJwUNmuLRiHu56DTSZpO6qMZ9QH9mzlaFs8s4Rm2FXuAixQdZ9kRuxyl8Ki++4cIFA==,iv:dPYYYtgPq7NUDTJ2+sioMlA7goYU535OAAejz+T7VNo=,tag:C0Se6CUBuTvUJG3BaVxjTg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ0g2ZE1QelNET1BzNFF6
            clpyaCtDMDVJNGFvT3l0aEhRM2Jsb1dpRFhNCkkrZjNYWitxZk5EQ2UwWVltaUdm
            OHBucVdjdlNZSXNadTBMdEZXMDR0OWcKLS0tIFNuV2F2R0Vkb1JpSDl6bVJvMGla
            V2V3bEMzSWZNbThRbC9lNzc4WG9PSGcKaVKzOoQEA8EGDuXIJtvKIBgsJpIvtcws
            I5BfD5lUMWBZwDpalLbLFyttaIVO8LCWj/w1HY/pUqGH5g60EuW9Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:29:25Z"
    mac: ENC[AES256_GCM,data:q1HDeVCzuhLNeYLNeCU3ba7moVoATEg5I6nMs5AnuHW56jJfB2+l4fX9JJx6a9vJXjw/vgn4HV711UR+oX/8zeKHxoo980v997POy/c2RAtWLFmTmf7igqt/XiDvJcnM217xxi3JBiqRnVTltUucPFB3RV2Cd/Z2FzNgkgaG/TI=,iv:ju9SbsQv1gMTvIMkSIK/U1Xp2Kr4l2OFw6jkPXONVfM=,tag:RPt2cwrbViHuj386zhbdEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
