---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-operator
spec:
  chartRef:
    kind: OCIRepository
    name: garage-operator
  interval: 1h
  values:
    crds:
      install: true
      keep: true
    webhooks:
      enabled: true
      certManager:
        enabled: true
    serviceMonitor:
      enabled: true
