---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-backup
spec:
  sourcePVC: ${VOLSYNC_CLAIM}
  trigger:
    schedule: "0 16 * * *"  # Daily at 4 PM UTC
  kopia:
    capacity: ${VOLSYNC_CAPACITY}
    compression: zstd
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID}
      runAsGroup: ${VOLSYNC_GID}
      fsGroup: ${VOLSYNC_GID}
    repository: volsync-kopia-secret
    retain:
      daily: 7        # Keep 7 daily snapshots
      weekly: 4       # Keep 4 weekly snapshots
      monthly: 12     # Keep 12 monthly snapshots
