---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgres-data
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-media
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
