apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
type: Opaque
stringData:
    SMTP_PASSWORD: ""
    MATRIX_CLIENT_ID: ENC[AES256_GCM,data:AIPLq3QfQr5qi07xXDmSlqmVoTaJLdNF31SPavhc0+Wi74fF,iv:ARX/XpMi/R35B2UCw/zf+QbiukUwE3BzIRm5SWYNga4=,tag:4jd6bT2yVe2MQfdIe3X7QA==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:S6wMVfJaH03un9+a6E5/DkOh5yW5LbsXFU3h2Qmu3CE=,iv:HnUYnr0QR4wi0RUaZwjcgaTpElN+nZpR1/G9XM5+VgU=,tag:e2dTh6kcJauGUQqdQz2Krw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T12:08:05Z"
    mac: ENC[AES256_GCM,data:Jk8QZolaDazPTSwNh7zDdF9t/tae1U/hApSBB57QatTFJHvkVNHfj0/e59niAv3lw4ok8EYvyVM2m32cB8D5G1HG4H88LPRmBA6VoUs5yjUQwMalzjVyyftZfzsUeWRZ/WNM8/7y+L4n8nkTeal5mZ9D48B1w1p5xQ1G6/8h1jE=,iv:XNbIhw4z76eP0+KF65b3Bl5ZchiwPxch5UjlWwA3KUk=,tag:kPnIS3HApseY7g9ziZC36w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
