apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
type: Opaque
stringData:
    MATRIX_CLIENT_ID: ENC[AES256_GCM,data:PUV0qlUOrLGRCQKe0m608IQg666rJdlBT9+4Oo5EElQ6yZkg,iv:rs/jt3sGqnuSgqV/BUrTLT3TTroqyBk2NdZs6qS57Ns=,tag:+00ifDQcVERHDPPmzgfuxQ==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:MF4QeojauDr2zwnhOZMKB2CMKk14QMLaFnKTbv3x9a0=,iv:q5XDDSdj8g4OUz+v8vK5Rf0Iabtv9Q2pqMqLf7OKVg4=,tag:diWviFNIVvg5acB6Z8K+gg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T22:04:09Z"
    mac: ENC[AES256_GCM,data:zpZ2qQS0kNhCoG+DP1prEdzD73Tng9SjjbjJCvjKKR2F368hAQ5P5vafAwAD8pdf8FLVjjLrBKiS4aUjKGk9jTvKL8r5yHvL7yDgj4k+YqDubJPitTMaJFIz5dD6KE+VZ6lXLqHhynnJw3GpnuuDcE3S7n0Ge5zM5kJN4eV/lGg=,iv:skynZSIn3COuKHUVO/iY3C2FqbEXiCeW62y1P6ntMFA=,tag:Yk2kTLh6dOp0H29LWHZwZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
