apiVersion: v1
kind: Secret
metadata:
    name: towonel-edge-secret
type: Opaque
stringData:
    TOWONEL_EDGE_HUB_LINK_PSK: ENC[AES256_GCM,data:iu1j6V5jirFuwlrtJ4CxRD9VIRSXkgqNKkDXaZp79NFzkqaMaCTLHHDr4wzYx9owdezJlqBoSypksXI+kDQ4Ww==,iv:2vHPX9UACcRdENbKXcIYHEO/yC4IeO9fLU3RuWCTPxY=,tag:s+AfSQuJLDt3Z3KxtEOSQg==,type:str]
    TOWONEL_EDGE_TLS_ACME_EMAIL: ENC[AES256_GCM,data:MvyY88oQTzIurMRLgZ6eZnqhJv4=,iv:ZKNj36myl2c1DZRZGTEGIkl/UK5UFEFv9oBiRacfAHQ=,tag:F3M1podXYNc4RvwBK9AOwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSFpWVVd5WGhndFFINHAw
            c0dMWkE4RkdtSmNSTHhON2w3N0NpN2hFVzM0ClkyWGZCUlc5RUVJak1TaTVaOWRW
            YWRuaG5SQmxSQUNsVVZ3cm41U3U3bTAKLS0tIGRKeU4xK2UrRTVwM1FJOUd1bG13
            ZFRUbWxrMVR4OUV3ZDhEaWNnNDlYdHMKdO0b+aQK+suCBtiuOilvqfpVQgJKZOQw
            sO4mEoyreqejNNgAAYbCLdTY+L/6hy6p1UNv0hGW5NKql6mvYQpAOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T12:13:37Z"
    mac: ENC[AES256_GCM,data:D1OGl99C/LOSidX8Hluest7YsK7cYjN11af5fhrmhB3S30saoZPIxWGUZDwhRO7y8+wrvPdv+sQrbNsT5TtiZvjnNphY1mkj5gSAfOrWl26u5iUa9MgmmeCjlhCpJrBitnvhjXyKnZ7/m/Qh4WfUDrBEplsDe+sRUnQbrLzC8oA=,iv:VNveq0T0IgMhCyEb8z8Wl8AKfqtCg4x9W+tL8tQ75CU=,tag:YAEURMNxACm/Ig3bW4n1Lw==,type:str]
    version: 3.13.3
