apiVersion: v1
kind: Secret
metadata:
    name: maxmind-secret
    namespace: network
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:HfnaJV8Fww==,iv:wIhpIXmQJO315VH6MAlfKGvh419dclwvWPSt24QrzHI=,tag:zWDGq4C1he/2+ENNTL0VLw==,type:str]
    license_key: ENC[AES256_GCM,data:PzlzTtLEHis/j/7xktJfmJSeCBsVw32ltKlIp0ef6VrbEiv61Dsxpg==,iv:Gau2+lk27cWc5OaVweOLVobtkhSj6xkkY0YUpwV9jcc=,tag:lXGE47ss+3cGwCB0RvwQiw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGlEN2ZxWDRtemsydWdr
            NXdBcXFGektYalpiL3c1SThvdXN0MVF4aUVVCkp0bzVDZTh4SlRsMDlKWVNxN1M4
            eXNKdDA1TldPaUF6dEx6MTJtdzNUOTgKLS0tIGRlcUFueDhDYVdER1ZXOVF1TFlU
            WjJ5SS9USW1GLzZSM0d3TUJkbW8yRkkKZMnq7/Foco95+jRsjT+qlh03/pVR4UL6
            FGBWorw+82J5LdCmBtLPbv5KAiU6ToAQBNdPTsOoAzOzI4nRu3koFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T23:09:26Z"
    mac: ENC[AES256_GCM,data:9DzoEumRi7IjfkNagEyfgzWijXM+YZY51AqWMUzaUnRk7k7pWqWuoc43FYozrFP2yg/AYwpyFD+xR/LgyGBgrVlAkUdjDvmrOuSs3q5feF133Erb5OnLcqi2aTD77ShulqhbQB0dFXx2Y8jy5qA1nkLsazBVq6wS2QrWzMbq/1E=,iv:xvrPEH++upFPtLV3X8b5+OanvxLA5H4ZvuzjQkjJGyk=,tag:BBBjOuDuSRvS/yGDfyVkOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
