apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:DdLMVFy0yZNgu4PPpswnNRt+j8nVnU0eo+XsTDXS6brmjdcYx38ztStapzlq3j3LINAuFKLUexqoUwcYc3hQeQ==,iv:Q6a+xbG+tyAirY+wF74r6ae4OKY+CLCkMrl5dnjsm4E=,tag:myjFQfjjbiFq/YoaNpdzMg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:rUCp60KDcUs=,iv:E7TK6XUu8D2VuQay0s/iDX5FZ0tinlLdfuvP5IzpLUU=,tag:rhSMm/0bsmboscHYW6bAZg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lxwjPUMDxPD0IJIUrvH0mm8ZK6uR9AryyNSS67EbUbx4QiIQX3MfbYjA4JfYbZDuFmtRe1vLtVg33LJ3El4gLA==,iv:Feuafcuf/c0JYRTEHKwzCr4cTJYh9HZxZwlwvKZWX/c=,tag:AyZHlQFCLgLizazvlqMEYw==,type:str]
    PAPERLESS_APPS: ENC[AES256_GCM,data:kB1CQmvLQi09TebT+OEsxmT3u64b34bbhwQpk2V8cxn4E35YIasQr+l+uBJ6cw==,iv:zfQ2ROL8RfgSB5FisRvKnW6JGBVSDK50za/ScqUxpK8=,tag:zkm+7VMjvtX4ze68y0Xmlw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:wbUwdD+oBwlNnSidLDdyv+KPZrPZvy+2NUdlHpezNOO1YgqBVoTUuH0t6Y2iEL537ujEKkGZbyGXo0MVa56w78oNoKrz449d4QpWPdyq/2mzF8RiOI8QRDW0WLGpd7qS+6gS1DWZ2t6P9ORDWx0Ig8y1IauNlFaZc1em3U3wUeF8hcHLFz4lq+9OpGy+02E+Gkx5dCZDgeYaQaUHtQN1YvMACSBIY3Bzp9SKON2Lr2zsoMTbC1Tlb+WTdAh9Vjfw+d//B9Pt2EerA3pTeDBvdKvfXEZsnOyH6kYoY+cSlWT6N0c9Xu7VH+NEzDjysTUM6w5zRsplxzXvdv5NqvHl17jmG47568AZSvfWCB2VchWBVcyRZdRZqNN0qd5wxWE=,iv:ptWiRdVdPtVa+ROeziIPmxlqlUWyBlmbvqlcdte9iP0=,tag:hD8US0WJuBy48DMqsjb4/Q==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T14:17:04Z"
    mac: ENC[AES256_GCM,data:oHwQ0EypTtbPq0HLo/tvfsUciLqBgFa4DdlhHEFE0Puy9qKLDQpQlikhDccafdytV27g5EaWT4zHB4x6qXjtiUcV9Elw1lyYqXq1H1p41dgqlDvRUOXsdBQmXo/9Syp+9Ph7ktQztH8i3RUz4Lf0xGba52FCgW4+LEisnksUQPE=,iv:RM4Syo3IS+OhNW0/s9i0c4es67diGlg3XXAygwsyMYM=,tag:PylySQyBXnOnIDF49/AanA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
