apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:DdLMVFy0yZNgu4PPpswnNRt+j8nVnU0eo+XsTDXS6brmjdcYx38ztStapzlq3j3LINAuFKLUexqoUwcYc3hQeQ==,iv:Q6a+xbG+tyAirY+wF74r6ae4OKY+CLCkMrl5dnjsm4E=,tag:myjFQfjjbiFq/YoaNpdzMg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:rUCp60KDcUs=,iv:E7TK6XUu8D2VuQay0s/iDX5FZ0tinlLdfuvP5IzpLUU=,tag:rhSMm/0bsmboscHYW6bAZg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lxwjPUMDxPD0IJIUrvH0mm8ZK6uR9AryyNSS67EbUbx4QiIQX3MfbYjA4JfYbZDuFmtRe1vLtVg33LJ3El4gLA==,iv:Feuafcuf/c0JYRTEHKwzCr4cTJYh9HZxZwlwvKZWX/c=,tag:AyZHlQFCLgLizazvlqMEYw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T21:08:02Z"
    mac: ENC[AES256_GCM,data:oAQ5UJojVHgE3wV2+GBP+4FPHAU9sxeMrjM0Y9zJex2rt5MoVx+9Hn0oq8+UqVK5l3NaohA1jcb4PemXBVl5/uXjjXDYsv9yXklMNwwOrZCEMvewehuEoXwWeRopXwDTb2Q/uhTYeAMM8kznjYeLPRZb4foO0D3VyrsYmqWvTMQ=,iv:G4jdDN6qaqkCfxbbSifvWGPqkvfE7NgJnf4zuDrzKhg=,tag:WfkX3pqm/cSRFMO/F9tBWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
