---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: zigbee2mqtt

  values:
    controllers:
      zigbee2mqtt:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${VOLSYNC_UID}
            runAsGroup: ${VOLSYNC_GID}
            fsGroup: ${VOLSYNC_GID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.7.0
            env:
              TZ: ${TZ}
              ZIGBEE2MQTT_DATA: /data
              IGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              # mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.selfhosted.svc.cluster.local:1883
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
              # frontend
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee.${INTERNAL_DOMAIN}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
                memory: 150Mi
              limits:
                memory: 150Mi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["zigbee.${INTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /data
