apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: seflhosted
stringData:
    zigbee_ext_pan_id: ENC[AES256_GCM,data:5y6Z6Skm5C5nNL/AjMi/wm4bw5cJI7oSsUKv,iv:zNqWC8TixNV+HRC3XB0eL5V29zHGQx7tlTPFIExLxB8=,tag:gsDhpLSj1HivsuBc/Xqwyw==,type:str]
    zigbee_network_key: ENC[AES256_GCM,data:cbpb/p///U6HNGWLQ3HWwMke9434wS0WafiB4u1hxzCXo99HmRJNLlrqjpDSFSq+vxuEwosucQ==,iv:gYneZbjZH5pZKDdpy5vlf1vWCEwSbSmxQYb0es9NKiE=,tag:8qvwDIbAL1C0DRbT34vP3A==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:w5f7sIg=,iv:7n9PicLLWJIhD7WVu3RSUobUZuvJsiEExlv0l7havS4=,tag:Rdcw3iUMoHwWKuzrJWeKUQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU2RFb1FIeUNzNytWMUxp
            NFlhOERYNlh0aTk1bE96bTU5c05ZdWJObEVrCkE5QjhYbld6REZLWHAvY3RxdVNx
            UzV5dU1VVmxXZjMwY0J1ODVTa1BlT0UKLS0tIFp3a1VTOFhza1RDUi9wZ2psczZ4
            UHc0NnZ2TVFZdTZPQnJPOGlqVmRWRE0Kfk/1f4NGACdHi0GTWRn+3Cd0MnkgAc01
            2cMvdusEw5vONI0yuB3/rngSvlOCeWLmkajtpTGGKiiLFtVO+yX0sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T17:11:39Z"
    mac: ENC[AES256_GCM,data:oBNc/dTHNNXnB8vXbQaBtf6xcZbvYZENhHo+HcYhKo9G0OcoMqmx3fMMgs6glFmDP8lB+XKwRBwnJynhpuxnOm6haN6iMUU6pMmFNfcMn6ZpYrKQFUE35CeOcjsLX6eYDa13jnsflLnVlHEB+4s83C7MVfSZaz7JgtviD4rV4VE=,iv:BvY5NietaDEj6ZwJllMr70uVfbqwzT21nTJFg5skSZQ=,tag:G3jA43jNOf6PyENl04+o/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
