apiVersion: v1
kind: Secret
metadata:
    name: netcup-secret
    namespace: cert-manager
stringData:
    customer-number: ENC[AES256_GCM,data:GWwDug8Q,iv:n7iZKyZDVSCJy3pK88Is8qsltdGQ1LITdN+Kr508V1I=,tag:oXLd7SVh16NEa9r2Jvi2wQ==,type:str]
    api-key: ENC[AES256_GCM,data:KxA+C/P1RpPQ7uCqajDfUJcCcDBzLtVL5RFssuDxoDzMNxpGrnHpZiTbUYttvR3FiGo=,iv:PV/vpJPg7zY4lqCnRnAHFYy+Elc0MePpHtP0GBIrw6o=,tag:Qq1Nl/kni3CUFRccxYvO4w==,type:str]
    api-password: ENC[AES256_GCM,data:ap5vHoKcOsw0fnABnCcqeXIx8yTMWDwDb5+TUtfDQym80ZjJh/w0w1i7K2i6/ffAHLc=,iv:qsHyd05a6tyYcZNl/JVoZ73ZYsaJb2ZE4v+F6hXNXq8=,tag:IxZy3OzNpDqVLx55ltyTBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJEOUd1U2pD
            Wm02dm82UHkyNXBMWWdMdHp3M202L3lBNUVmMWd3MEdCWFpiQm1TcGxBSWo3dk9r
            NFFHbGVPNWM3ZUZMUXNrUWxPV0dmQlJTc2VFSVVIVFo2dWNXU09PYUNvRkVZcnlu
            VjVuVkF6QU5SR3dMK20yZFIwTUZvN0pORWVoNGR6YWREbS8xdlpNRjZEeHpiandP
            MUE0YVdUeENIQU1CSzdERGx3bnBQbit2NC9HbjN3SW5DQTN0bmNHMVNrdnA5UkNS
            am1pd1lTYkNjTnpPd0pSZkNDcFhONk4yblQ0MWNBbnAyOVJtS3FYeUtPQ0lMZ2Jn
            eWFqVVpaQjliY3RJSzhxY1N0enlYOG1FZ0tMT29Gc0w2TGgvdk9UUU1jb2FwM3hH
            WGJheldvY2ZFQVdwUFp1VjVWSkwwb3RtTGtadjJXb05CblpNSXRMejdtYTdPVy9E
            emhRa2l4bEdCVVFiNFdtY213djhvUEN0OUc1ckYrT2YrSlZDMmg5MHRUMTFybWxJ
            Q0ZQRGl1SVBxdmJUM0ZPckY3ZFJMbXU3bmRCMUJrWlp0eFJ6bHRxU3RNYW9PR1hL
            M08ySGp3cHdjN1JBV0RPZFBDb096L2IwdlkzK29IT2kyaGNubXZ5alY3djlpSFZL
            R2JyQVh6eUh0YnZJc29MdE9GTW81WTBBYnI3QjZQbEVYdFc5eHFZcGlUV0xnYzMw
            ZjJ4S2FZbnB2MmNuNVVKdmxhSlJURlIzUEpkZno2R0pvLzYwNk5VYWMyZ2xFZnNZ
            WVhvTHd6aGNkVW5GQmhGRStVOC9RbVE0eWNPYmNZVjJBY3dZem9IZExaVEFraHB0
            NUJlMWRzR0FSRVFyOFFrMzZXQnhWZHA0QS9SbDNzLzRHclc3d1FNRXVLVm51dTZ4
            YjBwRXVwWXMrbjVRc05XQTlKdDJEdzFsYUh6QmhiMjlkaUVyNk41eERzUWF2ZWVk
            NUJxTnBobVBHc3AvU3d6TGNIc2RSWGJLeUs2TXN1eHlMZ3lZeUlNbDNLUmdQN3pO
            QjloeXcrL25UWDMvYnE1TnVVUnZqREx6SitTYWl1Vk5rRWtVQmFGelh5QzMwR0Qz
            Lyt3MDc3dldQRFVoRWhPdFROa0dKcnB6RzAwUUt2L1VFWjZxZllpaXUvVmsvcXJ1
            ZDNPYVVaeDAvcnZEVDhyTGJFeFR1Mld5S1hzUkNDMGZwZHhhNEZmaXJHbUtEK0Mr
            TUlZMDFMUXR5NlMvR1RKVWJ5N1JHMkkwbGpXWFFCZjJNSzV2QzByREZ5ZkVnaXg4
            VlE4M1RJNkNONXF0QUorcndKd0haa3pWcGxTU0NRaWF0clFoMnE5SndSaVM2c1pP
            SWVOdFd2TFhZU2pHUXhjVzByL3E2cG9RY0FHUDJ5NjgycklVd3ZZR3Z2dlhvcit0
            aTU4d3pYU1IwYm1lSkJrbEhMYXZSOWtLOWM2NGxqQXJ0cUNwaVlkWGtJeXN1ekhZ
            U0FGQ1dCbVpUS21OTWZpWUl2V1FDN3hITDVpZW1MMmRXcUJ5eFh0aFgzZnhlc2sz
            a1hoU3VjcHg2M0ZYNmxYYzcrQ2xjR09sUHE0OHBoUFZVZmZDUnZLU3lwRGorWGxx
            OEV3cHJQR3Q5Zlo4V1ZYcUhVZ3JiQzFEVW15dmNPOXRGRndSOFJuZXg1U3k4VlhG
            bHkvK2ZZUHdVVmJXa2hoNFljYlFPRDBBbXBNMldKVnlDM3hiNyt5TWVEZHg0NFVE
            ZThSdGVVL3JPclYxVXI3REN3R1Q0Zk9BM09RU09MNElqcGY1ditqTDhROVZPVW9O
            NWEyOU9TSXhJTExxTk9wb080ZzZiTzZRdVcwR0hzcnZuREFqblg2QjBNTXlqQ3VL
            R0t1UnRsdnpxSVN5TkcxcEJ0Nm1USXJBL3U1SSsrekF5TEdlL01zSjFudGZ5NEZP
            OXh0VjFVK0Mrb2pkT2VMTFFpdXA5M0VVc21xZkJFNVlaTDNZNkVoZ3VLUFFRUQp0
            NU14RkllcjM0TXpWSnFqTUErYW5BbXJYeDZFTmxRZE9xbGtPM1k1blNJCi0tLSBP
            R2xOVFIxZWJQTEVrT0xabzNHejdqMGVSeUlYMFptUTV3ekZMREZBb2tzCvX3mR9s
            j+XfQBlntoK9D1bVc6nqF1W6r0QdEU0sQ47WsxXSAseLgcCK6v4b8A5Lc95cG4px
            LtcVzRafEZ/VJ6c=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-13T21:58:33Z"
    mac: ENC[AES256_GCM,data:st3imkxiGMMP2GjO6t2MvmQm8q4nxflouO9b2NKCw3ILuGoh7XadxNvnUfyBSPuE6/WZ03a8+Tj8z4n8Z6MdBjgWBace1ssF0WGzx1LVKIfwBvfWE935dtztZhWNu6ja8xCumscGsXq4sHWB3K0r8U0JLrC4BZ2I1Gzhky6p928=,iv:PiHRqJ61aiU8oVL3ft9045Wb1OBw89McmpNxa6o6aOI=,tag:9cI/pTKC259I8T8Co8uHkg==,type:str]
    version: 3.11.0
