---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: calibre

  values:
    controllers:
      calibre:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: v4.0.6
            env:
              TZ: Europe/Berlin
              CWA_PORT_OVERRIDE: 8083
              PUID: 1000
              PGID: 1000
              UMASK: "002"
              #HARDCOVER_TOKEN:
              #  valueFrom:
              #    secretKeyRef:
              #      name: ${APP}-secret
              #      key: HARDCOVER_TOKEN
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  # S6
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - DAC_OVERRIDE
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: calibre
        ports:
          http:
            port: 8083

    route:
      app:
        hostnames:
        - "books.${INTERNAL_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8083

    persistence:
      data:
        existingClaim: calibre
        globalMounts:
          - path: /config
            subPath: config
          - path: /cwa-book-ingest
            subPath: cwa-book-ingest
          - path: /calibre-library
            subPath: calibre-library
      tmp:
        type: emptyDir
