---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: local-hostpath
