apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: media
stringData:
    HARDCOVER_TOKEN: ENC[AES256_GCM,data:eEMebl7IY25P6m6YNqwiZEqCpySRhYbVGpwYTbON6t0RV2pxokyJh/RLJsbSbMqOECPxDrt/IQSn3L3WcLt5dyWC8Z6k+qgb7vPfWfiDyR1m3Svs8dYKzp1B5mQuFvF4z0M86uQjwnpilmAsigwCSTPDBAU3iBPd9h5F3DEEF3esuhRIK4CSra+CwRV4h/TAOzpY1ZCAVr59KlWLmbaJjeGK5B3WTzCp/1k0Sn5Y5v0RO09tkheSOQYmlbS4DrHwPjLmDXjrROb9aKNUnSr3ONjpBOTSDwlqRTxg1qKAEOIAeJ22wZdoPOfANAf0e2vLCX452aiBoyogzI9h5ZPvYM2tlUzKCLSqe9AxYzRttXTgtJodwGn/IBhH9yWPZw/opvc9uoHSpvEyFHbLEbI95glnJ/D6ksBQMIrk2zXxnvFud52q0znDDkXbZ0MTOUlb8DSfuoD5WfoXMnxAiN40/tQsoFsTdiXgUb9yKre1IvFO282J+TOwQbasepDgFJeNRgtaqcBi6ZowzqNZFCBk4AWr5FhBjTrveOuOHdGhzKpQktndLRWZmHTaXBQ9nHzlqHkCBBQQ9rbAKxx/OSY5CIWNKtvacyFrLQDRbCt01UZliTliEpgLSTPdapRK+cu34BIbspp8UY8f7UZDJBREUkd8Bf/ujnQTD62o8MVWLHgo1dt0n1NNguh0hIHDMJPQik0tDhqsvA5EH/kd,iv:BDAR8K8RmG0NFai4YkDo4ohvvgZxOknTJgozkSk7BjU=,tag:RAED9A2AhpxzFzfN/68t9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpSNUZvcjA0
            UStWY1BMT1FWQmZ4LzdVMW1HckdOMFdOQWlQT056cXoxbW1rWjAxMVRYekJBL1RH
            cE5vQUFVVk8ydE40bWl5VHI1R1pLQXNjYnlWeXNidC9land6cHk0YXhxSjR0M0lr
            TXd0OFFwNTdOSUFwL3phYWJrS1BXbmRzbXhIS3BDQzBxMlZ4TVVYc0JSZk5QRCtF
            QUZnZWY3S09qaHUvZEZoV0gvdFFvSVNXaEJ5NVQzTjhqdnl6YkNIdnVMdnFkeWpX
            UHRiSnY3Zld1UDF1ZElJbTR1MUZvdkNOR0l4TVFQUkVZQ3pPM1V3dGNoVGhRVmFp
            OTRPeHQ2Y3hPV3RYb0MyYjFYZ2g4em5jdXdsQlYrS2xvZGd6Ymd0clpHNGVTM25R
            RXRCc05IcVRITjNWUEpsL0ZaM1NjTnNwVjkwUStCaTZya0t0K1FLTzhmSnc2QU5v
            ZVM1Nk0vTHVRU3V0SGMycm9qdjdpTXFEaHZYRTArOXhVZTFxcEdBVGxyQ2V2aGlS
            VWtGYnA1eklLdWxZc3VCZElHbFp0aFZuZjIrM1ZyZkUxZWk5STloSVRIcytLSVA2
            T01ZR09JRERuaUtmN2YxNXJPVW9xTWJRT09nQXFjUWdtR2FNdU0yQVZQLzZ2bFBO
            ZGNTNXlkS0hXMkp5WkE5NTV1MldhVURUNmJvM0hwanhCWnBNMklYenNRZTRZcnMz
            QzV1cDZtdU5Nd2h0cHR5eEpHbmxqUlgrYlhjMjlkSVFnSjRDc2gxOUc5VGYybmdm
            NGJRWGFJZ3dxQWRFbW1YQ1BJcXg0M0hweTk1UTY4c3dmSzhaNnUxc0V1OTk4Sjhl
            NmpmNGJsT1gzREIrcUpLR3Y0bUhyVjVZWU1ENUtEQUU5S1dtWGJZR240MnFaQlNE
            enN2dWx4eEE1aVRLSFlOdVFCZHlZb3hLKzUwVCtlQWJhaHJlREVMbVZzUzV2UUZF
            ODBLNncwNU1DM1JzUjZoRDV5bXVsTzBVbFM2ZzFTSWkxUmhmcjlGeVJZS3c3QTRt
            bVI1Rnl5MUYwamROc28zRUdueHUyMXhFZjVTZVRUMWd6Y2ZNU0k1Qjl4VlVCb0NW
            cjQxWHB2b2cyYXNjK2lKOWNEL3ZCZUFlS3RpaW03M001UWxZa0VBcmkvdVBtYngr
            ZXVDMU9lNU9rMjVpUm4zQjFvWHRRK1FwUnNyY1Q2eWJFQXN3d0htYWE1VlBlck1n
            RVBYVXk5UXRTTnJTb0xYRlNpYzRydStTWitPTWV4d3NibENXTTRPQS9XOEIvWlc1
            Ykw5MFJXalc4Rk1rRUVFZENXR1Fzc1VGZHVxUmFYM2c3SmlOdEY0U2lXejZWQmdn
            YS9VZW5sUnVBM1cyVS83amJVWmg1VFF4c1pIdEhiUWRCbmx0bGNoN3BPQlo5dm1P
            aDNoRnpWYnlPNjA3bldiZW1yM2RrUU9WcmQ0eG1lQUp1YmZLeFZ5NzhkRXEySTBx
            Tm5wdWpaVFFTbmh5bGlrckM2TUx1QUtVZEc1Wno2dHBoRkVBeDI0K1E0MmNITTdM
            WTNhWSs2WEFtelcvZk55cEJHWE1WRndSOGQ0WWJFcmhiVzV1ckYrUnZvNXJZck1i
            UjJlb3BEaWZ1Z1Vaa1pCS0pDL29vYTBmaUZXQ1hBRlE3VmJ5UjZ0eUsrT29OM0w0
            dTFiUEpCZzFNNm82a0hYTm9iMEtsYzZBeFU4YVJLdUV2dStjY08vSUlONTdBVmVV
            NFQ5SUh3aE9LSEh4L3Z3VXc4NXRZODJXOUZSWTFBY1RPLzAvUGEza09qTzkyZ1Zs
            K2w1MHdFZ2lrb1hPMnYwb1hpR0xWUHpCOUphb1dnOXVGczR4azZkdzNBamg4UmNQ
            NDJOVUM0MEJHUTNnMVZ3cUxwZ0pFbGt1OHYwYm0wWFJjUEpKSEdOSnYrQmJ0N1VP
            T3ZHWEFJWWJkOW83ZXZSWGNBSDlaUU83MW9RcVNRRTZSeWdPUmFxZHFnYnNEUQpF
            ZjIveHF2aVcrZGRPQU9xZThDd0RDNTRzRVJZRkw5eDhDTzc3aWFYMXJzCi0tLSBH
            RUJXcEVEVnVwWkZ6TkczaDdzZTdoMjhiVjFQbHJxZHRlaWtpUnE5VFcwCpBOrCyB
            X6lbAuADpkeELs1DQm2MxLMVG6KetpdSnLBuA/ZH6AxMwPb+gqdIECvm5oPzwq00
            x4g3hJAYFaMTJGc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-12T20:14:13Z"
    mac: ENC[AES256_GCM,data:k9Jnlxun6g0UdXBNefw4NxBDVN0NV7ppvl370phBCD0SW0zxf3PxElUjcjFA77+SDbaJBo3GQmMLR/HU9mI03SZmMlCNo60iJ0zwnEoJ0p9kU5wqHyD16pczr8CKAMBwaDtCtousyDV/rgv6YAdwiPvjGG4ypILGsbao0f23rIQ=,iv:P76tzk81tcwYJt8y3wa+X+om6CLIcWSrUlKTbzUo3/g=,tag:aJiALeM3ow0UwA94UvGOtg==,type:str]
    version: 3.11.0
