---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Ti
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-incomplete
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Ti
  storageClassName: local-hostpath
