apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: media
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R72PtYk2wA==,iv:rlafMDCdc/V5gQBnNeRjamOxSW3a2kNH/rjkCl4hkMY=,tag:bWvd0fdZa9DZHrHaXpBqDA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:Umu6e9vgrjo+,iv:btg2P4ub/V1Ue34ZPwxUYHYnd0HnFX3Yd8eM4MZBkuE=,tag:cXq4blXGHTTRO7KCG1bhsQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:2PXjFxm0lFn5GxhLqrUWGsQhQZtTHZIFFxXpO4pv2lVBNuGpv/IfkwcEV/M=,iv:Y6WmBRi2W6pEDWCAcvtU6U7uDe9fYB1xU6Qp6zVpxSs=,tag:zZDpWd373dNe/e5JF5OWzQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:VJEqqOCuNtoGjKRPbk0Mog==,iv:LF6Nipt7ILxt6JWcN12nXTzNbjfghWugPp30ilxjzUM=,tag:wNLv8yQiaXwn3lQU1BYONg==,type:str]
    OWNED_ONLY: ENC[AES256_GCM,data:jT/0,iv:IABX50+xbuqWw9DB9QrLatkhwOd//qsRRBngVIW35fI=,tag:+Ny/FzuxhwwvPYOUUMQh3Q==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:+X2PXl8fJ9+NjHg=,iv:yFICb9FvqFNdLp0eJDCQYSwweR4YVdq2nHnnawmxCuU=,tag:110QMk0hVMX9QaLlQ/uaMw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T23:32:31Z"
    mac: ENC[AES256_GCM,data:1UTOHyXWSOkp+/UKb1a8bivVO9clEi2eQEGMN7ztV94W6AR4riP8vwc8DE7+FLBnkXPszisurufYXjQUMpC16WlgJxBlli41py6Fy6UcyaYwiwKzm4DIjYQjN6xIEDouAX+eZiGFaa3J2UbZUK8tPJxd8cm8FBKXeWjcYsg5eZI=,iv:1NQkoGmZ5hUnX/I+joJUsexA5ogBYvElSra2QRAX+j4=,tag:xBWSXht8kI0f0Esv34TKeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:osJoJSVA2oXGVx9S7fA/hTDs20EGP0AVZkcslucI+UzLpbsV,iv:SpuofUyymYnq+6AfBpUCjZMu66KOlugnksGATM4MMPQ=,tag:7Wvm/ZpZAtYGjnQxxJCM3w==,type:str]
    client-secret: ENC[AES256_GCM,data:Cx8Qq1sS5i4mtKILmrVvVOFQn7xHBEkcgY4Ak+9OjmQ=,iv:BW733ipTbQ6vAOqG27sFGyIzOF7bqz4pLG2kDDweMbc=,tag:7Q1mWK3V1AGp2CE/9KBM5w==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T23:32:31Z"
    mac: ENC[AES256_GCM,data:1UTOHyXWSOkp+/UKb1a8bivVO9clEi2eQEGMN7ztV94W6AR4riP8vwc8DE7+FLBnkXPszisurufYXjQUMpC16WlgJxBlli41py6Fy6UcyaYwiwKzm4DIjYQjN6xIEDouAX+eZiGFaa3J2UbZUK8tPJxd8cm8FBKXeWjcYsg5eZI=,iv:1NQkoGmZ5hUnX/I+joJUsexA5ogBYvElSra2QRAX+j4=,tag:xBWSXht8kI0f0Esv34TKeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
