---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
spec:
  gatewayClassName: envoy
  listeners:
  - name: arr-stack-socks5
    protocol: TCP
    port: 1080
    allowedRoutes:
      kinds:
      - kind: TCPRoute
