---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: forgejo-disable-waf
  namespace: development
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: forgejo
  lua:
    - type: ValueRef
      valueRef:
        name: envoy-external-extensions
        kind: ConfigMap
        group: v1
  dynamicModule:
    - name: composer
      filterName: coraza-waf
      config:
        directives:
          - Include @coraza.conf-recommended
          - SecRuleEngine Off
