---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: forgejo
  values:
    strategy:
      type: 'Recreate'

    image:
      registry: code.forgejo.org
      repository: forgejo/forgejo
      rootless: true
      tag: 16.0.1-rootless

    httpRoute:
      enabled: true
      hostnames: [ "code.${EXTERNAL_DOMAIN}" ]
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
      port: 8080

    service:
      ssh:
        ipFamilyPolicy: SingleStack # todo: remove after apply
      http:
        extraPorts:
          - name: anubis
            port: 8080
            targetPort: anubis

    persistence:
      enabled: true
      create: true
      claimName: forgejo-code-local

    extraVolumes:
      - name: anubis-bot-policy
        configMap:
          name: anubis-bot-policy
          defaultMode: 0444

    signing:
      enabled: true
      ssh:
        existingSecret: 'forgejo-ssh-signing-secret'

    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        passwordMode: initialOnlyRequireReset
      ssh:
        logLevel: INFO
      config:
        admin:
          SEND_NOTIFICATION_EMAIL_ON_NEW_USER: true
        APP_NAME: 'Git Invaders'
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        cron:
          ENABLED: true
        cron.archive_cleanup:
          SCHEDULE: '@hourly'
          OLDER_THAN: '2h'
        database:
          PATH: /data/gitea.db
          DB_TYPE: sqlite3
          SQLITE_JOURNAL_MODE: wal
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs:
          PATH: /data/git/lfs
        log:
          MODE: console, file
          LEVEL: 'info'
          LOGGER_ACCESS_MODE: file
        log.file:
          LEVEL: Info
        mailer:
          ENABLED: false
        oauth2_client:
          UPDATE_AVATAR: true
        packages:
          LIMIT_SIZE_CONTAINER: '2 GiB'
        queue:
          TYPE: redis
          CONN_STR: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        repository:
          ROOT: /data/git/repositories
          ENABLE_PUSH_CREATE_USER: true
          DEFAULT_PUSH_CREATE_PRIVATE: false
          DEFAULT_REPO_UNITS: 'repo.code,repo.releases,repo.issues,repo.pulls,repo.actions'
        repository.pull-request:
          WORK_IN_PROGRESS_PREFIXES: 'WIP:,[WIP]:'
        repository.signing:
          FORMAT: ssh
          SIGNING_KEY: /data/git/.ssh-signing/key.pub
          SIGNING_NAME: "offene.cloud Instance"
          SIGNING_EMAIL: no-reply@offene.cloud
          INITIAL_COMMIT: pubkey
          DEFAULT_TRUST_MODEL: pubkey
          CRUD_ACTIONS: pubkey
          MERGES: pubkey
        security:
          REVERSE_PROXY_TRUSTED_PROXIES: 127.0.0.0/8,::1/128,10.42.0.0/16,fd01::/48
          INSTALL_LOCK: true
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          DISABLE_REGISTRATION: true
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_PASSWORD_SIGNIN_FORM: false
          SHOW_REGISTRATION_BUTTON: false
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          MAX_CREATION_LIMIT: 100
        service.explore:
          DISABLE_CODE_PAGE: false
          DISABLE_ORGANIZATIONS_PAGE: true
          DISABLE_USERS_PAGE: true
          REQUIRE_SIGNIN_VIEW: false
        server:
          ROOT_URL: https://code.offene.cloud
          DOMAIN: code.offene.cloud
          SSH_DOMAIN: code.offene.cloud
          LFS_START_SERVER: true
          OFFLINE_MODE: true
          LANDING_PAGE: login
          MINIMUM_KEY_SIZE_CHECK: true
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
          SESSION_LIFE_TIME: "1209600"
      livenessProbe:
        tcpSocket: ~
        httpGet:
          path: /api/healthz
          port: http
        initialDelaySeconds: 30 # default is 200
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 10

    extraContainers:
      - name: anubis
        image: ghcr.io/techarohq/anubis:v1.25.0@sha256:5cf4c0d6c7ea01a356c6685a779971bdd28d6a5a4a6719201f73a9c4ae108db0
        imagePullPolicy: Always
        env:
          - name: 'BIND'
            value: ':8080'
          - name: 'METRICS_BIND'
            value: ':9090'
          - name: 'DIFFICULTY'
            value: '4'
          - name: ED25519_PRIVATE_KEY_HEX
            valueFrom:
              secretKeyRef:
                name: forgejo-anubis-key-secret
                key: ED25519_PRIVATE_KEY_HEX
          - name: 'TARGET'
            value: 'http://localhost:3000'
          - name: 'POLICY_FNAME'
            value: '/etc/anubisBotPolicy.yaml'
        volumeMounts:
          - name: anubis-bot-policy
            mountPath: /etc/anubisBotPolicy.yaml
            subPath: anubisBotPolicy.yaml
            readOnly: true
        ports:
          - name: anubis
            containerPort: 8080
          - name: anubis-metrics
            containerPort: 9090
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities: {drop: ["ALL"]}
          seccompProfile:
            type: RuntimeDefault
