---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: anubis
spec:
  jobLabel: anubis
  namespaceSelector:
    matchNames:
      - development
  podMetricsEndpoints:
    - port: anubis-metrics
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/name: forgejo
