apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:6Ltb7tCjXCQ=,iv:vSXiLQKnfksNOkpQECX2OopAz8eEvzWSVtVBBsJVYx0=,tag:S/MuOBw8SNbOmRbM9l4CsQ==,type:str]
    password: ENC[AES256_GCM,data:VFBP2J8bKd3GPWlN5xNJ,iv:T++ftOJzt93F7TL+BXE8dHQMM44BvqzDytn71+TZbFU=,tag:VdHO5FAobLL0UYXw3GmyeQ==,type:str]
    email: ENC[AES256_GCM,data:pQ9QhR1BfBNmTFNj7lx8+hy+,iv:pDkmxOLAgA6eE/jAALsp4MV07RYjFnwBdpJ/ajbQ+iw=,tag:ZgmpBWbSdch5KtXlbKVFwg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T17:52:15Z"
    mac: ENC[AES256_GCM,data:cLmjDy1i1ZXWZh7XhUETU8mvz0fSUo+HBRwwlfQq1AN5XE8qawRiWbTuPOKTY7fH+UR6IoI+w1IR/hmCYFhaSvF6vtsDcKrWb79GAn4SVHiDiFDAPzzVJ+LrulFHUZcZ6qfkYTbLt9MDHLcSlQDytAR/rZw9BSvyyakP8Lqmpsk=,iv:dodQVVLrXvNNuC4S3tTUIrVoSWdcRhe7bI25NRlZGkg=,tag:rLWDJzPUEtDyG/zFP86Xww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-ssh-signing-secret
    namespace: development
stringData:
    privateKey: ENC[AES256_GCM,data:wci33NnbwZ/DaUXYNg9P7o41ISMAPrAN4V3EM8prLqq3ifPWRO4nGPfSHHgvnslpwAXiWEi9WAPqMXxBZJAXFQa87oeHtbgNNTRZzs9O2ZnXaon3B3SYoWKtshUaLr2crjqx3QlEIFGw4gAHrowgT4JMKXx/Io05rcXaHki4RJFFPnzR7Tu47wD1FgP2IWza4AKI1zNo0VXVG3UpcplYqxA3D4No7LLR+peYXTZg+puVsNzATO2A7ZGpY+54bc1EnCGI7mVKmBzT8KVKwMKq/M3bxxtmiipwer+81tgrmpXt8RAqE6DBqkVav5W0ZDJenvl55qQiIXNOsLvVrXBMULUkY1D2v8hhnIimK4npjgZM1C8kSyN3IyctlfKAhSNa0Vbe5mJjeeLwgTUpYz4RRUhLKyHkJSCsaNERCJ9h78jwFjrG3LTs4SLNKDgdJMcBnoEtF0tALoFkorhpCYBfG+etPAEH7/PeATE6P6nbTar8VWwQHaVmCLMpC35RqFjhmIwkQ7bx2PL2OaHrxC4frkS31LIaQYiJZhi7,iv:OafBygAP1qSsxKfuB9IJZOhEFCVDvjuCmbUkYiZphq0=,tag:U3RuB4uishnQQTGWB4/Mmg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T17:52:15Z"
    mac: ENC[AES256_GCM,data:cLmjDy1i1ZXWZh7XhUETU8mvz0fSUo+HBRwwlfQq1AN5XE8qawRiWbTuPOKTY7fH+UR6IoI+w1IR/hmCYFhaSvF6vtsDcKrWb79GAn4SVHiDiFDAPzzVJ+LrulFHUZcZ6qfkYTbLt9MDHLcSlQDytAR/rZw9BSvyyakP8Lqmpsk=,iv:dodQVVLrXvNNuC4S3tTUIrVoSWdcRhe7bI25NRlZGkg=,tag:rLWDJzPUEtDyG/zFP86Xww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-anubis-key-secret
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:vyxzZvLWb4FBVUQ9afeuERuP0qp6ouA6SPMNTfHJuHBa5A7m+mT7YNx7G7NtyiT5p7AILW+9Yv15qteRX2vwyA==,iv:xKE8zqwqSCOku89PHkRw/KB5W4FBiu/iY7De+3l2UIo=,tag:Ok7mzQmSp0yOkcrn/F588Q==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T17:52:15Z"
    mac: ENC[AES256_GCM,data:cLmjDy1i1ZXWZh7XhUETU8mvz0fSUo+HBRwwlfQq1AN5XE8qawRiWbTuPOKTY7fH+UR6IoI+w1IR/hmCYFhaSvF6vtsDcKrWb79GAn4SVHiDiFDAPzzVJ+LrulFHUZcZ6qfkYTbLt9MDHLcSlQDytAR/rZw9BSvyyakP8Lqmpsk=,iv:dodQVVLrXvNNuC4S3tTUIrVoSWdcRhe7bI25NRlZGkg=,tag:rLWDJzPUEtDyG/zFP86Xww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
