---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo-runner-next
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://code.forgejo.org/forgejo-helm/forgejo/forgejo-runner
  ref:
    tag: 
