apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-next-secret
    namespace: development
stringData:
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:7ABtr/hLRWMhY/M9kPtH+rb9q4hlekYBKg==,iv:zH2EtnbQqc46rTY+tRoiQJFCJ5r5sxAOtk2iF86J9nk=,tag:k3s6A+5lxFjUb+Hlv4zSBg==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:qLtAOFMyfvXwTlz8TX4cEdh1m/uOcc/oJcKeNdAtb3ja75LOey0IPA==,iv:8qZG8EuBG4FXrF+apbp9g2vHXlwWuQJtCGs7XVQK66E=,tag:iVPlVTd3fgDknkXGnE5yog==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OWhQS2YvR0s1VURkcW1S
            aEt2NTZzZit0Q210dWZjNFcvekVtaUVseXp3CkN1RGFvUWdWWnlHOS9lV1dBY0FH
            SjZFUnMySXRRYm5FaVVCMkFpSHk3bFkKLS0tIEh0VHRJazNxLzRvaDVPTS9BbjJ6
            NmRjMTBUTWpMUGt2R2x0NmFCRG9aYkkKuf20zqT2YzTQ0huN/vmI52KBbb/zzi5q
            oipkjSgdeon/wEz94hgP2pMc6V8plNihFAdPgEutLJELRHLpjpiyDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T14:56:09Z"
    mac: ENC[AES256_GCM,data:hQuEuxN6XTV36vTACi+gVcVPHwhofTG+s9OwwWo0LT19lXaEtiqIN2hxr0u9jI7IlhLc6rxrOtAgJ7JpRzTS+0JVVsCPsfhT800npeyxKa1gWE2kLK2AMnIIr6hB+jMJy8TCLlJWPDUnHCYmy93hvnm2lWwJCU1M+D7uIg3gCXY=,iv:bdWfDGW/kDajxTsOYi/CYxLEMQB8JxQaYfeZPtq7IKg=,tag:ZSdzAJsyDaP0LQOH6eQvFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
