---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headplane
spec:
  chartRef:
    kind: OCIRepository
    name: headplane
  interval: 30m
  values:
    controllers:
      headplane:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tale/headplane
              tag: 0.6.1

            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

            probes:
              liveness: &probe
                enabled: true
                type: HTTP
                path: /admin/healthz
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "headplane.offene.cloud"
            paths:
              - path: /admin
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "headplane.offene.cloud"
            secretName: headplane-tls

    persistence:
      config:
        type: secret
        name: headplane-secret
        globalMounts:
          - path: /etc/headplane/config.yaml
            subPath: config.yaml
      data:
        type: persistentVolumeClaim
        existingClaim: headplane-pvc
        storageClass:
        globalMounts:
          - path: /var/lib/headplane
            subPath: data
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
