apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3Uayx6m0IHe3ERHacAp0eT6kEPc=,iv:z632BcXtcXmZkRiKic1wZHOEGBQypSQXRWIoAAZrmfQ=,tag:8qKOOAnxzX1dt9qIr1R2TA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ygIOXuaAaomEPdm0bESbZAfZlxMwyVbtJwaWOkTVm25Ojt2SiZL4sg==,iv:b5GJbYVEQ+V3VBhIPeLlEpFvHfG2Fmn3EHm5mMmqC0c=,tag:TNljr3iAK2yzZaEFOAwBXg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:impnhGKIdMTFe6lcThRdvohf4DjcRrGTwfT4QcuVLGksSRobFMJwbCEpqMfpYcgok3eYGYavCXNgIYuVO1dTEYMu,iv:2nq+werEmRqg6wO31Pheo+tbS/k04aGlZzanvG56qHI=,tag:Cp+z8Th10bdfG4wKsAglBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBtek1tMzVP
            eTN6UlJzNHdlR3o5ZlArTDRRVEFZdXpNdmhZd0FJSCtUb0lkR0VEUXRZMUVhdnhh
            QWwzVXdjbjhGTmgrTjhzalRxTWx0Q1plNHV1d1RaWHMwOFBmbG1FN2hxWmIwK2dh
            b2dVY2lYN3d6cWlWeWtvYmkxWk40RkJVUkMxY1FBajZ0blVVUVl3Mlhxa2xiZkdm
            cTJSVElPNGZBSzg0MlZEN2luMUlCaVEzckx4S2JsZ01jNVNCeFRtVjA2NW1yZU91
            MjBiak9QaTljSnJ6emQvejdFQlN3WUQxL1oyOXlkVUdSNmljejJjRTBjSWw0NkU4
            Rml2WmxpVVo5VHA1Tjc5azdUdGdoRmR4elUrZnNhQ09UOXY0dVNkNHluRkYreWVy
            Z3NvTVNUT28xT3R0NHdxYTZqN3AwazMxUm16cmd5V3NTaCt0U1I3ODd0czNxdXFV
            RldFRE0rd1ZZZC9XZnFZZWVaM2U2bzBYZ3F3U3dYS2NDNGdrd2NsRXkyUjJXU3pJ
            QS9XWmRGbDlwWENwQXlWVGdMYmpGbmpLcEZGU0pXZ21kKzhsNitlMlNwdklWYnNw
            WndBSW9MMkV4aTY5RU5yRFFqQ0N6YjdJNlRxQU1zR3RDZUY1UkZ4elgrZi9MSCti
            TW52a0lRQXNpa1lod1pJWFZqbkNMMTRJTkl4TGlhMENkalhHekNXUExkcks1R2tX
            dGpBOUlPUStVVndCWUR1RGNmSGY5dlFrSGtNRmdJSDgvNE44MVRvOGlwdVArNDI4
            M1BEVjdiVVdJSFVOZmFsS1dVNlBVYUszd25vQ2FDVDdXOWpMMGtoWi9oOGRsZDNP
            Z2psaldEMlcxNWZPbFZyWmtEMFQxRmlBU0w0RW1Gdm1MNkx6QlVIRUpPUVBXbkFM
            YjIxRTN1TDJnK2VKdHRzU0pwVHRwaVVDMHA5MUpOY3lCZmxhTnQ1ay92TStOa0JX
            dVNqWkZPazI4MktCOVJJd05wWm9TTG1mRzZORi8raHVFL0poSVJGaEY0TzB1RlJp
            YWFyNlFKcE1vd3h6T1dNL0JuRFdUVUI0UFV6TzZyR0tSeGZTTzlITUhnaGIyUkRy
            Mkh4SWY3Q3JJekxKbmU5U01wbWdGOWd6cDg2ZGltdTFrZ3UxdUc3WGZPUXBFdDJW
            QWo2cCthaHFWbk5kQno4d011eFNoVEZORE93Q3ExUUhSTkR5ZDVlSk93aUQ1b1RM
            UUs3Z081QmljaVd0dUJ3RDRudEQ5TzVjaVpoOHVKc2s3ZU14RDljOGpJV2xCT1di
            S2N5WnBhUnF2T1hwUmhxbnRxWGpudjdUTUxVWU1lYzU3QWU3YXBRaHYwbnhhM3l5
            UHFrMkhZazVZRmZMYTFXV1kwMi9hc1VHV1ZqQUxCeWthSjZBWmxaN2xRNi9FUUNy
            NkhNbC9haFRuMWNjVms3bW1qSEplb1VEY2hxV2pNTk9UajVYdksyKzZYclM5aity
            eUxkL0JYODYwM3AvOFVjMmdkd0NTV0Y0R1BoMWx5Q0RTVXQrVVpmWXNKbTcvT3Q3
            T3B4dW4vazh1aXdJaTU3cmdnU21CVllzcEc3c2hBL3EyTlFla1pHN2dNUzRxcENK
            Q2p1dVBSUUNTWnlEYVRGb2VZQ1NzQnozc2JmSHg5NUNjdGh0UW5uN0hKZCtKT0Nv
            Z0xzU0lzWmdTbFZTSlZpcytGeHQveHJ2bG10SUluQkgxSVhXMXZNNEo4Tm1uNnkx
            dmFNRGx4Z0VndWFXRlh5Q3RrSERrU293SXF3N2xpcElXN2NnWlg2eUl1M2JRejUy
            a2J6UXRVa1lhMEdLRGxydXJoZU9aOVp0SjFkV1c1L0NIVkpMYkw1Y3JIdkRFQ3Er
            ejhoaVZ1aGtHWHQ0K2lrdmJ1VnhEcmQ1SWdZME5MUlBIUzI0eVN5VjV0c0g2MmJp
            NWZ3V203MzdUWUVmWjRrdFVXcDAzQ0FsUzNMbi9WODBlS0hIS0FFa0kzMTlDUQpX
            YTlRaTZwN0VzcnJsbnovdzdpRnh0WkxFQlZ0Tk9pUFZnUE1acXFjdVQ4Ci0tLSBO
            bXVvdkVIaXFKbVNzTjRWS1l4MDhBUkduMzlNSnlzcG56SFl6Sm9tek9RCtiX7AQo
            7XlGOASKvpkoWqoCXipSaRL5LPjG+vmar2UFNq7aM77tmbfW87TV9p93OIK0SAHZ
            7hr//LwQhm5L2eo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T23:53:52Z"
    mac: ENC[AES256_GCM,data:TZ195s4Zc68BbibJirL/f6YSDKxs6qn2EQJLudgPHLXib+d6hsN7vRjNT4Zx1UtJlxEVNlS+2rdTa1UL7CbV9q1161KbItNtztWxENFk6jLyR0jED8CLJnl8Rgi9s9f4gZtPyIXQ7cYHeHOsZNGtjCLTcEg/3Aw1sNlqowz59+c=,iv:MXLBeSb/1ivw9aqinkeYN5Eu591Q+FkKbyZ6J7wSpLk=,tag:gHCWZR7nITLk0S/WqLYfSQ==,type:str]
    version: 3.13.3
