apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3Uayx6m0IHe3ERHacAp0eT6kEPc=,iv:z632BcXtcXmZkRiKic1wZHOEGBQypSQXRWIoAAZrmfQ=,tag:8qKOOAnxzX1dt9qIr1R2TA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ygIOXuaAaomEPdm0bESbZAfZlxMwyVbtJwaWOkTVm25Ojt2SiZL4sg==,iv:b5GJbYVEQ+V3VBhIPeLlEpFvHfG2Fmn3EHm5mMmqC0c=,tag:TNljr3iAK2yzZaEFOAwBXg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:impnhGKIdMTFe6lcThRdvohf4DjcRrGTwfT4QcuVLGksSRobFMJwbCEpqMfpYcgok3eYGYavCXNgIYuVO1dTEYMu,iv:2nq+werEmRqg6wO31Pheo+tbS/k04aGlZzanvG56qHI=,tag:Cp+z8Th10bdfG4wKsAglBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueEIwVjVTRmxEODd0M1A5
            WktqU1I0b3NoaTd0NjFEWVI5NGNTbzg2MGtVCjJFSUxEbSt1bDRvaTF0dVNJT0Vr
            QWVuM3NjNFFFc0xVa3I5eTY4ZzgrakEKLS0tIDlJL08rOU1VT3pmekJuYTE4WVVB
            MXUrNEppanBnaUZXSkpYaitBTnNQTzQKZaT5lKD7bzznbIofmmLQ0ec10T8ZD3bp
            TqlOepk7xC1wuWlwdRKCu3pTXEMURwlq1CYSi4oMa2/dtTEN8uaGYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T23:53:52Z"
    mac: ENC[AES256_GCM,data:TZ195s4Zc68BbibJirL/f6YSDKxs6qn2EQJLudgPHLXib+d6hsN7vRjNT4Zx1UtJlxEVNlS+2rdTa1UL7CbV9q1161KbItNtztWxENFk6jLyR0jED8CLJnl8Rgi9s9f4gZtPyIXQ7cYHeHOsZNGtjCLTcEg/3Aw1sNlqowz59+c=,iv:MXLBeSb/1ivw9aqinkeYN5Eu591Q+FkKbyZ6J7wSpLk=,tag:gHCWZR7nITLk0S/WqLYfSQ==,type:str]
    version: 3.13.3
