apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    KOPIA_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueEIwVjVTRmxEODd0M1A5
            WktqU1I0b3NoaTd0NjFEWVI5NGNTbzg2MGtVCjJFSUxEbSt1bDRvaTF0dVNJT0Vr
            QWVuM3NjNFFFc0xVa3I5eTY4ZzgrakEKLS0tIDlJL08rOU1VT3pmekJuYTE4WVVB
            MXUrNEppanBnaUZXSkpYaitBTnNQTzQKZaT5lKD7bzznbIofmmLQ0ec10T8ZD3bp
            TqlOepk7xC1wuWlwdRKCu3pTXEMURwlq1CYSi4oMa2/dtTEN8uaGYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T20:06:54Z"
    mac: ENC[AES256_GCM,data:LKERyxahEPAQPUm7ypO82Dh1h1bskxvfsWXeAyKCkeGXtartLCnn+manYTjQVmO56u4EeS3O+HO5q91x0IFDthUQxsDUcjAIaUv8akTUcY7WIH7Xj0xTqf3eTOBuorz8rJBZrEQ2A51Y/e+lHui+h22hsqYGUawIqPTRn2/beFQ=,iv:WEMa9LWg8kKQtG4p+hw+nYk8XKqSePywsZ6xR38Q6MM=,tag:S4eIyS5i2YFXW1OxtQ/yUw==,type:str]
    version: 3.13.3
