---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 1h
  values:
    fullnameOverride: renovate-operator
    auth:
      defaultAllowedGroups: "admins"
      oidc:
        enabled: true
        issuerUrl: https://id.${EXTERNAL_DOMAIN}
        clientId: "d6a40507-922f-48e0-8365-836381fd4c32"
        existingSecret: renovate-oidc-secret
        secretKey: client-secret
        redirectScheme: "https"
        groupsClaim: "groups"
        additionalScopes:
          - "groups"
        pkceEnabled: true
    route:
      enabled: true
      hostnames:
        - "renovate.${EXTERNAL_DOMAIN}"
      parentRefs:
        - name: envoy-external
          namespace: network
    webhook:
      enabled: true
