apiVersion: v1
kind: Secret
metadata:
    name: garage-webui-secret
type: Opaque
stringData:
    GARAGE_UI_AUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:/NJUSs11ldpoekXwwyzsnuI5CV61TB6La2u0NvSG5aFsXsMd,iv:4jnGrdiogbx95CABnKDVEuURn30QUgKUlFDfT8wMC/c=,tag:BoKg01u8RK3coc5xMBPqZw==,type:str]
    GARAGE_UI_AUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3SYt5aBL9CWorvaOgIe3IenhEClfh4SKB/VWif0OXZQ=,iv:Sp3fT/AvLhE+0D+KJMMs9LIr9Ao3X2ryXhHIF//LkEM=,tag:ObuHC6TpVqtvcYjOjHTxyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFhOSWdJdUV4WkkyMysx
            VHNGdlM5N1BtRVBOVWFWajkzcUwwaXM0UHlvCm5pQWVQVWNzcDkxNmJlYWJJTFMz
            cWJkOGRwaWNjWm10RmVtTjIzakZZdEkKLS0tIGFybjNvVWR4K2dsZmgxQ1RWZEsr
            ZkdOSXYzSEpzQ0kwTUh0YWhxZmU4RWcKyKWU6QwCIyQ7NW7ii3/3jh37ateF5EF7
            zJDpPfmhqOSWWjKhlAR/swtSoDIUfb0yC6+2LDMZWvGDrZybCTrBIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T14:30:25Z"
    mac: ENC[AES256_GCM,data:p7xeWOeMFUzD8hk+p3K16kbudHfgE7TNzCcxiigh3SqSEogeOD3tYtlf2Ys55a8aX1lK8C8v02ZAL6SNILiW/A2v3HoTFVNBGDwVTMn0hSPxoENi+RNEg7ICqiVIPeJwiWPw8htS8PvG9zzSyIK0YY0DQpabiLclchAGi1LmJwQ=,iv:TYAoAr45IQlh6ImNXpUEyjjJx8O36/MkWuWPc6yY/1w=,tag:Pu7jSRIwVrelCnYwHESo8A==,type:str]
    version: 3.13.3
