apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:sfLsBSrLBX2yiNmWC+sZmcrM85QVGlecj9jebBbBSEDtWQ==,iv:n4yAD6NQtkIg2/t+HV7aYoYb/L4ReU78v02qVtjFXKc=,tag:qn/fBYC6nPQ57OYsXQzz3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhjNStwN1pP
            VUxFclRjSGw4c092c0JtNUhpNDA4QXc2dTJ6QTc5WC9SZmZoaFZhclkyQ0RqUCtv
            Y2VZUklmS255RHduTkVVeHQzaWREd0VXS2ZkVWMzRUN3cHFzeXUrZ0dZUDJNNnFs
            bkd4eFduSE5IWjNyTGNpVkVmdnRzMlhCQzJBTHZQeUhRcEtnU1hnREcrNVB3cm4x
            eko0dk50dFJ1QWprRzlDMTViUVpFK3Q4ZXdlN1JlMU9aSnJEM1lUdXByT2Nhb3pl
            cUNZVDBaU1VtTmtmbDI1ODdmanYrbjIyWG9FY0p5N1hsd3FnU1RqTDlTb2Z6LzZ2
            cjJxWEMrdFkzSmF2cW9kMFo4UTB0UlVpR2grSEpjdTJUY0pLbUwxL0xYSG12ekk0
            OWFVY2M4S3pjMUhLSUE2NFpBVHA3bmtGSzNYempoTFpJWFlCbjdkSFpWSWFIbDU2
            dURvZ2p0MzRLb0RTWHRhaWFpOWlkVHZIQ0trMis4bFQzTHhnTFFRblhmZFI5V1U1
            ODZIZ2lzSHBLbVA4dmVxTlhkNEowU1pHK3picDdXNGZmeTZ6cFRBelBvcVBMVzA0
            a3p4MStLcExtdEFUUW05K3RuTXdFZ1hrZWRFK1AvaG9HMXo0RllkK0lCQm1FaHBz
            dERReSt2dDh5dExCS2RCQ1BOeEdUNUszSU55Y0x6UUUxZmRqUmYzZ01oZGFVbHpp
            bEVkOHkxSy9sS1c5SGJyQ0MrYkFkdGUwUWNYZGFKVE0xbnMwQ05IQmpxeEJlWWtM
            cWppWE5BVUNaUExQcjRjR09aK1YxOG1ucHB2cFFQY1JSK1JzdHRmeGRkRlFXRFYy
            ZlEycUdxVjNQNWNFYkpsaUkwd2Jxc3ZyZFRlM2I3MTlyT2RXYkdzeHpmNDdoRE5L
            akdzTytTUW5RNEdvODJ5VUQzZFVZN1MyeWFxaWNtYU41emN5dG92U3FlakJMNWxq
            MmNEaFU2R0VjdndINHlqVkhyaklPcFFDSFJNdEFOcktXd2tOODFZN3dOUS9ET0h3
            aFBTbzBxbUZQcVdmTGhEZFhrcWp4aStiamlybVB2Z0d6RjZ4VjU3Mzh4LzVZSzRX
            M1JKekc0Smc2QWNDRDZudW94NlBURmVzZnlGZFlSOXQrK3VNQ2wrajU2L0ZMSDNU
            K3JmSG1zUUlnbGhDcHdod1Y0anRCbG9mUVl2R0FadG1lbGVSaU45T2tubUJmb3Bh
            UlRiaWRKcURyOUxDRWNkZHpLYXZJMVVJcWc1dzJzbEc5blk4SStQTThoQXJKY0I2
            bkV3dXpjeHFMWjlrS3BPZlI3QzVpRkJSekQ1UXlOTC9YdUJmcmZzR2w1YXpaSWI1
            VVc2RmV1ZklUb0sxRTlrL1RrQzBBcGRDTlpEV2R5TEJlWXBmZUJBMi8vWWVsTTNn
            MmtBNW9MNks5dVU2bG5nMzlXdTd0eE4rdEI3bGg1eGNyZ0dQeDJCQ0o5TVBlSkZx
            S3VMaDJqQmJjakNQcWxteWFoTjVMWG4rdm52ajlBMWtlQzhVdDFQUmlxRDBJM3N2
            WDV1ZXQra3VrMHNPQldnMEh3emlCbDBJSDRhc0NYNUdYcndteWx3bXJYK3pMRi9p
            K0JpZ0ZVcEZiWDJUamJwdmFiNUZsc2lCUitCWjJ1bXl0SklKQkx2SDJMRUdQelJ3
            di9kVU5pY2pBUDBqc0Y2UGtMa1N6QkVHVU1VamwxYmZHaGJ4cXRvNmswcmlrS3pY
            Q2Q0ekZWZXhlREhZTVU1VDJSS2pvVzdYMkxLVGMrU1lrUGt2Nm9SbmpMVXFHQ2RW
            WTNNZ1RLdEJhc0pSTk5HTUx6aTBKTy9RNEJMNjNmZjU1U0hWVmZCaXRCRlNlYW1U
            VEtwY1RONEtwTlJIYnVnMmFJQlBhT1NVK2Zub0IrN04xTFVHOU9QU1QveEFSUXky
            T0RqT1gzbGdSNEFCMUF2NUZ0YjdMSWNEVWFwNGMvaGhkdmJqZ3ZUSWZDZDFYdwpl
            R2thS3p6bUtwNnJ2L2xRTW5CWVl6V0JlYXU4dDdJNExXU3lpdTZOVWxjCi0tLSB2
            UUtmbVQ0QUsyWXFWUGEveDFqckY0RnZhRVdtUWFSQ01sNURSSUd2OVFZCjgbccpZ
            sqnlWKbbq8MfLV4BTFR1xZr+/ykn0Bg48TyZ9yvSJh7ldaP7EpUWJSFx3m6b/SvF
            PBG8U9CsJZZSXF4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-27T14:15:06Z"
    mac: ENC[AES256_GCM,data:kd05cBRFqLly7RYyIxOSUWbIOHy/1tL8Ks1g0pND7MyIHgPOx+Dq0AQF4DUaWjzJyoSHOAaK/2d4xJpsCBNEKXXqLUQ+K5+zOgVPuF/HrO3LAyhm66BFPzGbeCSV8bqAX+wA9MHW8pv2f0UcN9/G0+ZkxyFn3lD8RvudCVQd1ww=,iv:aRAbabpM5yyfXrv5w/VmqD1Gp0uPQcKiWvFLSdwq2K0=,tag:REwCihyCaJjbdmG96RwyeA==,type:str]
    version: 3.11.0
