---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nas-route
spec:
  hostnames: ["storage.${INTERNAL_DOMAIN}"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: nas-backend
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: nas-service
  namespace: network
spec:
  endpoints:
    - ip:
        address: "${STORAGE_IP}"
        port: 5001
  tls:
    insecureSkipVerify: true
