apiVersion: v1
kind: Secret
metadata:
    name: konflate-secret
stringData:
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:aZzc901rMILq5kYzCe0UiTbYoRF7k3zmDCI9cmJRBy39L9LhUO99zDkZeDrmG81KcvxRYfWaQKORR/XW9AzAjA==,iv:RFYrYvJvtv1GdW/7OGlYJnNMg12nZ8TMy9DhED2pfX4=,tag:QG31XcDQQ5SIHqVdfY+9vw==,type:str]
    KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:GshOKw0zbymbf7owqnLckrhAOH17+NS5R1Dc720HK8D3W5T8aY7KGQ==,iv:BiSUj8vUkgRHepGgWaDC+mvhNzlcZfC+Pa6b8JZCCmY=,tag:1SyEZK1HTVhQPmFI+SeJyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T16:13:24Z"
    mac: ENC[AES256_GCM,data:cCDudltF97qzCFTb3xIDpE6/rBX8WXZpJCiYR+117F6DrXGDy+GGmejPSGoa3O5zq1zFupBA4GLjKGN+MC3bJh2K8o0CIvjOprN/+HpPUwGNeg/NKbkXAiXa/fHDK0vm0ZygpS++P8U0Pq4WRlPEv6aWfPWkwP1hOLXCmALTwnE=,iv:YERBAo9jv2CZyBQPNLJ9zM5SVnKkjfyVJ60YZkdS1Cs=,tag:PedZGbM4kBe9Z/WJMqCrhQ==,type:str]
    version: 3.13.3
