apiVersion: v1
kind: Secret
metadata:
    name: konflate-secret
stringData:
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:aZzc901rMILq5kYzCe0UiTbYoRF7k3zmDCI9cmJRBy39L9LhUO99zDkZeDrmG81KcvxRYfWaQKORR/XW9AzAjA==,iv:RFYrYvJvtv1GdW/7OGlYJnNMg12nZ8TMy9DhED2pfX4=,tag:QG31XcDQQ5SIHqVdfY+9vw==,type:str]
    KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:1kVrRms8bemTR28dhZSRasDf2tqG+ywmQO8xD5g3t7Psdfbbl1cBrg==,iv:Dhlo1RJEUpDMoxBuWOxyGK8QLildmJ7u/y0rbMsuEp0=,tag:/Y8/CBOtDmExHHxIfroKUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T16:19:50Z"
    mac: ENC[AES256_GCM,data:IfYOKliJxA51PxCy333BLzNI82uoCWDRDpzYQ7yNVcOcxBdm2JVxF1bLaZUYKzfubwndA4yYYKg+lIboYo0AC99mweH6GKaIsXvNopCcnfZkgZk+YZ7AhQCAVTtPUYA1ilHKSOKszsFDS4umd0RZG1oGUBkOmXTeer/OWV1onU8=,iv:IDILbfT/nxrVl8mi7TO+pHbLgjTZTU6v+B93BatCzcA=,tag:9Kx2Kv9UiMk0jcqXGuUO8Q==,type:str]
    version: 3.13.3
