apiVersion: v1
kind: Secret
metadata:
    name: konflate-secret
stringData:
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:aZzc901rMILq5kYzCe0UiTbYoRF7k3zmDCI9cmJRBy39L9LhUO99zDkZeDrmG81KcvxRYfWaQKORR/XW9AzAjA==,iv:RFYrYvJvtv1GdW/7OGlYJnNMg12nZ8TMy9DhED2pfX4=,tag:QG31XcDQQ5SIHqVdfY+9vw==,type:str]
    KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:mkmDch/lA+ZBpZkF3f1+DTO/8iklB8DyaroIvHSIOsNSht/53rhMSQ==,iv:WGYwk+7YJal05PVTPyuCORe6GDkGbnlCMleA/k01SaY=,tag:w62apJ6fQy0v2KWHFTRrrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:34:08Z"
    mac: ENC[AES256_GCM,data:lM8RWoUsfZjjomAxH37YXuabuCjPVu3asv+kXE+t7Zy+xqWLTJ4DxhE+KooE8UWBoWkc78X1iSSmmlS/aTNfSwR81uf6MJLXNUtqS8C+bIRMmRk243P85ngadrF04yVY+QRaSJhdntakP7tYzwMDBIhIkZ5UrvXl6lJ+b4BkoQg=,iv:aG1j1k+SO1czYRoRJz8V47epvCQwf4bBqFpCajKpFjI=,tag:AmeXNtt/2+N8yKuygioUqQ==,type:str]
    version: 3.13.3
