apiVersion: v1
kind: Secret
metadata:
    name: endurain-db-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:60sed+qjlrs=,iv:WIYjsmtN+VUX3ff+qOy1REW72E9y2ogx9KMnQPKabEs=,tag:Lw9xFcxbXnYIC9VbbBq4zQ==,type:str]
    password: ENC[AES256_GCM,data:oR/J8ld+Yy/Bz7g8Ycd9vLY/bVMmKdgSUBfA63qvEPaQcI4/zC1UWyuOnVNABk54XndJz+IQ/uGu7XO/UmlcIg==,iv:sD0F3l8GwCSvv0fgpLdGAdkY6T606lTXQ/TD2+rgXKY=,tag:GpcNd5j1wKYBD2aeGis8dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T18:36:14Z"
    mac: ENC[AES256_GCM,data:syZr06ekNX9tOkTh+kaKtHQC+5UsJhWXgtXAySCBa/WLl0mqfSJxnQxUfc+4/4z9VoJRFO2AmCLTut6Laj/6uMzPDR0eqGE4Yoz8AJhHu4tG8uur04+/RjAVqlc7PHBvW9ChztfEO5MJWCtGEY+qJglQ+RDtzXCr5niYFV03dzM=,iv:Z+dLIJHoEh1zM4TWNXTElDCTxMHloXWyZLJiNG+Trds=,tag:8hbAU+0jLQIW9FldBcFHaw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: endurain-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:E5BOe9AWELuXM00KN2tMn4WMxz1GnA9VbXHFgAAUrQeTghi7338lWNSii5hsAsx3RiBX20TPeQJzVzKjLgZXiw==,iv:YaAD0MXAd9nAWS4fwCC+dxK8H2GDEHwNAQg2c4WCVB4=,tag:pN44TuRvVBH2IqQtTSqGFQ==,type:str]
    FERNET_KEY: ENC[AES256_GCM,data:RVQYeEJUAfZwBUaC9Cmv4EGRUieiaxbwn0PiKXco3OBtUv1pCk4b9k3kxVsTHy67Ny0v97L9Inf22Myn2tANAQ==,iv:XTPM0nNKYj6pUPEz5xXLVhAUv0to34Wh/43NEDAh7CY=,tag:99HR2xhc3atskNI78NIxNw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:tbqpT5gJAGKnLOlvD8K1nRtwy7tE5pnrB0t9XSayPytDohXXcpTPrSGmPkdJqE+7rYNgslNbGdHzZp+6dLhJ7g==,iv:dmDwGh1bbsSFd5xCHefyyLrGoFWYao/VzJHmsjPamNY=,tag:mi3Vtzgm04hFVThkbHtVCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T18:36:14Z"
    mac: ENC[AES256_GCM,data:syZr06ekNX9tOkTh+kaKtHQC+5UsJhWXgtXAySCBa/WLl0mqfSJxnQxUfc+4/4z9VoJRFO2AmCLTut6Laj/6uMzPDR0eqGE4Yoz8AJhHu4tG8uur04+/RjAVqlc7PHBvW9ChztfEO5MJWCtGEY+qJglQ+RDtzXCr5niYFV03dzM=,iv:Z+dLIJHoEh1zM4TWNXTElDCTxMHloXWyZLJiNG+Trds=,tag:8hbAU+0jLQIW9FldBcFHaw==,type:str]
    version: 3.13.3
