apiVersion: v1
kind: Secret
metadata:
    name: endurain-db-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:60sed+qjlrs=,iv:WIYjsmtN+VUX3ff+qOy1REW72E9y2ogx9KMnQPKabEs=,tag:Lw9xFcxbXnYIC9VbbBq4zQ==,type:str]
    password: ENC[AES256_GCM,data:oR/J8ld+Yy/Bz7g8Ycd9vLY/bVMmKdgSUBfA63qvEPaQcI4/zC1UWyuOnVNABk54XndJz+IQ/uGu7XO/UmlcIg==,iv:sD0F3l8GwCSvv0fgpLdGAdkY6T606lTXQ/TD2+rgXKY=,tag:GpcNd5j1wKYBD2aeGis8dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T18:48:42Z"
    mac: ENC[AES256_GCM,data:P+bRKA9BhUvtLk/Ct8i+HmJP/yKp+/YUVIy4yqoS1h2/m9Nhz7N8EJ5MN8/0QRhOCaKX1IVUNrzpYxI3RPuukD5Q2i7fikYViABpnKtAnG1/puukioI474IDR0NpWeRccIBede6NN0FF9FRFOdMcdXHm4I8/ANdXjUXwcn6Gdq8=,iv:cxM+JQr94X4nKM1mnVzT1uYJE+2x6nQ301OsJo+we8Y=,tag:VmVGC5QyOJOK7VI7udROJg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: endurain-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:E5BOe9AWELuXM00KN2tMn4WMxz1GnA9VbXHFgAAUrQeTghi7338lWNSii5hsAsx3RiBX20TPeQJzVzKjLgZXiw==,iv:YaAD0MXAd9nAWS4fwCC+dxK8H2GDEHwNAQg2c4WCVB4=,tag:pN44TuRvVBH2IqQtTSqGFQ==,type:str]
    FERNET_KEY: ENC[AES256_GCM,data:d5b/eL5WUTqqvN3IJLwQGlpUbhtZtdLpTx51cttRMfuV6uG6+w0pL8nsnBM=,iv:fen+I5R/OJC1w7lJt1pWfZztlFDfUiwWwhrpUFBt7Rk=,tag:GvHBMGmI0UtZ7+tE2QiIdw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:+RlM6h4EO4tSZWxleBcSdadGPVMUA6oSxSkexGWXbPOEZe+OVjTvCCJNdYU6SJm6bqxYtDamj0ZQcN+CQqUdCA==,iv:5g+6z+mGasUjSMPnXHCfjRjAcPuV5ms8LVk1Y4LOZQA=,tag:dG28ylEK6+UnFt96fxjwIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T18:48:42Z"
    mac: ENC[AES256_GCM,data:P+bRKA9BhUvtLk/Ct8i+HmJP/yKp+/YUVIy4yqoS1h2/m9Nhz7N8EJ5MN8/0QRhOCaKX1IVUNrzpYxI3RPuukD5Q2i7fikYViABpnKtAnG1/puukioI474IDR0NpWeRccIBede6NN0FF9FRFOdMcdXHm4I8/ANdXjUXwcn6Gdq8=,iv:cxM+JQr94X4nKM1mnVzT1uYJE+2x6nQ301OsJo+we8Y=,tag:VmVGC5QyOJOK7VI7udROJg==,type:str]
    version: 3.13.3
