---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus

spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: gatus

  values:
    controllers:
      gatus:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.33.1
            env:
              TZ: ${TZ}
              GATUS_DELAY_START_SECONDS: 5
              CUSTOM_WEB_PORT: &port 8080
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 30
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
                memory: 105Mi
              limits:
                memory: 105Mi

    service:
      app:
        controller: gatus
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["status.${INTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        type: secret
        name: gatus-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      data:
        type: persistentVolumeClaim
        existingClaim: gatus-pvc
