---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss

spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: freshrss

  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostUsers: false

        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.28.0
            env:
              TZ: ${TZ}
              CRON_MIN: "*"
              DOMAIN: rss.offene.cloud
              LISTEN: &port 8080
              OIDC_ENABLED: 1
              OIDC_SCOPES: openid email profile
              OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host X-Forwarded-Port
              OIDC_REMOTE_USER_CLAIM: preferred_username
            envFrom:
              - secretRef:
                  name: freshrss-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

    service:
      app:
        ports:
          http:
            port: *port

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
        hosts:
          - host: "rss.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "rss.offene.cloud"
            secretName: freshrss-tls

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: freshrss
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
