---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  # NOTE: This might need to be set if you have more than one active NIC on your nodes
  interfaces:
    - ^enp[0-9]+s[0-9]+$
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux

---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: "${ENVOY_INTERNAL_IPv4}/32"
    - cidr: "${ENVOY_INTERNAL_IPv6}/128"
    - cidr: "${ENVOY_VPN_IPv4}/32"
    - cidr: "${ENVOY_VPN_IPv6}/128"
