---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  # NOTE: This might need to be set if you have more than one active NIC on your nodes
  # interfaces:
  #  - ^enp[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux

---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: "${ENVOY_INTERNAL_IP}/32"
    - cidr: "${ENVOY_VPN_IP}/32"
