---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  connection:
    bufferLimit: 8Mi
    maxAcceptPerSocketEvent: 0
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      idleTimeout: 60s
  tls:
    minVersion: "1.2"
    maxVersion: "1.3"
    ecdhCurves:
      - X25519MLKEM768
      - X25519
      - P-256
    alpnProtocols:
      - h2
      - http/1.1
