---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./backendtrafficpolicy.yaml
  - ./certificates.yaml
  - ./clienttrafficpolicy.yaml
  - ./envoyproxy.yaml
  - ./gatewayclass.yaml
  - ./grafanadashboard.yaml
  - ./https-redirect.yaml
  - ./observability.yaml
