apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:8A4xc9YamYegcA==,iv:MUvSMJs1bhWWXEp66YRDTlBm2DH9Ug0TcLCoaOHB1+I=,tag:6MCYqD2/W3/Fd31EpOEXZg==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:oH9KqAc7o9jLzk0gqfo=,iv:NCU4wXUJ16tl0tAr5sWCMeryo8nZlxrSrktdXrrKpNU=,tag:Z2Q+41QmKxI507/5g2pvQQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:T2BLSTob2AbMgr48wo5hpmkpqFM=,iv:jW5tanN0neZ51RG7zQtzMyTaTcSK9/9korvdUeW3ba4=,tag:8ysPHF7XXZ8bWU2UQ58a1Q==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:LnAkvhHnU9JmMAfhbYISs9129u4mQx87w0G5HGsvrjJEKqYm0TcTA3jqy62dqfcB9YBfqzdSjvlh7MPk5Owavw==,iv:1CaUkWhFktX2VLX7v6H4KCZs4Td95kioxNc1JNzHsz4=,tag:hfACviGd3J84D0PRhSQbyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRndnluaHRX
            RUhrUnFjOFAzS200dFVqa2NVNy9YY0tKR2Q3VDA5T3JaQjJYQkU2ajhvdWpMUlh6
            WDc3dFppRlBUcm8xVlpSdDdXTC9rQUdGdEE4Ull0K0h4YS9YVDVMeDZYV0d0S2U1
            RDhFWWZVM1kwK2FzWERGNVZ4eFRONEEyUk5NWUZOc3NYUk9USnJpUjE2alh2MUtR
            dGdZdVk4aENpbHNYSXM5RE5BckluYkt1bGZLZjdsWUYycVAzWXRJU1o1d0JDVW14
            MUxDNGFoeGF6UnYyWnYwVktDT3BNcThFMGpqdTQ3ano0K1Zrc0QzemhWMXdFWDF3
            YURUaVNpQUU4bXRsUmgzRWh3VW9EUW5QQjFKL05xRnVRdC9NNW9rMEhpbFdiZ0xB
            T1RTVWtqZkdDWDhobit0YmgyR05vejE3NzNSTWZWQlYvZzJsaStxZ2w2eHd4cnUr
            SjBaZWo4WEV6T255ZE9VQzdUSHQ1bkhRclFOYnVneDNsTTBBRmo0SHNQMzJhKzdm
            VEgwbGpBTG1FVThxdis0dUNUWXV2ODJBSHk2OFh2aEZWMDQ0d2tkaFpUeXNsRVFU
            aDh2Z21yVVJ6QTR6V1dBUUNHNnJMVy9ZWUlVNnRrV2FIYVVKdTFRWlZFYWUrK2Fv
            anFXOVNXejNtZzI4QVRIcDdjUy91UXBad1FCTndVaHJ0b0ZmaHZsbXBEYTEraUhu
            aGN1NU9oaVN3VkdQNFN6L1MydTRLcm9TSHJkZ0lKWXg5dVhKZE1sVkRveE83alFU
            T0tqVFBkQW05TytPUEhReVphUGZDVXdwcHIyYXRvRVgyYTg4ZFZFUVY1V0pSMDNH
            cDhpU1F5Ty9lcllqcXZTNCtGMmZjemZPSmlya3J2cWhVZXFNL29pRWRyNVFkbWhE
            UFlYd2tmNjhqV3Q0L2s4LzJ1dmJoV0R4b2NWZm9FMXl2aThTRHR6clZxdFd0Sm11
            eDZONUNSS3oySHBlWmNiTElMbkx1SEl6RVIxV0dFTFpuREZ3RlZsWVludFVDenV5
            VHpwMWwrQWxVN0xhZnhURlFrT3NMeEVYNk93TlZ3bGZpYnN0eHl1bVhSSVo1Q1li
            MDFLaU1QL0pobXFkd1hVTm5uVnpyQzlUUjNOTUM5ZjFCbnJZRmd5Z1Azc3FGbmk3
            dmgxRUF0S2dEWWl0cmtwMVlxTmVYTDUyYnhwclJ0MGFVdjl1VUpEcmNMUXhjSndE
            NHl0Ty9vQzJON0hMc3lsOFhkNjVwRXIvKzE3b2NiYVVHS0tBSTQwTHA1Ukg1T2Ri
            aDA5V0Y5TXB1U2NVVEJzUW8vOWEzdERldzlabXUzVVUwaGVWRjFoeEc3c2hYcXZY
            YUJsNXB4b3h0VGVhVXpxTk45V2pZZlFHb0k0Y3VMU0pFcGZPMklGek5OZnRQdHZz
            ZEkzdXVKQ2UvdEV2L2thbWlQdW9ZRTVsbHA0bWZidGdGVkJNcmpBZHNmUXpLNXQr
            TE4rNGNDaU9Rd2ZFVmtFUEFzM3daTnEzYzJWekhWbGZ6S1FDZ1JlQldTUmV4Q29j
            R1l1UFlEMU13bWRkRG13b3dXNE5UbExaVTRqSzFFakQxQlBWMmRZN3Y1SG1QVXI2
            aTdKZEdKNlhyKzJSQ0xENzdielBYaGYvMTcySiswQmRIQldnODBXc1VKbTM0OU9F
            c2dPeVVPekNwS3BlcFpWQ2E1dGpFQVNRZGVERXkvNzRnUm9DK2N1ZlhRSHp3Ujkv
            Mk9XelNXTkJKdEl4L25tbjd6RzYzQW1QdytvQlIvOW1NK2dpMlN4Rmtia1p6N091
            RWRiQURIdERIazR2cUZpTVhLZHJsRGZLSVo1Mnh3QWM4Ukl1QnQ4cDdZOUhrOCtP
            Z2ExeTRBU3R3a2hnYlFDbWhwZ1Y4WmxCdHF2QXBnS1lkSUc3MlNzKzFRa2tFcUVM
            Y0tqZlhJc24xTHY1OTNNNC9OTVpnbm1UTnJiNXFYN2FGZzVHVURGeU0yY25IZwpH
            T3cvaWU3Y3laV2d5QUUxTUQxV2ZZb253aldTZW1SOHVpMzc5cVRSMm9JCi0tLSBV
            dmhZNWt3K0EzRjVzTUJ6VzB2UmVLM2JDVmRkUmFaYTRWODBCK2JzcGlRCqbs85VI
            ozq763eUzB1wiH8UYnDqnSyqadpROVykmNMR+CQ1+TLNd/3kxYGdfiZYzw2mpeCP
            coJ93ZQlGActItk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-21T13:39:52Z"
    mac: ENC[AES256_GCM,data:/Rn4QUtDc/rvwAJQwHoaiP98+5JbMxBe2OXq58Ce/MVq+ndLumIU88l7VrpLQbCBIHLMhP5rm7ZPAuJR8pW40t3b7PBkT6kZU6XeLWkN2ozXdwWR/9kgMGbWOudstAUY6HoPkhMgXPDIUpdyyoBqEIA995jK5ZZFSW77xA42HPg=,iv:wFzuFHGobIiopThd6mjUXSisb8scdNKzTi6iqKNyzqw=,tag:bY0Ig1pwJd6o2M4CrPlkLA==,type:str]
    version: 3.11.0
