---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
spec:
  components:
    - ../../../../components/kopiur/backup
  interval: 1h
  path: ./kubernetes/home/apps/selfhosted/vaultwarden/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: vaultwarden
      KOPIUR_CAPACITY: 10Gi
      KOPIUR_PUID: "2000"
      KOPIUR_PGID: "2000"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
