---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  chartRef:
    kind: OCIRepository
    name: snapshot-controller
  interval: 1h
  values:
    controller:
      replicaCount: 1
      serviceMonitor:
        create: true
    webhook:
      enabled: false
