apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drawio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: drawio

  values:
    controllers:
      drawio:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/jgraph/drawio
              tag: 29.6.1
            env:
              DRAWIO_SERVER_URL: https://draw.${EXTERNAL_DOMAIN}/
              DRAWIO_CSP_HEADER: "default-src 'self'; script-src 'self' https://code.jquery.com 'unsafe-inline'; connect-src 'self' http://MY_SERVER_URL; img-src * data:; media-src * data:; font-src * about:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; frame-src 'self' https://files.${EXTERNAL_DOMAIN};"
              #EXPORT_URL: http://drawio-exporter.selfhosted.svc.cluster.local:8000/

          #exporter:
          #  image:
          #    repository: docker.io/jgraph/export-server
          #    tag: latest@sha256:9667a71912e5605197aff73b645116649dcbf25f87b5398364037ef412831005

    service:
      app:
        controller: drawio
        ports:
          http:
            port: &port 8080
      #exporter:
      #  controller: drawio
      #  ports:
      #    http:
      #      port: 8000

    route:
      app:
        hostnames: ["draw.${EXTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
