---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: home-assistant

  values:
    controllers:
      home-assistant:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${VOLSYNC_UID}
            runAsGroup: ${VOLSYNC_GID}
            fsGroup: ${VOLSYNC_GID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.12.1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 2Gi

    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 8123
        primary: true
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${HASS_IPv4}

    route:
      app:
        hostnames: ["home.${INTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
                subPath: config
      hass-cache:
        existingClaim: hass-cache
        advancedMounts:
          home-assistant:
            app:
              - path: /config/.venv
                subPath: hass-venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp
