apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: cdn
spec:
  clusterRef:
    name: garage
  globalAlias: cdn.${EXTERNAL_DOMAIN}
  quotas:
    maxSize: 1Gi
  website:
    enabled: true
    indexDocument: index.html
    errorDocument: error.html
