---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagecluster_v1beta2.json
apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: garage-cluster
spec:
  image: dxflrs/garage:v2.4.1
  zone: hcloud

  admin:
    adminTokenSecretRef:
      name: garage-operator-secret
      key: admin-token

  database:
    engine: lmdb

  network:
    rpcSecretRef:
      name: garage-operator-secret
      key: rpc-secret

  replication:
    factor: 1
    consistencyMode: consistent

  s3Api:
    region: hcloud
    rootDomain: .s3.${EXTERNAL_DOMAIN}

  storage:
    env:
      - name: GARAGE_ALLOW_WORLD_READABLE_SECRETS
        value: "true"
    replicas: 1
    metadata:
      storageClassName: openebs-hostpath
      size: 1Gi
    data:
      storageClassName: openebs-hostpath
      size: 10Gi
    pvcRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
