---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: cdn-key
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef:
        name: cdn
      read: true
      write: true
