apiVersion: v1
kind: Secret
metadata:
    name: garage-operator-secret
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:P5SccPxIYAYKz1WYw3O3Lv5Mnv/0bOlSTD4iea7KbcyKXPal6zi+gmoIRxgbeU6jFSW24HxUK8f+9R6isFuIaQ==,iv:s+MR+XtvT4LLrwuQTEMM9AxLxXp+PE7rFoF0tTo2oaE=,tag:UU28+2d117ygdnGh6OHIww==,type:str]
    metrik-token: ENC[AES256_GCM,data:qtl+U5P+/v4S7T5Tlj+5cFjhnqNNK9C39U7t7sCfSq0G2sZ1otxs3XnY+YpjiwDABuaW0W9VVDmouRHGThlBkw==,iv:e66RQ2aJC/Rwp9wrltOLCrUxnTcZtAkQpuSBJd7g8uQ=,tag:0JajA6HbfbXfMjU1z1U5FA==,type:str]
    rpc-secret: ENC[AES256_GCM,data:pbqa7eKJmAqXdBJEXQB6esN0eT51BLCTs+3vz4fDoI1xq0PkXmY6tWdB59aVLZ8WlbLC0kWuSXN47sTaHHkdLw==,iv:hI3yZkX5Sqt07njbXz39P+33gZQMJtoFY9VU3yA0L3k=,tag:Kz6XSJDwJUVEmr/eqVytwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFhOSWdJdUV4WkkyMysx
            VHNGdlM5N1BtRVBOVWFWajkzcUwwaXM0UHlvCm5pQWVQVWNzcDkxNmJlYWJJTFMz
            cWJkOGRwaWNjWm10RmVtTjIzakZZdEkKLS0tIGFybjNvVWR4K2dsZmgxQ1RWZEsr
            ZkdOSXYzSEpzQ0kwTUh0YWhxZmU4RWcKyKWU6QwCIyQ7NW7ii3/3jh37ateF5EF7
            zJDpPfmhqOSWWjKhlAR/swtSoDIUfb0yC6+2LDMZWvGDrZybCTrBIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:54:07Z"
    mac: ENC[AES256_GCM,data:MWgFiUievSFdXwZQyJAazNVQsHMFBKqnWa9GoRkpY/trDVIhAm9qzNwLZ6CJXaArxbwjte4d5fiVfsecA5induFw9aA5XvxUrcx9Evfx6NEn0AFjzne1udKF+r4Fms6ZWVw245JwiWkjaBLZ/Aw5m/743mCcifE4gf1z6UEJ1tI=,iv:c/4svamAOl8wkKynlFGu6tHu42KbXJ1Z1JTn7LUdcxE=,tag:/ZXoqxSxlQpEckngiAMMTg==,type:str]
    version: 3.13.3
