kind: Secret
metadata:
    name: garage-operator-secret
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:amqRqZT+0bS7VjxoFnTkzASUBSn02Xpn558ZI4tWF16IwWowcSQsQ6+hLYI6kXWOy+UpazbobOlwugeZ2NexwA==,iv:RgLgTfjWCgsbaVbO4M4QAV1BAO0Edy+etGlgzzEP/QA=,tag:iXhg34GSiVhKGo6e0nOWpg==,type:str]
    metrik-token: ENC[AES256_GCM,data:uxR+qcVqVViKiblgs3tkgPsmddE1KGWx+iUdfMQEE6bfrokMDh+7ZbSaFEjZjoIBQGBpbvFWgDHJjcYVlS4KbA==,iv:mPbegDVQiukPVTaTCmco5MKK67/Fq/RGvSI+cLxFxjc=,tag:Ily+9BirZWaKN4E+6t8rUw==,type:str]
    rpc-secret: ENC[AES256_GCM,data:V78ralSPFiOgfvBm4XCk03fRH6p3WYZGPJfxUuXcaxAHmjedN7bZJ/1YJZm178nw8vJknJ3MUGIlhbfKtTkJYg==,iv:0sKQvAxRCsk8lSnRThzUAD4pMx9vpatkuqeGqsninj0=,tag:yekx0Rx29WjIONDK5yn7NA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:45:21Z"
    mac: ENC[AES256_GCM,data:ye7YYccwHS3l8k1XYbLCwtnGlCsydKiNm9s8wAzflhTcjqfkabdrVORQE7vcVLxPMlGR1L5j0jeYABaDp6gscFOjqkvv+huWufLd7qVlsi2fOCdUUIwlunwsvOAlA0SNvm5q7C2K8T09YdSKbn/5vDYEl9fk+1nZRmCvZB48Lls=,iv:A7vtSKRyxI2yl51FJnFGAU5nR9PKDmrOwpyP1cY5u48=,tag:SU13xuWObOFSXSKxyQCakw==,type:str]
    version: 3.13.3
