apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:DdLMVFy0yZNgu4PPpswnNRt+j8nVnU0eo+XsTDXS6brmjdcYx38ztStapzlq3j3LINAuFKLUexqoUwcYc3hQeQ==,iv:Q6a+xbG+tyAirY+wF74r6ae4OKY+CLCkMrl5dnjsm4E=,tag:myjFQfjjbiFq/YoaNpdzMg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:rUCp60KDcUs=,iv:E7TK6XUu8D2VuQay0s/iDX5FZ0tinlLdfuvP5IzpLUU=,tag:rhSMm/0bsmboscHYW6bAZg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lxwjPUMDxPD0IJIUrvH0mm8ZK6uR9AryyNSS67EbUbx4QiIQX3MfbYjA4JfYbZDuFmtRe1vLtVg33LJ3El4gLA==,iv:Feuafcuf/c0JYRTEHKwzCr4cTJYh9HZxZwlwvKZWX/c=,tag:AyZHlQFCLgLizazvlqMEYw==,type:str]
    PAPERLESS_APPS: ENC[AES256_GCM,data:kB1CQmvLQi09TebT+OEsxmT3u64b34bbhwQpk2V8cxn4E35YIasQr+l+uBJ6cw==,iv:zfQ2ROL8RfgSB5FisRvKnW6JGBVSDK50za/ScqUxpK8=,tag:zkm+7VMjvtX4ze68y0Xmlw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:cFoVQ24vlw0HeZw0gPVGJ4H+X73j+Uhbg0aBfgjwt4+I8X445aNpgQOysiNW9dTZccgu3iBB5QZUkwWG4uwDeAR3rqxJmXFqSDpXvXu6wbTzoLhabTVahhOVrwzupQ7GlkFfyPePb4+nL2JFwm7HScMP3S77x+nqyNFVeih1syV0bkNWutqSqa4zulNlCIBufhpXufPqh5ubk8c7Xr9hCyFqfnDDbIgJz1y27fAHux9uUrS5mpAv1J+p+Ve+cYpFbahiOwkgiRnRauILMNZ1hJicOKq2SsAquxbgBMl1ZmXDWM1Tr6QBxGUyDJi6zaaSppmhHdJfsAJVDd8eJd0MrxtjIZUtvSQr6/VBD2SeQHzUP8AEFuicJa2Ajx0QjQ==,iv:3tkaP4C5nTvx2LeeY76yyp+5gBxy3lL/+mFrdffHiIo=,tag:JZ1BLkpHWX/cEYAiZxdHWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFkekNIQStX
            ckMyNjdPa0lkdXFoUTF6R3RwZzBWYjlWR1JONUFJQWtEUkl0dGhNV1hEUk1kdGla
            cVlOd1M5MEJQMnhhdkMvNnlWOWp1cHVMNDZ5SDN1V1FFSWVSR3IxcWhoZm41Mjhi
            Z3ppbWwwSnlNVFlrNktvWkZNRENBRXRHZXpiZjA3UVhVT1I2bmJ6d1RSK1BGYXdG
            eWhudys5T25kOHYvVXJnMEhJLzN4MVNrNzdERHo2MEtlVW85UWpPeEE4eTNUb01a
            cEI2RUs0TXo4SHp2bmVRbVVBcWJzekhBbTU4TjJSWEhXZmxzY2xGbGlOQVEwQzdU
            ZHFxdTFsS1F0andzUU1ZVUt0cVNTL1p5QlNIYjFyb2VuSVVXaGhQUWxXNGxIenhR
            NlhwK3MzYzBlRmFJS1h4V0piaDU0eGNJUjVPSld6WW40WlkzS2hMZ1ZsbzR2L3h0
            bGR5dXVpSHMwckk2dTFYT01WL211ZUJLRm5TTE14dXhVRGxNQ3dobFc5bUI2TjNw
            RllrMlJkRFlMZUdSUUxxWlAzSUZqUHg2Y3preTIzb0hkT3RvbkRDYlRrUSthdWJV
            OWJXSE80VHFNaXhERkpCSndNdGNxVmZlbGJDUWFiZ0hFRXpuaE9HNGpaUnhLdnhv
            eTBqbnFXQVhCVVVDaHJmWXE3eUJMUExxU05oNGZLbzl2aFNjc3YycFh6cnBKVk1F
            blJrZ3ltUHd1Z0R4Z3RDWlVwQmhqam5RblZjQ0tXdGZVUTNHb3hQajFvZW4xeWxl
            Y2dIcytBNGltTVRoTWFHbGJ4dEo5dXhmRmhQN3JZYk5RaFhHYkRZMm5tZEV6NmdR
            SE5ReURYNGxWMkpLc2tSODhpcVZzWVlmOU8yanZuUWFQZXI0MnFJZGM0bE5XUDNS
            Q1Rra09FZTVMV0l2VVRkdFdnTlp5ZkFsdlpJR3BMRE1NVnErdkxRSVVUUE1ENGI3
            NUxPKzlKTEQwMUd6K1RUNUtHVXZqMlhiTEg5SEVMUnRPdnRLVnNqVDI2TFNjdE52
            TmptRjN3SURSZk41ZFJOR2NYWnNsRk5tb3UvTi9xejF4Q0xON0o0RFBOUTA3Yy9Z
            enFVcFpqMXdsU0FFc0tqRlZvcDRBMnErRVR5NG00dDE0dm55aUtQWmt6K01wdUQv
            anpGUFBUemN2SW1HbHhNT3U5dnp0eWVCdEg0Y2VMY1hmMWFpdGdBMjR6TEJVbWxq
            amRCa01VSGxvcWNOZllCWm9WS2lMc0J0ZUsxWEp1SkpDUk1Dait5YjJFNmgwRkVL
            L3VERVZTV2JIZzdRbGs4bklrMjRiTWRvY2VZUnkxaTFJYW4yRFl0MDJDSTlmbm9S
            cHpxSjcvN2UyVTBpYi9Nd3FKSy9FbkJMQUhWU21xMzc0TzhFUzAvT3duODRxMlh1
            RUxITHUyM0FSMzU5S3BKMGt2cWlFUExKWitsY0xJYmg2QzEyNzZwZkZUOXlGdlRx
            K0I3dnFxN3lGSmNKVURyS3lua3YvTUlUamhoM3ZSV2Y4S2VHQkNDNG1WV3l0ejBq
            SWRmazliZ0xxS2lDc0tnTk5QM09kOXR5UFoyV2ZuajJyUUsrZWg0NHkyTHZOTmhZ
            bG1YakVBaXZzMmI0aFJ5QjNDRWRQVmFLNG1wT0h5eGVVaHhod2c0aVpOOEFCN01P
            K0hCVkpCOFlWZjVrME8rYzVmNmpQQ0RGRVU4by9ydnUxVmY4dEhOQnIvRVAxQTNr
            L1IwUENHSnJ2U2psVjgrck95NTVTQlJ4YVpITHVwNnYzZ3lFVTM2YjRaU01wTjJL
            UDNCZWY1RUR0OW83YkJ4OGZiaU96NEVMcU4zRXMrcjNqaTc4bDlsQUdmZzRDYnlr
            QVRldUZCR3dRaU9XMnd1MysxYkFaS05lRk16S2dmM2FQMEljQzNkQUR4UHFMU0FX
            Rk9vMmVRSk5TN2kvMDVwTW9nbGpNZEtIUGxncTlEbnNLTUNGU2VERVM4RFdTQQp5
            djJFallxMk80SXBrVmYzbmE5UVQ0K1VuVlVzRHN2RmNXQnBNb01aWk9BCi0tLSBB
            UGlmZTM5aG54THVGWjZDRHRsNS9nSUpDNGRjcURhZUQ3TSt1aUZ2SC9jClLN1nSl
            xzpZGTSphZzyqkh2zJ/Q4ty4jRtbKyo/OnY5t5RGDFT1/gsiu7SluQ+ANlIZOJHU
            7ZL9Fz/CDuKEoAI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T14:20:36Z"
    mac: ENC[AES256_GCM,data:K5kgOkcaBJyUfpirX7F6Z0LApaiRgQOamWHXN8fZPQa3fkTWE0qowSVF4iRCo5fSDXjEuczXi46uiuXBZsgfGhsQA3eqvSz5f5KbxrkOx9fz7t8sZshj3lR3i4v/ZSdiBJh/z/FpOfKrNjp5qWP+abHpQQVTMWdXzUWI9wJBOk4=,iv:cmD0oeeZl0noQGqaGsy5iwRCXdnYbgkZtguIqRS6rgY=,tag:628FI9usOq2bbnYHIzbUdg==,type:str]
    version: 3.11.0
