apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
stringData:
    TS_ROUTES: ENC[AES256_GCM,data:dcWw8Y+m9JaOeWyrlg==,iv:mBQ6Y3mZmZd0ykztolU2BbTCYneIt3tOozDpl0cUHEI=,tag:B7wNYWhitx0CYfWi87bR6A==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T15:30:49Z"
    mac: ENC[AES256_GCM,data:lRszsw3KYwvQ9s0HAfvz7gsWoajskaELm8O9Mb5wlox91mEkkHx/2dwtL9Go3ZTwBKm0GbwJH5dbL3hCq0nSD9FNm3OLPqxDY7aboVk17hABBayoM2Cut6fkhvSxNrJqv5bNDr47ZocZrNKTj7w7wnf+cJ3g0CV5dxHGbDuYbJY=,iv:3tjcssu2W3+eOKR6SbmPqozlutb8y5GdGbml3h6RNMc=,tag:99QRqbu1IzIln+/tB2OJow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
