---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://nextcloud.github.io/helm
