apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:cGNuDims/Ds=,iv:L0BUk1vAVeauT6JcamRv8vDLYYIAR9awRnGYWTh801U=,tag:ka5b+t9A95d7ou1u46IBJQ==,type:comment]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:k13hyPT294wdHLOc,iv:hvLe+3i4So5h/ndTT0wfN33owQRYvUARpt0JfVQ75ZI=,tag:xzlqKJNJ75hB25aKElrwtg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:RO35j1ZghRpFfOKi+97zFqjVWA==,iv:gm6UaLve7RVI5piL2OkGW+PInBjuEFjRslJO+MK5xCs=,tag:1YCbHnsEE7o8UYD0aJflGw==,type:str]
    #ENC[AES256_GCM,data:Hm6IrizTHNmbflZqKg==,iv:P/jgbnF9pUZ3NkULqeNUbzWcs5kRTnnNq0FC112nBYQ=,tag:4mPDdAjUIfyYNNKKxiprHQ==,type:comment]
    PRIVATE_NETWORK: ENC[AES256_GCM,data:kVoqHBj60xEHTQ==,iv:audczJAZA2RxW/7t3uMLGRm9Cw3SL4uFvOR1yaKSryw=,tag:PFoLxlATe2mdtC3B+PnmGg==,type:str]
    PRIVATE_DNS_IPv4: ENC[AES256_GCM,data:Bzc+uzNmvV+Y1w==,iv:nszQ6hJDbS5QqalNjZyl/yioIe6kXidLKuuE9LZ7RVI=,tag:96N8+shiN278wvpfsw0ohg==,type:str]
    PRIVATE_DNS_IPv6: ENC[AES256_GCM,data:mKUAtaIowVc/hjG7gTS6xZw=,iv:PSeWNyjs/HFlqjDdCe2/0q2UUdWC6Td9uogceq7tkTk=,tag:S0FuCzySPq0Zmq3sepUc4g==,type:str]
    ENVOY_INTERNAL_IPv4: ENC[AES256_GCM,data:9U0HQJS5Tc9JlQ==,iv:oCisQRE5APWFyG9o3k8UGX58idxczxq2qQ0xpShFew0=,tag:4NyKxSHW21YdEUgTNGvTFQ==,type:str]
    ENVOY_INTERNAL_IPv6: ENC[AES256_GCM,data:qwidv52Arsurg+FvRbn+nrQ=,iv:7PtHVs5fOwBZ14B3QUeQRzJA/dzKBDu47hbqNMcqDYw=,tag:G9g4kLw00OUbj6QgJXeCjA==,type:str]
    ENVOY_VPN_IPv4: ENC[AES256_GCM,data:aWjbqhh9w+l9Zw==,iv:XaHoegkx9A9tlHkw8i57P0oa7ZJbL4PWWOUQx2f/rC4=,tag:227yPGR+laTllY7bqwia5Q==,type:str]
    ENVOY_VPN_IPv6: ENC[AES256_GCM,data:FAkygY6FXPhHujCDUg3K0bs=,iv:wvGBONZz+kJJGDNsa8kh5ayb4cLVoRr6yjiOowDtPfM=,tag:nzTnJ8ZBxNbQq8VUPNstwg==,type:str]
    #ENC[AES256_GCM,data:AEARQYrN5AKwmaSBow==,iv:U/tyEUA4Iv5o4o86uDkxshTIkmDHAA5YLuih8n1Bh18=,tag:PDyteHuJ+oMt3BmQzbEgGA==,type:comment]
    STORAGE_IP: ENC[AES256_GCM,data:poz0a7nGBFq5orY=,iv:GbLN97L8rcx8l+9caYwp14N8JZrzqNQTwFLOlbz66nI=,tag:oJBhXL0wQvclZCuHP2FkPQ==,type:str]
    #ENC[AES256_GCM,data:qS+SMfuD3lGxyIN2e4M=,iv:x3kknajZnZDvDW0EXxJwN8OWoJUVVy9VoH9f/G08bgU=,tag:qaMqcVQ4tnCiH9NzTJSvSQ==,type:comment]
    #ENC[AES256_GCM,data:DvUL7fY/fYvElA5psNCOpG233Rz5Nyi0fOtAMuU8+/7P638Cuq1VzRjIuzKt,iv:xwUJmyuDjmHVtFin6jNkvE1XJuzKN1eIEiIP1+dNRzQ=,tag:F/7GZ0PwOuaYITLjfev4Ug==,type:comment]
    SLZB_MR4U_IPv4: ENC[AES256_GCM,data:xfSUCp7/RFpY/9g=,iv:nTBAowlKnO72J8pYs4+0O+c3yybrl68dFE2bfCgM0m0=,tag:AXS2AuLuGdJMr+2HOhDb9Q==,type:str]
    #ENC[AES256_GCM,data:FGT4jeC+KTF9Ds9iBAE=,iv:qBnL+fXFPUE26OlfQapaVXpInUiqPZswinfT4ogNrS4=,tag:sPPdO1onidmNLGziaLtNRQ==,type:comment]
    MAIL_DOMAIN: ENC[AES256_GCM,data:cjGEbEQe9SJadqw=,iv:Mgu70CkwnZaHd8H2DiHOx2nvFONT/wGQJSdAqvO/5l0=,tag:tYR+vHofrz1nJTeqB9OIOQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:L8Ic72taPL7RJXfFiK4=,iv:F06O5xDQlLCmbp2J3jT+5y6PyGfwwfpVuzMZhyBO8Q0=,tag:lkQaMTPNoVdlOlwaX/VoGQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:MvD3iFI2muxmWoKoBS9F+9IiSOA=,iv:Df87DHQiehT/HLZsbBODXCndzBxW0zsIlUxuM0BmO5A=,tag:+HgfDpI5BHiUfl7SuLUBew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFQyVFBrM29r
            TEs4SjkwZXA3bzMraTV1ZUR3TWdNakRtZDJyQWROOFFkWSt0clNuMlRHR0VjL21i
            SDRkK2dWNXZDbmN0aVc0K0J4akZsOXZOUDd6SjJ1cllZSXI0ZjJaa01yR0FjVFdO
            SUljdkV2WVkrblBkMk5vZERvd1hSZ01NcVlBWFJrZ1c1MEJzUjdSOFdKaGkxakZ5
            dTdqMTFFck95cFRYTjFWSEhJWXM0YW91b1FGWDJqQTJPK2prMTJzNkJxZ3pWbkZ4
            bWhYcnFnRWlrTWlYN1N0Ymp2Y1prMFVybDNZM0VPZDhHN1lNNDNPMmtMeVhVL0Vz
            dFltSGdZMEFkcHhDaTZ2eHM0TWZvSnpYODBVMnlxK2VtZi9xbVZ6eUl4MUVUR2Fi
            TWF6WUFOZXBWa3BPRFZ2cVRGN1RpVEpodHhrOVRGM2hRTm8xN2FOMTNwMUkyWFVu
            dGF6aHpIRzA3NkRMRDliWS9hbFJZSFQ5eUVCcEhtcGx6ZUlKeGRQZm8yN2hzRzU4
            NVQzei95TUdnZ0RwNWxZeFIvTVNZTHMzVDJiaDVrOXBxUTlqZTRtS1E5MFBLMmRY
            bVAxaEt5RVZLd3VnUU00eEUweE9PdExVYUVKdFhJNWNxSHVtaktabDNNME5LdGJK
            N2dTcUJCYkNIdit4WDQrS1k4VFNlbEdReVJtcE4vY1QwRkRPaS91RnVSMWxkWjFB
            cDRZbTJsOC9pUTEyYWNGM0ZDWElKKzJSMHVvWVdTMmg2b3hBbzBUQnpGQzZwOWVn
            WVpJYUJQMkJUZDdEWnNWM0loWlliMyt4YVhlajBDNjZPWE1YTWdsSC9JcXZEcGo2
            Rm5rVlZiSUlYdXRmUlVyUnVZeEtOQ2pPZndMMFFFcjhoemdmNzNJWlpONkhnSjhz
            Y09rMTF4Y3ZTdWhjOGIxVE1xRGlKN3hDNU40VHRjVjJQQ0lwcjdhTVZ0TDhqN1VJ
            WFJ1YjlkaUNjbUp4dkE0eVhUYmxqZjBYdVZMMUFlS3htcGJlOFN2MTRndHh6cnMx
            RXJ1Rk9uL0NWSGpGd0I0WlhUZVQ1cE9LY2J6ODVmKy8xb1JLMlBlU1ZudVhnczdM
            WlJoeURxTlRESmkwV2NwRDVHWVRiWjBPN0F1V1B5ZUwwU2t0cnBhRVpOUCs0d2Fx
            YjJHNzNtNjRnSHBJQVpGdjRXbEt5dHRxR1NacDl0UGRBdjVLMDgyMzc3TkxSVEp1
            WHVYRkVXN21lNGtvYnkxZ2hhQVdDUTVTNnN1U3J5NVJhcjRPRmVFNGFVVGtnQWpm
            NXlrbTRTTW85a1ZVUUc0NUZmUTBzdkp4NnJEVWFiR21IalNWN295WXE5bnV0aTZZ
            YzgzNmVTQ2tUUzRNY2hyOFNRdUlpOVcxbjBLRlgwQk84NE1KZExuNTd6bkt1NGg2
            M3doSHNFRVgxdzE5SWJDeHZUUnpuWm5iTmFNeDBNWVBpeEZwNGlSbEZYWVdvMFph
            UVM3NHl0anliOVlIcmV0QWt3bVo3TUF4aGNsZk9yRldlVW56Q0R5NFR5cjZPRFRW
            alBSVlFseFcyc1U2bnY4YlM2cVViYlQyNlNocENZcVJtcDM4S3pNajRXMklaRGRl
            RXhnWDMva28wWXYzREx3SnBLRnhYbTErU1pFSm5HVHBlVEhSUldORkxLWjh0ZldJ
            Z2VYZjN4VHlxaGtnWURHdVdRSDFyLzlsWlZaZHRaVkpGNHZqVjBXMTBpSG52bG94
            eU8rV1RFQUkxUy9jWHhodGN3RUsrLzRUQmpSMjNuUWNZbGRaMWVOZVJRTFlFamhB
            SGNxaVAwQVZkaDl0SEtOOXJLQXpFM29lNzFNS1lNSDBUdFRFTFRrbmlvOVJYSzBT
            NDhIVy9OTkUwVTB3V2RYS3U4b21MQzRTSmc4TnhrL3pJRVhBdndWU0ZsWlQzdlJa
            dFVlMnpRVHg5dDB0Tjc0amoyd2lBTExXMHBXUHZXbmwxNENjRGYrRStHYi9Zdwpj
            eEZjOHh4WC8wUVRvRWRLbk5aVmhuRWk3UEpScEkrZHdOQlQvcnhWMzBvCi0tLSBn
            K0pWeGZBck1GY21SMzFYaXkzZG52TXNydW9PUnRLWnZINW1MRDZZUTdzCsfYY6e8
            QJVyCVDTy4gr7cjg9e0jU0bNyP0bREEmTOMDkww6fw8wV0848aSZOMx/tSMnJ4iq
            5DpcajI0gasqZgo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T21:46:03Z"
    mac: ENC[AES256_GCM,data:l7RK4ACk85VfCRcBgHIrkW+bryM4qRnr88fLB/ecDgpyrLcDgxtx6lJJWtm0NVPWVd6Tk6G1Z0F4dSeCOfUILSXQKkhDOQ3G2sYNdsLtavyUri2y7PhGLJHIkPs1H0qctadRdK0VNjx6CS5mliZ+G4yfHwgfWoXFzz8Py9bH7LQ=,iv:8q08uRJYEXGqXHEvv1G99QHGEZJzqrpdbmbZg/t/HN8=,tag:diThKBhB64rPDNouIYSbMA==,type:str]
    version: 3.13.3
