---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: "${APP}-restore"
spec:
  source:
    fromConfig:
      name: "${APP}"
      offset: 0
  policy:
    onMissingSnapshot: Continue
