---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-operator
spec:
  chartRef:
    kind: OCIRepository
    name: litellm-operator
  interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    replicaCount: 1
    controller:
      leaderElection:
        enabled: true
    webhook:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
