---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  timeout: 5m
  wait: false
  prune: true
  path: ./clusters/home/apps/kube-system/snapshot-controller/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
