apiVersion: v1
kind: Secret
metadata:
    name: renovate-oidc-secret
stringData:
    client-secret: ENC[AES256_GCM,data:KVy/WjIicophbYBDzlz+D/zzgn1sYEFvT+T+DBoL6yg=,iv:ICArewv5mqssS8s1zEnPEMCRrqAQFVy1Pv3GazmAZ7A=,tag:qGkmq0+8d8meWIz7R1JRGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDAwYVFuY21q
            QUxrRkpNdkQwc3JJVWRnZks4TE82OUVVcEEwZjcyaEdTZC9abGdkd05nbFJXdTRh
            SzE2d090aFdWUElrN2lpMThuZDkxZjRXa1NSTnBSTlFubUg0dnd3Tnl2VEJYcE9K
            cStjTkZmTUhHS0ZmN2FiYlpZa1NMVU1IUUZreG5NVDhMSlJFNXRKOEYvUkt1WXNu
            cFNXa2t2N1pmSzRqR2hyRUFpVWU0LzhTdm9aZ3R4azRqcFFNYzFnYnNkcFRjMEhT
            Z0ptZzZ3ZXhGcWwvd2NXbHc3bWFXdnZwYzJxUm9YSW5Cck5sWlRwZkc3TzBKdDlX
            aTgra1ZOQytXeEt2Z0E0akF0Y0s2aUVaZ0VsSlFWMFBscE1YK0x3L0FDa1h4SmQr
            MDgySWVQQUpYNkxDY0h4dTd2Y0RiOU1LaTVwVjIrU091SnoxOFZnUmxtc09CTnpI
            QlE0clM4MERDQlhJMXI2S01uUk0ydkRKU0ZteE1aMFU1eHBya0hYMjY2MkNWM0cx
            enNYV2J1eWIxVWk2ekJRcW9sd0dIaW9TSE9QYmovSy9RTVhXdnZGQkJaZmFVTEZI
            NitFTVpMcXRxUUhXdGZqWGI5L20rak5ENFg5SkhEY0p2N2RiTW8yeWhkd1ZVR1Vi
            RGc1NlFIQUFqT2tQSXFQYzdYa2NZdGJNMEo5S2xPYnpYckhzTUNyR2lUcWxPR0dH
            Mksxbm0wVW9WbkNNQ21KZTMzYkF2MVBoYTA5dnY3c1pwWjd3VWFwZDZFTHhja1ZN
            bndUY3RXTy9JNmJwcStTcDBaSUxlMzlLZmhvVm5FQ2wyTUJ3UksrcmRUUEZwM3NJ
            YlM0SVpsSXQwMXJLSVEwVEtoZG1tWkpiNk9kYUlncXljOWRDS1RCS1l1WTdwMEFW
            YmNvMzYwRk4xWEFVeTNZSWdXQlczSFpIeFlLVnFTdFNrOXVVZ2VDK1RyeXNRQ3I5
            TEt3UytHZU9BTGRzcmEvTVhkSDJPeXZqUHMwODVLRHlHYzFOZGwwUHJML0NtdTc3
            em1ERC9DdjF5UklNOTlBN0oyUVRCRURVWjBONWVHbDF2aXpQZ2ZFa0IrenV2KzMx
            bTA0NHllMWJyYjVCNisvL0pISHZ0UUpMc0FHaWxlNjNZbEdNYldmc1lqajUxWWVN
            MUxvSkZhK1IvcHRKblBiQis5R2xPb0c5eXJrRGxuOVlIU3pzS0hIc2t0TlZuR1FL
            NHlaL0s2MEJLMkJDNnNYQjBmTzVuNWR2aHVTbm1hS2dMdVFic1poY0MwdDB6MGo2
            VGJZaUU0QVN2WXppdG5UdGJBUkhiN3NjWTB3VC9hOVRHNXl2WnI0cG9saDBBL296
            S2FhTHlCOWl2Z1ZsWHdISExEWEF3K0Q5czZIZ3RxcmNaTlJ5ZHpmSEhLWFh6MFlB
            WG11SXIwVFN4aGRwMm1DSDRyNmYwL2RrNjQrZVkyK1g0aFpxb0FUR0labFdQMnFY
            ajBYNGpycFRCWjI1NCtJTkZPc0ZtQ3JqdmZsQ25kNmcyRjZzeFpESklNRTc2L1ow
            Y2k4OWZjUDk5RkhNaW96SHZQNDNLYXcvemsvRWdSZlFFdmxxVEpGbnJpc2Z3Q3NP
            SHdsaWRNR3grazQ2dzhMM1FlbmJ2dTltTERzUHlqODY2empUdVM1Sjh2TTlGMHhh
            VGZ6QXJuSVFibU5ucHBGai95Q3d5dkRhcFlPL2xYQUhSNTBCanAybHB5aU5aWWw3
            MEhUemR6NGVEZG8xcnlJZG1adUhOMks4QmJsYndEbGZNREJCdldsbzhRM0xNZnMv
            emhaU1d0b0xzY1A5UkY5ZTRLWUVWOTIydFdReXJZMjdnNkQxTVhYS0ZGMkxBNkw0
            S1g2V1ArbkRGSjJZSGxlUnlwa2JweldoQnFuQm4xU1dma0IxN1QrOUs3Sno0UXJB
            T0JBVCtPcHVOYWovekJxM1NTVE04Y2ZiTVFJbW9MZEVwTVNuUHN0NTdobG1hUQo3
            WVR5YmhINzB2UGRVWTJHdFhiRy85bElLRWNhNzU1NVhEeTB1OVphVUhNCi0tLSBQ
            SDRWc0tNSkMvNjhudmFQalp3Z3RyTXJFSUY4dFJEeGUxbHBRdEpFSm8wCh4zcfwS
            ENt1aVf3s8ce9xITiuoFve20yPeb/Kv8UlI2O96EmKCRYGpXxvxo2dsTJzay0uWa
            ILjhpyxZzSfM498=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T22:06:52Z"
    mac: ENC[AES256_GCM,data:wv5Y8jwyyojOYi84Gr3yUzDM+oQXlM5MXCULc1mYp7iPfysgiIsd1lvixEHFEn2laOfcow/xigQdyKfH+DYhl3LVlQX2DyPeMCcgfnaNKQoZnZOHb20U5uPfODkjehy+OrAghHr9Pf/KDJeIGTA7ldmjmavg4RUwTouADtw6uHY=,iv:36DLyy7jBEvhFnkXaFTanSdByJ3Lq8E2aLkRbSjLUtc=,tag:x2CgwWlPQ9lGUcdbljon/g==,type:str]
    version: 3.13.2
