apiVersion: v1
kind: Secret
metadata:
    name: renovate-oidc-secret
stringData:
    client-secret: ENC[AES256_GCM,data:KVy/WjIicophbYBDzlz+D/zzgn1sYEFvT+T+DBoL6yg=,iv:ICArewv5mqssS8s1zEnPEMCRrqAQFVy1Pv3GazmAZ7A=,tag:qGkmq0+8d8meWIz7R1JRGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T22:06:52Z"
    mac: ENC[AES256_GCM,data:wv5Y8jwyyojOYi84Gr3yUzDM+oQXlM5MXCULc1mYp7iPfysgiIsd1lvixEHFEn2laOfcow/xigQdyKfH+DYhl3LVlQX2DyPeMCcgfnaNKQoZnZOHb20U5uPfODkjehy+OrAghHr9Pf/KDJeIGTA7ldmjmavg4RUwTouADtw6uHY=,iv:36DLyy7jBEvhFnkXaFTanSdByJ3Lq8E2aLkRbSjLUtc=,tag:x2CgwWlPQ9lGUcdbljon/g==,type:str]
    version: 3.13.2
