apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:8A4xc9YamYegcA==,iv:MUvSMJs1bhWWXEp66YRDTlBm2DH9Ug0TcLCoaOHB1+I=,tag:6MCYqD2/W3/Fd31EpOEXZg==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:oH9KqAc7o9jLzk0gqfo=,iv:NCU4wXUJ16tl0tAr5sWCMeryo8nZlxrSrktdXrrKpNU=,tag:Z2Q+41QmKxI507/5g2pvQQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:T2BLSTob2AbMgr48wo5hpmkpqFM=,iv:jW5tanN0neZ51RG7zQtzMyTaTcSK9/9korvdUeW3ba4=,tag:8ysPHF7XXZ8bWU2UQ58a1Q==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:LnAkvhHnU9JmMAfhbYISs9129u4mQx87w0G5HGsvrjJEKqYm0TcTA3jqy62dqfcB9YBfqzdSjvlh7MPk5Owavw==,iv:1CaUkWhFktX2VLX7v6H4KCZs4Td95kioxNc1JNzHsz4=,tag:hfACviGd3J84D0PRhSQbyw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T13:39:52Z"
    mac: ENC[AES256_GCM,data:/Rn4QUtDc/rvwAJQwHoaiP98+5JbMxBe2OXq58Ce/MVq+ndLumIU88l7VrpLQbCBIHLMhP5rm7ZPAuJR8pW40t3b7PBkT6kZU6XeLWkN2ozXdwWR/9kgMGbWOudstAUY6HoPkhMgXPDIUpdyyoBqEIA995jK5ZZFSW77xA42HPg=,iv:wFzuFHGobIiopThd6mjUXSisb8scdNKzTi6iqKNyzqw=,tag:bY0Ig1pwJd6o2M4CrPlkLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
