---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io/
      chart: authentik
      version: 2025.10.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 30m

  values:
    authentik:
      secret_key: "${AUTHENTIK_KEY}"
      error_reporting:
        enabled: false
      disable_startup_analytics: true

      postgresql:
        host: authentik-postgres-rw.security.svc.cluster.local
        port: 5432
        name: authentik
        user: authentik
        password: "${AUTHENTIK_DB_PASS}"

      email:
        host:
        port: 465
        use_ssl: true
        from: "Authentik <no-reply@${SECRET_DOMAIN}>"

      redis:
        host: authentik-dragonfly.security.svc.cluster.local
        db: 1

    server:
      replicas: 1
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi

      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: "ECDSA"
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
        hosts:
          - "auth.offene.cloud"
        tls:
          - hosts:
              - "auth.offene.cloud"
            secretName: authentik-tls

    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1Gi

    prometheus:
      rules:
        enabled: true

    postgresql:
      enabled: false
