apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:/NvkWqotv9EMwNkVO1FpVvRy0c2ADrnDC/gWyVCqwZIJXj2mlk9QZSGGFXtNoZ421pk=,iv:cFVvDldwxK/r6dgkXkTB0+LL2dFIZOl8FiERcD7a/4U=,tag:pP8B3ASOg6Z/XlP1bw52CQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T13:28:18Z"
    mac: ENC[AES256_GCM,data:/s3GUPSAslIdmyJQY6hmX8Y5ESZTL4dUlik84tpsnTI2EncjI6afaPgsw8Dk0+icq0dfZXW6nOD+BdM+AAeG/CVSlvW3ALOI39N2uEuJuIML33YKdn8YPc6XKYUEWTws8G3ubourC5As/VFb2rTP5CjpT0ckqOVyI6IuILeO4xI=,iv:GyfZSngHB70TkVfMq0SFXHYRvhMqFL98rsn2zX0MbjY=,tag:6RqZDAnpwl/s6iC7JRy+yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mLUACoA0Dj1/,iv:uhLtwVTwDBveyHQmATKSaL00pIfbiY7Qj59DvOhrdkU=,tag:Kt2UqMRGgbAfdbzEMloMkg==,type:str]
    password: ENC[AES256_GCM,data:T58qpH3XiCQxQq50FPZhMPGnD0V1baKVDgYAqcuPDrPKjTBjM3ZEDfj+rX0RP3DPH2hXLbgH/KC/yDPtPP8hWg==,iv:31SXJYdb9m65+IpRvmnRki6PlmH1nOhthVk8qyucedM=,tag:Z753MV9hlk7NwK3JRAV/JQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T13:28:18Z"
    mac: ENC[AES256_GCM,data:/s3GUPSAslIdmyJQY6hmX8Y5ESZTL4dUlik84tpsnTI2EncjI6afaPgsw8Dk0+icq0dfZXW6nOD+BdM+AAeG/CVSlvW3ALOI39N2uEuJuIML33YKdn8YPc6XKYUEWTws8G3ubourC5As/VFb2rTP5CjpT0ckqOVyI6IuILeO4xI=,iv:GyfZSngHB70TkVfMq0SFXHYRvhMqFL98rsn2zX0MbjY=,tag:6RqZDAnpwl/s6iC7JRy+yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
