apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate-operator
data:
  config.js: |
    module.exports = {
      gitAuthor: "sujiba-bot <bot@home.lan>",
      autodiscover: true,
      automerge: true,
      automergeType: "pr",
      platformAutomerge: true,
      onboardingConfigFileName: "renovate.json",
      onboardingConfig: {
        $schema: "https://docs.renovatebot.com/renovate-schema.json",
        extends: [
          "config:recommended",
          ":dependencyDashboard",
          ":disableRateLimiting",
          ":semanticCommits",
          ":timezone(Europe/Berlin)",
          "abandonments:recommended",
          "helpers:pinGitHubActionDigests",
          "security:openssf-scorecard",
          "local>homelab/renovate-config",
        ]
      }
    };
