apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate-operator
data:
  config.js: |
    module.exports = {
      "gitAuthor": "sujiba-bot <bot@home.lan>",
      "onboardingConfigFileName": "renovate.json",
      "autodiscover": true,
      "automerge": true,
      "automergeType": "pr",
      "platformAutomerge": true
    }
