apiVersion: v1
kind: Secret
metadata:
    name: renovate-oidc-secret
    namespace: development
stringData:
    client-secret: ENC[AES256_GCM,data:3wZj4Cl6M6CngAPasP4YdGkGxhB1soqlM3peFO5hrx4=,iv:t1n8FM6opMtyrXUpeBtWSQezDJ3bmh4yFrED5s8CbWs=,tag:HEbTx3cru/wxkCAqha7+CQ==,type:str]
    session-secret: null
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:26:09Z"
    mac: ENC[AES256_GCM,data:c/ZkKStjr9zRO9oODT7jtd5WZi2xEuVYHB5OiLtwdrRmyRcaxjN9PMOrNMG5P2gybwXWKf9ekI52scISMZQcL5T24Oc8DKlR1/f7K6m+Nu5bH8rb2jtGEFLeh9DtjzkiCM+G4baAKj5rckYg4HgmRrAsxrrfcFYtgbIQ3xxRsv4=,iv:IsKidJjaFuxN8mYbMsIPNxie1OBz7TvtvpSbb6nBrfg=,tag:QbdwwyStyLjBrpSW4pqeFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
