apiVersion: v1
kind: Secret
metadata:
    name: renovate-oidc-secret
    namespace: development
stringData:
    client-secret: ENC[AES256_GCM,data:3wZj4Cl6M6CngAPasP4YdGkGxhB1soqlM3peFO5hrx4=,iv:t1n8FM6opMtyrXUpeBtWSQezDJ3bmh4yFrED5s8CbWs=,tag:HEbTx3cru/wxkCAqha7+CQ==,type:str]
    session-secret: ENC[AES256_GCM,data:IpSzTGrRuQkVz2NelIJkaya8tVMNXMx6+GrzQMf4ZeDBm4lSUl0vtT+QwjW5bfSitHg=,iv:79UmgavLUyFMyen92QKY0WbeJdf4FGSkXlc78CKgWwU=,tag:zoldJojpAWby6mnSrbrKvA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:33:23Z"
    mac: ENC[AES256_GCM,data:GgMZs/AXn0iHXWFfQhuQHhxaAN6A+j4mtyU5PAxtATgb1m7DUcOsiiV4OuvIHQ/k6RuaEYduXqBKMFMuTmQQxJEJe+DDKxd5KV+8RGtVezEt5VNcWz41m6HHRy/VKxeuFt561hSnI+LEjXUrbDMCit6o6ftfCVdk0KYu1RUfqUY=,iv:dke4zw1JdTepPHCdO63eJY557RXYoPAY4hHLa24lMVI=,tag:/K0U7s3O6F/vlfpCP4etnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
