
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana-operator
  interval: 1m
  path: ./kubernetes/home/apps/observability/grafana/operator
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana-instance
  dependsOn:
    - name: grafana-operator
    - name: democratic-csi
      namespace: storage
  interval: 1h
  path: ./kubernetes/home/apps/observability/grafana/instance
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
