---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  chartRef:
    kind: OCIRepository
    name: tailscale
  interval: 1h
  timeout: 5m

  values:
    controllers:
      tailscale:
        type: statefulset
        replicas: 1
        strategy: RollingUpdate
        serviceAccount:
          identifier: tailscale
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.90.9
            env:
              TZ: ${TZ}
              NO_AUTOUPDATE: true
              TS_ACCEPT_DNS: false
              TS_HOSTNAME: cologne-exit
              TS_KUBE_SECRET: tailscale-state
              TS_LOCAL_ADDR_PORT: &port 9002
              TS_ENABLE_HEALTH_CHECK: true
              TS_ENABLE_METRICS: true
              TS_EXTRA_ARGS: >-
                --advertise-exit-node
                --login-server=https://headscale.$(EXTERNAL_DOMAIN)
                --advertise-tags=tag:cologne
              TS_USERSPACE: true
            envFrom:
              - secretRef:
                  name: tailscale-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    serviceAccount:
      tailscale:
        forceRename: tailscale
        enabled: true
