apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
stringData:
    TS_ROUTES: ENC[AES256_GCM,data:MPfGKd0myfZG9WOMrg==,iv:yQF5fsV/4/p6N5oQPye3PtJWPxBeYscbHTJdwvnGz9U=,tag:JgfVwa4cCHgj7rub8bg1Ng==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T15:33:41Z"
    mac: ENC[AES256_GCM,data:qRUF9TtL6ChjwBHRyEXVPBwlyCWO49P1W1oBnSWd1eBZarfcRcstXphZu3Hmw4QwzexbGP00q23AxIwnhN2lMMiD4ob4XIW0hrTxpV++No+GeYeIB0KE02duWHnMTfRgJyefpQSSBUuSYsOaA5zEhGvZpD85SMEL6BaDmGlU2dQ=,iv:obZJbbRi449tTdX/rePpg/DBbyHy7SvxYMiV/ZM4Uwg=,tag:T/TjlbZlOjaMoGxs3vGhAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
