apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
type: Opaque
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:RO35j1ZghRpFfOKi+97zFqjVWA==,iv:gm6UaLve7RVI5piL2OkGW+PInBjuEFjRslJO+MK5xCs=,tag:1YCbHnsEE7o8UYD0aJflGw==,type:str]
    MAIL_DOMAIN: ENC[AES256_GCM,data:3s7eDHBkiz7pNPo=,iv:Z+UzAHGigbZUr5RTxofziB2A26KanYbE4ybW6/LCj6M=,tag:RFS5J/QZnTETN13H7exdqQ==,type:str]
    PRIVATE_DNS_IP: ENC[AES256_GCM,data:PJp0Sts1ABrBKA==,iv:4SyZfoyoBUTsYb39wcGymMeXuW9QRoItgv9i9ukZfcc=,tag:WzVCafkOYvwzcm4KSxjgJQ==,type:str]
    TZ: ENC[AES256_GCM,data:Z2QEaSaKaMEgmhTiHw==,iv:+zO0TzJBdyWV/cW+rBX9UWpbEyGFsAlUPMuEX3P9b4U=,tag:Ru6EN9Xz7VsyAPawfusK7Q==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueEIwVjVTRmxEODd0M1A5
            WktqU1I0b3NoaTd0NjFEWVI5NGNTbzg2MGtVCjJFSUxEbSt1bDRvaTF0dVNJT0Vr
            QWVuM3NjNFFFc0xVa3I5eTY4ZzgrakEKLS0tIDlJL08rOU1VT3pmekJuYTE4WVVB
            MXUrNEppanBnaUZXSkpYaitBTnNQTzQKZaT5lKD7bzznbIofmmLQ0ec10T8ZD3bp
            TqlOepk7xC1wuWlwdRKCu3pTXEMURwlq1CYSi4oMa2/dtTEN8uaGYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T10:38:32Z"
    mac: ENC[AES256_GCM,data:HhQFOBARUaF8OcYyPYqfoquxhnwvQIkXKwF4HVuajdiUO8Znxxcl2qu710/QivkLQ9cBnqB1vRF4YlmTty1djf6s9jGgtzCWzw+m46ggjj39kbmCd/GvfYFIDXXo+cA/AYgdpxHBE9vUO+TFwhKgjZMfjmcIJ9Df1ppn/eJzqsU=,iv:0ZbpcY4tFOssv0YI9fAgjg0M1V9/6WPIsZ/fv5A65NI=,tag:GN85jOH+lOItIdZVgZve3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
