apiVersion: v1
kind: Secret
metadata:
    name: volsync-kopia-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TjCPB8mPcMatzOPHe7ma5KU6Sg==,iv:NiJfXpDIXhi12mxfA/96ujbPlyc0YRrR4fxCV8Rpm2w=,tag:0U+/+4VI5Xc68fWiUCF6Fw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eWbvoD7qRR1UCSlekaIyTlOelj8=,iv:kd/Rsdew/EDcqJteWs0ACGl16yfNZYSxn0O7Z1t+qe8=,tag:XwtXBQXHmolDZfNR44g1nQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eEVQ/gmnmN/qm0LQNjdvyrlDe57TJSPw/NOynfT9ElmWewviZDYtzg==,iv:GXXBr4hSmplcw7qwg1aql8n2fQSY048G7HxyUE5zIAQ=,tag:HZgrVIam31v4azo8/ayA4A==,type:str]
    AWS_S3_BUCKET: ENC[AES256_GCM,data:P5b+L9sWA/mQi580EQ==,iv:8k8mbqsWqh/+tI+RGNyRMPBTXJy16zY8Soj4boBQM4U=,tag:EaK+ixWfR3d1Yka+nDXegw==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:ApC9Uprfz4D4X4AlZfhi5uRjopHPv8VYSaAb,iv:v+cX9UfyueWqDMN3NFguATS2MAs3RrQ+hq3VjvXtS2A=,tag:JnYjX2hlCsx7ZiiSlTgjRw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:3LnBJA==,iv:VnNIo2tThZobUNCihWtupNXZPIZLG4H27xYVj5dpQyc=,tag:Lo02KlPrEIGS0O3HWBZSOA==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:TYDIwmdYKzTngtSHQTN9Oz8X,iv:5/IV5DHjoVPFSDrszmKpsfiSclEMijW66Oj4sliLVBs=,tag:Zp4x13fgBRVlG89HVPyC3Q==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:WPYdgQ5ly9aV7V8X6+w5o3+8Nf0Kix5YjubO3O3dTHj6ojTY2NMOpmV6Ze+9yUAijysqyVzUEkdcVjo6VdBVig==,iv:6oRlrEXdbk3cYUHRqt6/36wXFnEiFranAgxxFqOb+Y8=,tag:7y+YL3D+QhIi57Tuhb2NHA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTRUMmNJNU82K2F6a1pS
            bmRCN3d5TlRXdXJOVFJRcXYvby9HMTl3cEFzCllGVzBURFQvaW1jcWdlYWViVkd4
            Q1NDY0V3Z3YyL3BFYXozR0Q5elVFMzgKLS0tIG5iZ1k0TVF5Vys3RE5tc2h2d205
            WHZhR3Q0dHQ1RDZ5ZG4yVEpFT3ZjZHMKFn1ihx9gY0acTkTgvE29PvMkD4mFUBWa
            wNRyFClKjzLpPZn0FjAnsu9v++i0SZa9EVuhAwna+BeF1Bca6wguDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T19:22:27Z"
    mac: ENC[AES256_GCM,data:a8T8R2iWZAUVOhLzAsKVj68BEM+WOmnTyNfjWXK9dXXElr4fW8jSscxsdXGLkfSZ/fDAzTXXQtVEgOarPva7iIdAPQY4+6QlbelBgYqhL+dTlkGDD6OlyOBLmSSScQzIiyvyDD7PrJ1v72CElJEq0ZkUbGBbNAg9a10OfGP2u6A=,iv:wMrm32SL5MIwV/mGrPxQlzoujMkvpbYyUTbLpsyrOmA=,tag:J2LoCBu2uG+0Tq6bfgaCoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
