apiVersion: v1
kind: Secret
metadata:
    name: volsync-kopia-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TjCPB8mPcMatzOPHe7ma5KU6Sg==,iv:NiJfXpDIXhi12mxfA/96ujbPlyc0YRrR4fxCV8Rpm2w=,tag:0U+/+4VI5Xc68fWiUCF6Fw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eWbvoD7qRR1UCSlekaIyTlOelj8=,iv:kd/Rsdew/EDcqJteWs0ACGl16yfNZYSxn0O7Z1t+qe8=,tag:XwtXBQXHmolDZfNR44g1nQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eEVQ/gmnmN/qm0LQNjdvyrlDe57TJSPw/NOynfT9ElmWewviZDYtzg==,iv:GXXBr4hSmplcw7qwg1aql8n2fQSY048G7HxyUE5zIAQ=,tag:HZgrVIam31v4azo8/ayA4A==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:ApC9Uprfz4D4X4AlZfhi5uRjopHPv8VYSaAb,iv:v+cX9UfyueWqDMN3NFguATS2MAs3RrQ+hq3VjvXtS2A=,tag:JnYjX2hlCsx7ZiiSlTgjRw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:3LnBJA==,iv:VnNIo2tThZobUNCihWtupNXZPIZLG4H27xYVj5dpQyc=,tag:Lo02KlPrEIGS0O3HWBZSOA==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:omcD+1/vxK72VTC+3hTeuOpd,iv:G6fAXK/hRa180psXoDeKZCSvoEotikekRRVz9Zntn3s=,tag:ZNAK0wE4qp0uVKwoPrdFNA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:WPYdgQ5ly9aV7V8X6+w5o3+8Nf0Kix5YjubO3O3dTHj6ojTY2NMOpmV6Ze+9yUAijysqyVzUEkdcVjo6VdBVig==,iv:6oRlrEXdbk3cYUHRqt6/36wXFnEiFranAgxxFqOb+Y8=,tag:7y+YL3D+QhIi57Tuhb2NHA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTRUMmNJNU82K2F6a1pS
            bmRCN3d5TlRXdXJOVFJRcXYvby9HMTl3cEFzCllGVzBURFQvaW1jcWdlYWViVkd4
            Q1NDY0V3Z3YyL3BFYXozR0Q5elVFMzgKLS0tIG5iZ1k0TVF5Vys3RE5tc2h2d205
            WHZhR3Q0dHQ1RDZ5ZG4yVEpFT3ZjZHMKFn1ihx9gY0acTkTgvE29PvMkD4mFUBWa
            wNRyFClKjzLpPZn0FjAnsu9v++i0SZa9EVuhAwna+BeF1Bca6wguDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T10:33:25Z"
    mac: ENC[AES256_GCM,data:Aa9AG1UZRIO/RHXyMTfRWOvFyQwzxPziWjuLHqOUvPFtOXzzKTiWmNCSG1bzlwDlnmnTq/eRxYbSNRr/GyEtnQKBuEv5prybKqeAHi11oatcb2KL6XY+i9hFWsOGrBTKjoiqZcQo3HO6iHzHhVgZG7jE/5EnrbNX/ThZCkssXd4=,iv:lJWGsZtQJzOKBGrwlvBd01r7bTXzMvIrCzjR06EACF0=,tag:XaJZsWwwRg+RkIFKxQLAXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
