---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chartRef:
    kind: OCIRepository
    name: tailscale
  interval: 1h
  timeout: 5m

  values:
    controllers:
      tailscale:
        type: statefulset
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        serviceAccount:
          name: tailscale

        pod:
          automountServiceAccountToken: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.98.9
            env:
              TZ: ${TZ}
              HOME: /tmp
              TS_STATE_DIR: /tmp
              NO_AUTOUPDATE: true
              TS_HOSTNAME: cologne-exit
              TS_KUBE_SECRET: tailscale-state
              TS_ENABLE_HEALTH_CHECK: true
              TS_ENABLE_METRICS: true
              TS_EXTRA_ARGS: >-
                --advertise-exit-node
                --login-server=https://headscale.${EXTERNAL_DOMAIN}
                --advertise-tags=tag:cologne
              TS_USERSPACE: true
            envFrom:
              - secretRef:
                  name: tailscale-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 9002
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568

    service:
      app:
        controller: tailscale
        ports:
          http:
            port: 9002

    persistence:
      tmp:
        type: emptyDir
      run:
        type: emptyDir
      var-run-tailscale:
        type: emptyDir
        globalMounts:
          - path: /var/run/tailscale

    serviceAccount:
      tailscale: {}

    rbac:
      bindings:
        tailscale:
          type: RoleBinding
          roleRef:
            kind: Role
            name: tailscale
          subjects:
            - identifier: tailscale
      roles:
        tailscale:
          type: Role
          rules:
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              resourceNames:
                - tailscale
                - tailscale-secret
                - tailscale-auth
                - tailscale-state
              verbs:
                - get
                - update
                - patch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - get
                - create
                - patch
