apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
stringData:
    TS_ROUTES: ENC[AES256_GCM,data:MPfGKd0myfZG9WOMrg==,iv:yQF5fsV/4/p6N5oQPye3PtJWPxBeYscbHTJdwvnGz9U=,tag:JgfVwa4cCHgj7rub8bg1Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IElkeWZNNmI1
            cTZCeXJkL1lwK3BNK0wvZjZaVnZ5YXA2ZG4rNVh1NzF2eTd5RXlaRHM4VmJhNWpU
            cFJNeHY0Z2JXT3BaTGMrdFhoeU9PZDNHNURYUGdoRi9FOXpOT1BYR3NEdFA4ajZQ
            WHU5bVd0K0xicUtIOENjZUUvM2NyYXYza1ZibmgxZlF3WDFWZzc3ckJXSnBDbmJs
            dXpOMHpsM25xUjZhc1k4STdiUXRRUzNwM29wMlEydXVramovaWo5eElLMnNyTkFy
            Qit5V0UyUWpCNlVyMllib2ZxL00xNnUvUGRMc1pGWmxzN2Z0cExYSEE5eE1qRFVM
            SDRzWXNUNy9uYUorWVFNUGhsZmlIVUU3OExYYjZ6NjdPV2ZEeHVwUnNHUlJHSlkv
            bHpacG1hTkM4ZHpRTEcrVnpyaWxZNGdHbGVjeWh0dnZUTEtHdk5CNjliaDRzaEV3
            RVQ0UGZOVWh1OXVIZmJrY3J1SDVVU1E2ZjRzbkhnTUVwTS9iYWpVTUl0a0l3UFYv
            UDZoUFJlOTlRWDZ3WmlQemtvUHJpODNYL2MzM1BkTllseFJ2ODlndTJwR2RkK2E2
            NUlOMWNyckhoWk5iRFpsNTVCT1A0M0tTVWxVeG5Wdm4vaHhTM015dldoVUxjODNI
            Um5jYTl0bnI3VElxaEtreHp2NmxPbFNxa3Y2TFpRY1NWSzVic3cvak5HekNIVDFQ
            N2YrY2hDaVFFaTFwTCtUR3RaWExUK3ZEcFNlaVJ4TVF4ZFozaXBhMSsvdUhnbnRG
            aFF1cjJEaFBUODhGaWQvTnNsR0MxNmgrQW0vaHpoRWMxQXRaZDNnYzFXaFUyT0dN
            QjRnSkNjNVFBQjd5YjFFcTA0UWpsdWZlbEJpbFNCTER4L3dQZ0IxSVNDNW5EUER4
            VFdUNk5vK3plTkdIWHdHTWw2Wko4RllEbkhZK3BnSGR1UUFxNk9hZ25LTzFhSG54
            aXVDdDlML0gxQ2hWY0xtckxCRGlMZHBjTG9qYWxvb3MvMHVoUmsvYVJOWmRYcHkx
            VkhUMWkzYStLTzkzR09CckxzVUt1TWp4MUNzZ3ladjdCamJHS1Z3YU1ZVi9pbXZq
            V01xVjZmdmFteDFvc3h4bEVjZTdhRlBwQmVuVTJSUXlLNzhwWWlYZHJYVXZ3bjc3
            OGNjT0RjQWM3ZHltbHhHNUZIUmwxaFJXZGVrQmxLOEpyLzExa1ZGSnptMkxja0NI
            VzNmOEJTK3NoajY5d1k2Q2pidWtYdXBlTFhaL1RXT2lvVkNHQmpkTjNQV0trRTdC
            dU8wclFxNlg5d0Eyd3RsdnVKRFF3Q1FOUjBMaVhwU2pyOFByVG5xK08wQmx1OGp5
            cHpueU1mbWRrbWJqQUZYS2h1VUdFdWFGTkp4NU54ZzRoWFVpMThrTnNiZ0E2a3Iw
            Ymp1ODhUY2ZDdEJ0L0dzSE1uNHhGOHczbWxOVE5YRnRPOUxIbXNteVN0RUgxNGdu
            YVdwcWFBWWdpUXhwc0c5dk5EQThXSVdVM1BBNThUY3Uyck4wUG1OL3VVQ3VDcUY1
            SUxGeG8vSk1tNHBxWjZreGFJWVR0WmY3d0NybzNuN2dkVTNRVVZBY2oycll0UkNy
            UFoyaTBOTkNDZTlTVkJZNE02UG4zSnVrN0FpTHBFV1pzMzBjRldUbE1EUDN6UVhE
            VnR5MHhHR1ZIUVY0MzVuV0xxK2hxNzdmTzJ5UzA3ek5aUVhyNy9taHB3TldjM3pQ
            ZjBlQTVUbHo0Qnl6Nmx0SmRFSUJZeEpRbXdFcjFTOGpCUXhhQXBPalltaTN4YkpD
            OVpVRW1mNXhQT29JY2I4QXVoaUZPM08weDJJNTRDRVg3dVcrT3ExUzdEYXd1cFd2
            WHZJWHJyUDNNNkdQYkZRYUhyV0V5eDdkTlo5M3ZPbytVcytOSTF6VzFIOHZGSEZI
            Zzl0N1FEZFFCN085QTBnU2tUZUZLMG5paXhLSEgrRUpObllhMWd2ay9EaVdJQQpx
            bE5DSUk4d3dNS09NTXBSbmx1Vit6ejdFUGZPTGZma1FDcEkraFpGVE5VCi0tLSBl
            dEZJbldhTXBGbDByUnJUMlJ0aTVLS2V1ODdhK0hBMmRrRWZlTElvaTBJCuHOupKL
            HGeAAB3OIvQrXopxQrWkz3xK7JRne8Lhq7625d/W7zc19uvvTbzdgg72ldABFd4P
            DIGty8wqOyG3WdI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-28T15:33:41Z"
    mac: ENC[AES256_GCM,data:qRUF9TtL6ChjwBHRyEXVPBwlyCWO49P1W1oBnSWd1eBZarfcRcstXphZu3Hmw4QwzexbGP00q23AxIwnhN2lMMiD4ob4XIW0hrTxpV++No+GeYeIB0KE02duWHnMTfRgJyefpQSSBUuSYsOaA5zEhGvZpD85SMEL6BaDmGlU2dQ=,iv:obZJbbRi449tTdX/rePpg/DBbyHy7SvxYMiV/ZM4Uwg=,tag:T/TjlbZlOjaMoGxs3vGhAQ==,type:str]
    version: 3.11.0
