---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: pocket-id

  values:
    controllers:
      pocket-id:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v1.16.0-distroless 
            env:
              ALLOW_USER_SIGNUPS: disabled
              ANALYTICS_DISABLED: true
              APP_URL: https://id.offene.cloud
              DB_CONNECTION_STRING: file:/data/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
              DB_PROVIDER: sqlite
              EMAILS_VERIFIED: true
              EMAIL_LOGIN_NOTIFICATION_ENABLED: true
              KEYS_STORAGE: database
              LOG_JSON: true
              SMTP_FROM: no-reply@${MAIL_DOMAIN}
              SMTP_HOST: smtp-relay.network.svc.cluster.local
              SMTP_PORT: 2525
              TRUST_PROXY: true
              TZ: ${TZ}
              UI_CONFIG_DISABLED: true
              UPLOAD_PATH: /data/uploads
            envFrom:
              - secretRef:
                  name: pocket-id-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                memory: 250M
                cpu: 10m
              limits:
                memory: 400M

    service:
      app:
        ports:
          http:
            port: 1411

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"

        hosts:
          - host: "id.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "id.offene.cloud"
            secretName: pocket-id-tls

    persistence:
      data:
        existingClaim: pocket-id-pvc
      var:
        type: emptyDir
        sizeLimit: 1Gi
