---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: configarr
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: configarr

  values:
    controllers:
      configarr:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        cronjob:
          schedule: "0 16 * * *"
          timeZone: ${TZ}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          app:
            image:
              repository: ghcr.io/raydak-labs/configarr
              tag: 1.27.0@sha256:a258a9b195fe2034519cbc28b3b79ced4afa2e22f3da5eca7cb7bcf55c3129c1
            env:
              TZ: ${TZ}
            envFrom:
              - secretRef:
                  name: configarr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    persistence:
      config:
        enabled: true
        type: configMap
        name: configarr-configmap
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
      repos:
        type: emptyDir
        globalMounts:
          - path: /app/repos
