apiVersion: v1
kind: Secret
metadata:
    name: configarr-secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:InMXh6mHj3iRQsVbhCQlHrCK0dCOvQerksDCipLDdCI=,iv:JwypOAfg/Zz1R2cNyoNipROolOJgS6J2j7YvwVe89ds=,tag:v6bMbVHR41B2J73CZkh6Yg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:hxpEcRTyN0Ex7otff0IwBgM/FEE/mXXVJceNHgIph+A=,iv:UaL0Zc9L0qvQLyc1+/6UIhFFLP3f8TDPpcCr33/yQUo=,tag:3egomnjqx6QEd0ITXedXBg==,type:str]
    SONARR_ANIMES_API_KEY: ENC[AES256_GCM,data:T0qqJAQiSP3uRZfXIA0DdV/Vu0yRvOGmwwgbHCARbLE=,iv:h9CbTeGanqnnatOTAmEBPBaVhZgw0GJrNkYiRbW0940=,tag:C8i/6s/4PN9JHLHBHushHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHlIR0VXbkNE
            NlV6WWJSb3hOK1p1MkNGNTF2MlB0TzFwcFZ5TVdtdkRxMThNQ2V3VjVsTkprd0Jp
            RUVrSUREUmlsZ0c3OWRsU2djZmpERStUa044OUVwTlJNRDZDcVF0NGdDSFhYOE53
            SW1uYzlmYkxEMDVOOWtLdHlqTmxTTE92c0o0eHAwQ0F5ViswTFpJNk9adncvZHRj
            NW1DVVBGUTdldzRaM3FGandFWHorbTZoN0hOdnIyRWhqK0ErWUI3REFxaVpKZnRx
            TTJxcXdqWDJ6SmwvMGIrY0U3VElNUlVYbE9vRGIwNkFha3dnTUZPQy9kck00YXE3
            bm9ySytaTXhEK2hmcFh5SUh1dW9mK3dvYzVRckZlclpFcDZyZ1I3SWpSdlRPUWFW
            cFRxR1V3bStkQ0JENDJtV2RwQWt0TmJWaFBQdi9qejIwR0FBblJkZENwVUk4Mno5
            Z09qM01ucThRMmlvVU9FTzdLcWJOK0RESkphdlRsdWkvRko0Qzh1NmR0T3RoNDlG
            NUlGYkRrZEhnYjV6MEI0SnYxcHQ5SW11S1hnUkRnaFJ5ZFFHWmpRMlNpaC9iMVVR
            VUQrNjAzL2RTNjVwZnNYZXFPWS9MYWVwS0I4K2x2VzAyWGtvTllBbjBVWnZQcktP
            Z3g5Z3RhQ2FENU56allZUUY5NXBnU2Fodmp4M1hOQ0JVSDdFTHpBWjZhUnlSakFP
            T3d5VEZDTkhicnZER2VGOG5oQ0NJSVRhSkJtSXZtdGNYZGxodmRxYkZZa0FTSm5z
            ZE1SS2pFcHlBbERMNnp3TTYyL09RdVhyTHFrWGZpZzJMTUt6eWhxRW5nZ1cvWWRk
            V094ZHVDc0tqVDdjcjU0S3VJQUJzVDR6UnBPNU9jNnBUdktHZ3g1ZVVNWml2aTNP
            MmRwZWM5S0o0eGNrQTN6OGtXODhkaEpKVEk0OVBpTnNLYjdvRGFCOWMwRDJCMTd2
            V2dhQ1E4eWhXTUdwRG5WbVhsdjVmQ1JjZUNIbWgvcUdnSUpJTmpnM01ESHJBODhS
            L2NMaG13SjlTdTlaaTZmMGN5U2Nta3VoblNDWGd6NWk1NkJDMkdBN25CR0YxZjVD
            aXpkWmxGVTl2TVRTVWZ5VEh5K0YyOXZlRDdrRThsRjgzc3J2V1RadWxpOUI5MU5m
            UFREYTBTcTZud1VsYzFpUzcwVXVUbEgvdkRXQzQ0b3dzQTNaeUhIejB4K1plbFQw
            VTRCaWtpc2ppdXZHQWJGSm9BMGsxcHJBWWtLZFZPK0RZa0FsWUZtWmh6c0RaeXRV
            SnQwcEJMQllhU05zZFZFSGdiak9WZndhRFFXN0x6SkNRTnBVZExsbGhLeDJzT2J6
            K2J2dEFIM0VNR1NCRnA0OHJ3UXVsdGZxVkNvWkI5WDhWem96QW9rNVVSRW04djY3
            dTJhbEhNbUdySFk0MStCS0xkVEhCcXp4d296WFBMUmNILzBaRDFuZ29KamQ2ZTNS
            SVBNbFd1VnpCTWRZWFR2ZG1ES2NjQ0lXZjJvMzZRdHhsRnpmcTIvNm9BOEU1dVc3
            aHFUdmtxMXBwS2lRcXRHNklPQmNPTG5RSUVzQ210ZXEwS0o3Z0FVLzA0aHNyUm1w
            T2FGTVhCWXhFWGpXRDZTdiswcC9MQ0Z5TzBrOWlybkpvMHhnTG8wSHhweFJQcDgx
            WmYxZ3I4MzJQWmx1UkMvdncwZzZoaHE5dFYyZThaYnlWUG1nYmg2b2U0Si9tSC9O
            bDkzLyszYUdGSmxMNmo0eUNVR2pRVDUrM041WVdyckgwYjJpT3Avd3FHS2ZMdjRX
            cnF3b21nWkZyMDh5ODJJU1VSTytjcUpRRS9Gelh3bkZ3QUk1REVZemVYa05SZlhF
            N05Xbll1WTZzbjZwcFpKVy9lL3NSU1ZOTHZONkZqamR6dnVZK1BGZzlqV1VqdzJt
            a1kxNmxqRXUvczArcjczb3owREF3c0ozK1I4OXUvVWwyeitRYUJrM2ZKcXVQdwp1
            K2JUVzZWV1c0OGJlUmdzWW56WUN4Mnliazl6c09FVFFJblA5QSt5VzU4Ci0tLSBO
            eDlDKzFwZzduQWJmeGtPd2NJdjBXWFJOQ3lid1NYMU5SMlBVUWVuS0Q4Cn/heCHq
            LcQnsqrdmigyzFt912f/KZZ2T/0hFbyaWXLGfuEm4F+yTwx4DmNJMW+bG13rDbK5
            4Uv0cUMG9CAet8E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-29T17:31:27Z"
    mac: ENC[AES256_GCM,data:+M6Q1D6vXr8iBEh0i2aIa/+HE2rkAix4mqak7fDh640HRwJP9bFnT51/1Bn6h+uGGnHYQnIKpqSwKt4dfZLsgrrFddH/EY9WLXCQMuPeqQxj53Vm4emtU/xlk9AGIInQx6twu/oGoG/4rfqwMk0z7k2i1KSuYPvfv3kC9unrnJU=,iv:rbbl9D2MP7nz46PcOD8hNNYLZZgEWMyxQWF7KLK3SBQ=,tag:WzE1tPI5ju2twr1Eozg11g==,type:str]
    version: 3.11.0
