apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: selfhosted
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:nZalx5FA6yYIJIMHSwq9PfrmWlAscpPfnrTaYwbE/UtgZR//Mo+cxfGkY57haFu1ZZWVq9Z7dXiKknhbGGgiow==,iv:seDo4E2e6HwyVP3YG3Lrh6l0NwbaNbwuVnEN8XlxJ9A=,tag:2UzkVeJCaCb+vzqVxFpDOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T15:20:23Z"
    mac: ENC[AES256_GCM,data:Jz2PYAkWev1jn2oEVTsMDXbLTcb4YFnmKKM7WAiG0v8NpQIgCe1DutSnFAz4r0n9BpY4FVV9C1/KkvCCcXRuOp8tziJbfhwl5eNViRw2rzegHeGl/nUIiVZ+9SRPCpiQ0/jp7/fKlA5E+LdNTQW0L1oiCTZma3jzaSkcqFsfczk=,iv:h6D5KBNl9Mxnz8hSyKyqYNW5RNVGRT1aVSHQuIvHXoc=,tag:nQdjKx4TZalSyktaUAklOQ==,type:str]
    version: 3.13.2
