---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  install:
    crds: CreateReplace
  interval: 30m
  values:
    serviceMonitor:
      enabled: false
