apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:RIp0iGa2c9+J246WuQ+CYAUolP3kPhZ99i9+u+awi51dwsTjWuLIcvb0m2UamETToZvL86rPb/u1HGT37dE69evM5w==,iv:cpz+etWSi0uuTPTMeb7uuZmKAK1z8jQg3D0blZIJJ6A=,tag:rlcbfOLzQkZ00R3H6Q6AkA==,type:str]
    HETZNER_API_KEY: ENC[AES256_GCM,data:mUcauBqPWjjMTpE49UnkLvfKPOjQdx7XrMxMSZKg+MQ=,iv:DQ0Ig+N3KA7yYDuuf8Ay0FSbM0AW27p++tJ91GgrpSA=,tag:KhEZvjQ6RrHEfRWQPZDOEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS2ZHazRDVVNmOEY5R2Vw
            RHVWV1lORmpmRWhZRWVzenRxK1dHdHo3MTE0Cm9qZnRTdWxkSnBwZWwvUHVlS1NW
            SFp2Yy93QjJ4YWsxK1N5eW42N1N5am8KLS0tICtzRkM5bW9CNzN4UjZIYzBYcXpx
            UnhEQkkrR080emVYZ2F5WjBGK3B6a00KEi8tOL5XitevAxs3/WorvjTOVn6OTyZV
            boaJjYt4NUIRMHf/pbgPll32FdP26Y7Y6xCAcEOu917p8W5IthVjnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:00:49Z"
    mac: ENC[AES256_GCM,data:sE9ofrm+/K5e3W3OfA8kSeUS2zPHpCrOO3DkePxl+mZLmHc/S4qeqWRmRobvDEHa7KeXwuBeDYIdOdf5cRLkoIUe80KuvcF8zWbmXvA1PTgOCWw0f5YViHapd5AJSj6ZfxZ/UW5aFTMou4brZL/BpV6UJio5Jr/3woOnF5GKEQk=,iv:sJ2pN4c6laFFvQZ9Dxexl9XxskK5bYFkb2Rt5OTIF64=,tag:yZBd0+p4SapgxIjMNhi4Fg==,type:str]
    version: 3.13.3
