apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:sfLsBSrLBX2yiNmWC+sZmcrM85QVGlecj9jebBbBSEDtWQ==,iv:n4yAD6NQtkIg2/t+HV7aYoYb/L4ReU78v02qVtjFXKc=,tag:qn/fBYC6nPQ57OYsXQzz3g==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T14:15:06Z"
    mac: ENC[AES256_GCM,data:kd05cBRFqLly7RYyIxOSUWbIOHy/1tL8Ks1g0pND7MyIHgPOx+Dq0AQF4DUaWjzJyoSHOAaK/2d4xJpsCBNEKXXqLUQ+K5+zOgVPuF/HrO3LAyhm66BFPzGbeCSV8bqAX+wA9MHW8pv2f0UcN9/G0+ZkxyFn3lD8RvudCVQd1ww=,iv:aRAbabpM5yyfXrv5w/VmqD1Gp0uPQcKiWvFLSdwq2K0=,tag:REwCihyCaJjbdmG96RwyeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
