---
defaults:
  hidden: false

badge:
  size: 12

metrics:
  - name: talos_version
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    title: Talos
    value: labels["version_id"]

  - name: kubernetes_version
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    title: Kubernetes
    value: labels["git_version"]

  - name: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    title: Flux
    value: labels["revision"]

  - name: cluster_node_count
    color: '"green"'
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    title: Nodes

  - name: cluster_pod_count
    color: '"green"'
    query: sum(kube_pod_status_phase{phase="Running"})
    title: Pods
    value: humanizeNumber(result)

  - name: cluster_cpu_usage
    color: 'result <= 35 ? "green" : result <= 75 ? "orange" : "red"'
    query: round(avg(instance:node_cpu_utilisation:rate5m{pod!=""}) * 100, 0.1)
    title: CPU
    value: string(result) + "%"

  - name: cluster_memory_usage
    color: 'result <= 35 ? "green" : result <= 75 ? "orange" : "red"'
    query: round(sum(node_memory_MemTotal_bytes{pod!=""} - node_memory_MemAvailable_bytes{pod!=""}) / sum(node_memory_MemTotal_bytes{pod!=""}) * 100, 0.1)
    title: Memory
    value: string(result) + "%"

  - name: cluster_power_usage
    color: 'result <= 400 ? "green" : result <= 750 ? "orange" : "red"'
    query: round(upsHighPrecOutputLoad, 0.1)
    title: Power
    value: humanizeNumber(math.round(result)) + "w"

  - name: cluster_birth_age
    color: 'result <= 15552000 ? "green" : result <= 31104000 ? "orange" : "red"'
    query: round(time() - min(kube_node_created))
    title: Age
    value: humanizeDuration(result)

  - name: cluster_uptime_age
    color: 'result <= 15552000 ? "green" : result <= 31104000 ? "orange" : "red"'
    query: round(avg(node_time_seconds{pod!=""} - node_boot_time_seconds{pod!=""}))
    title: Uptime
    value: humanizeDuration(result)

  - name: cluster_alert_count
    color: 'result < 1 ? "green" : "red"'
    query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
    title: Alerts
