---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.13.1
      sourceRef:
        kind: HelmRepository
        name: backup
        namespace: flux-system
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
