apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rcTSCoeUIB9StvFKDv17CYrLFX+6gNd++XiEDNDzysPYb5dBk20aYVAK5mZfQsmmYgreAYibrN7E3f2xJupMR144l2m8PwH/nUE2POieE7JSfR7VDcWNKA==,iv:fb0J6Atls9NAZgH1+qXxk8LVQRo0CWAmyqc0c5JcOx8=,tag:Iu+ZNX/cgQTsgQGOlv3lsw==,type:str]
    SIGNUP_DEFAULT_USER_GROUP_IDS: ENC[AES256_GCM,data:52B3gSqsAqzKCY0sbQHnK8o8t7cmBh6LOihFaN5cf7Z4AqZyjQ0rAg==,iv:/oYLeRGkS6MJig1X8673/bnCIAw+0NEJxKBKCAFKAyA=,tag:gh6uERpzA4H3OeaFRFh/3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:38:26Z"
    mac: ENC[AES256_GCM,data:2R3dsjmwZ+qQ26eUYAtey9awDellpfqWpV4Eov3lJQsOGt0+lCENltkKl01m55u7G5pFWv312ZgNpHNkPmvvMzIfeVqgUGYGdrCNt8W3IoGMmb8Hi8FRWZDXNkIWQvlw3vQ+z9bl0r+GtQyQG2jqRAx9D5TjtxwNQDDL134ch6Y=,iv:vCrIRQfGi7hakyAQcXT02KvkypsEfPvzdOeK5mb07MU=,tag:1tu31yN5VmGxsM5BbvDV/A==,type:str]
    version: 3.13.3
