apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rcTSCoeUIB9StvFKDv17CYrLFX+6gNd++XiEDNDzysPYb5dBk20aYVAK5mZfQsmmYgreAYibrN7E3f2xJupMR144l2m8PwH/nUE2POieE7JSfR7VDcWNKA==,iv:fb0J6Atls9NAZgH1+qXxk8LVQRo0CWAmyqc0c5JcOx8=,tag:Iu+ZNX/cgQTsgQGOlv3lsw==,type:str]
    SIGNUP_DEFAULT_USER_GROUP_IDS: ENC[AES256_GCM,data:iCmXz80Tqjtskxvil5wtycSDjNRX08j+FrY7ssTsQngczBQw,iv:8hz/8vEG1ftKhU56rXyDXqq9bUDBiJ/Y28fLzMwninc=,tag:uI1tHR7MwtptIufPThR0Jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T11:37:36Z"
    mac: ENC[AES256_GCM,data:juf5HMWGdvaOK1bynuc8tRfHxMoWg5eoAtOKJSFK+Il3/hm75dHtVeVP8wPFKzQvJgzW0CddNqbpNjr1bJEosNiODFxY4ceB5s6Js58FzR4uau8CLeqHJsRnv3HoUTKSChtTBeYFMzrhGUc9zVCvGT1iH1Tu+NajgmSh4oyyWq4=,iv:zevWKMBzQ4uShjZGwcTJXiqF/aCtGq8icfz9bdJ/8cc=,tag:JNdYgyerpk9vSVGSdtZ5LA==,type:str]
    version: 3.13.2
