apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rcTSCoeUIB9StvFKDv17CYrLFX+6gNd++XiEDNDzysPYb5dBk20aYVAK5mZfQsmmYgreAYibrN7E3f2xJupMR144l2m8PwH/nUE2POieE7JSfR7VDcWNKA==,iv:fb0J6Atls9NAZgH1+qXxk8LVQRo0CWAmyqc0c5JcOx8=,tag:Iu+ZNX/cgQTsgQGOlv3lsw==,type:str]
    SIGNUP_DEFAULT_USER_GROUP_IDS: ENC[AES256_GCM,data:LiOs7Ob3xB9FNyhxo/e75vGWJx14CcLljybOJJGsQMcQwfH7WyVbXQ==,iv:uwKUZRRGVJ/wrOiRCk4jcY4M+ZmbOKw3gZk9aMdZjh4=,tag:snA2zc+8LB47J9i0MH4j5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:03:15Z"
    mac: ENC[AES256_GCM,data:INPK3oVhAeo4tVHVL0Ma5zFQj79JWaUvIFQRLwKtGZHdMPG3yyojLiu3VQKcl+HUDoDPqvp7P1FDRdGoyUmUgqcyVH8itH0OizuT0DTpZDk9AqlbSbe5h5h7vu79ityk/nhFJ8fvDWL8mFBBAnDRMREQIjfDCzsuZ2amsYHoCd0=,iv:IPsqNZAjDVN8cv4OTtrdejchxbyJvHCH2mqtiAk+qJg=,tag:r/hduXvUan8V6YnxmeQUIw==,type:str]
    version: 3.13.3
