---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data-pvc
  namespace: selfhosted
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
