---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: &namespace cert-manager
spec:
  targetNamespace: *namespace
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1m
  path: ./clusters/home/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-webhook-netcup
  namespace: &namespace cert-manager
spec:
  targetNamespace: *namespace
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
  interval: 30m
  path: ./clusters/home/apps/cert-manager/cert-manager/netcup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
