---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: calibre

  values:
    controllers:
      calibre:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: V3.2.0-DEV
            env:
              TZ: ${TZ}
              CWA_PORT_OVERRIDE: &port 8083
              #HARDCOVER_TOKEN:
              #  valueFrom:
              #    secretKeyRef:
              #      name: ${APP}-secret
              #      key: HARDCOVER_TOKEN
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: *port
                    path: /login
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                memory: 600Mi

    service:
      app:
        controller: calibre
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
        - "books.${INTERNAL_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /confg
            subPath: config
          - path: /cwa-book-ingest
            subPath: cwa-book-ingest
          - path: /calibre-library
            subPath: calibre-library
      tmp:
        type: emptyDir
