apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    HARDCOVER_TOKEN: ENC[AES256_GCM,data:Zg==,iv:yk1OEYRZNba+sI0NAYqRddlDI+qbAkKiLzzzrQvZX3g=,tag:4cisd7RB23Q45tTqPWiXRQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T22:37:45Z"
    mac: ENC[AES256_GCM,data:379doQzw+Ps0JdS1RXkpuOphpP+/I8uWqdLBuH4/MYGPSYa1o+w0Xg618TXVDP7EZ8rSFs723YU9S4ktR/iAe2OzdvkUVmvIH6/VfwcDh+UEsYYzmi3m611MRbtqc6kh3EQ+ARxXr7dRA78LrqU9C/GOIqQkzLwgtP5LV5duLLo=,iv:ZCNIgqKVSF+xpm3VcBvIpI+c9Q+iRIm2DyIV6FaCR0k=,tag:YSfvBz/MivI7ymHpBPWpbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
