apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: media
stringData:
    HARDCOVER_TOKEN: ENC[AES256_GCM,data:eEMebl7IY25P6m6YNqwiZEqCpySRhYbVGpwYTbON6t0RV2pxokyJh/RLJsbSbMqOECPxDrt/IQSn3L3WcLt5dyWC8Z6k+qgb7vPfWfiDyR1m3Svs8dYKzp1B5mQuFvF4z0M86uQjwnpilmAsigwCSTPDBAU3iBPd9h5F3DEEF3esuhRIK4CSra+CwRV4h/TAOzpY1ZCAVr59KlWLmbaJjeGK5B3WTzCp/1k0Sn5Y5v0RO09tkheSOQYmlbS4DrHwPjLmDXjrROb9aKNUnSr3ONjpBOTSDwlqRTxg1qKAEOIAeJ22wZdoPOfANAf0e2vLCX452aiBoyogzI9h5ZPvYM2tlUzKCLSqe9AxYzRttXTgtJodwGn/IBhH9yWPZw/opvc9uoHSpvEyFHbLEbI95glnJ/D6ksBQMIrk2zXxnvFud52q0znDDkXbZ0MTOUlb8DSfuoD5WfoXMnxAiN40/tQsoFsTdiXgUb9yKre1IvFO282J+TOwQbasepDgFJeNRgtaqcBi6ZowzqNZFCBk4AWr5FhBjTrveOuOHdGhzKpQktndLRWZmHTaXBQ9nHzlqHkCBBQQ9rbAKxx/OSY5CIWNKtvacyFrLQDRbCt01UZliTliEpgLSTPdapRK+cu34BIbspp8UY8f7UZDJBREUkd8Bf/ujnQTD62o8MVWLHgo1dt0n1NNguh0hIHDMJPQik0tDhqsvA5EH/kd,iv:BDAR8K8RmG0NFai4YkDo4ohvvgZxOknTJgozkSk7BjU=,tag:RAED9A2AhpxzFzfN/68t9A==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva1AzaDRPTUFOcjhNbnhi
            WkdJQjNxV3RYa2NvUzdWanhZZ0JtM2FrVTJzCmVCZ1Q2SjlhYVBhMmZWY29nRDNR
            ZXoxZ2ZzeU52Y2hudDg2Vkx2UklubHcKLS0tIEh0NmV2SzhrMTdOUFoyNUdjcHF6
            TzUzY1duanB1Nll0bzYvY0c3UzRLaEUKNpCfqgVnMjaX/pxH/ooGIS/oH9kPdRPk
            ZNeKxa9UMEvoIgwtykCSJ/nXA9UJ0QN4ryasvV3HFF1k4a10NYlLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T20:14:13Z"
    mac: ENC[AES256_GCM,data:k9Jnlxun6g0UdXBNefw4NxBDVN0NV7ppvl370phBCD0SW0zxf3PxElUjcjFA77+SDbaJBo3GQmMLR/HU9mI03SZmMlCNo60iJ0zwnEoJ0p9kU5wqHyD16pczr8CKAMBwaDtCtousyDV/rgv6YAdwiPvjGG4ypILGsbao0f23rIQ=,iv:P76tzk81tcwYJt8y3wa+X+om6CLIcWSrUlKTbzUo3/g=,tag:aJiALeM3ow0UwA94UvGOtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
