---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: kopiur-s3
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repository
      bucket: kopiur-backup
      endpoint: fsn1.your-objectstorage.com
      region: eu-central
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      key: KOPIA_PASSWORD
  create:
    enabled: true
  scheduleDefaults:
    timezone: Europe/Berlin
