---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: kopiur-s3
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      bucket: ${AWS_S3_BUCKET}
      endpoint: ${AWS_S3_ENDPOINT}
      region: ${AWS_REGION}
      auth:
        secretRef:
          name: kopiur-s3
  encryption:
    passwordSecretRef:
      name: kopiur-s3
      key: KOPIA_PASSWORD
  create:
    enabled: true
