apiVersion: v1
kind: Secret
metadata:
    name: kopiur-s3
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eQ==,iv:u3H/fAr3bBlKhBEdd4FCv4/3AXdUfxg3pYoDgRLGpOg=,tag:nNrKXgpWwCbsteCm9oqVLQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1g==,iv:CtO252OpDjS3ZWEUiDtGQjvBs2HJI8+vHmeRJ34pHvc=,tag:Mp/71MGLDEZtxwnOg3QY8g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:8Q==,iv:Vv46pnAAEn339JForSKLm6Xot0Um9SReN0I3+TRHNpk=,tag:UWdJ31L1CxF2ob/964nyWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T22:04:56Z"
    mac: ENC[AES256_GCM,data:HyxvZHy3LOTnIbfTr056jKbWdX3Hsi8VZslxQ0Ip+gC7L310Rjr2RSBk+yyHmMo9ArQ+TfWmSFYO+0V7xmvIDJWIJKBeridHdue8iTtm2yv1gH9VjoiEOIk45M+3NJgg1cPiNIVQh7WyX5gwNA0/dd15L6sxNf7nzRKMgElz5Rw=,iv:UBfQ/UABBMNf6KWpppgRdbV5D6f0aotj7M0j/kY/2FQ=,tag:te3k+5DhRzJleqDHnyfPhg==,type:str]
    version: 3.13.1
