apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-secret
type: Opaque
stringData:
    CONDUWUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:tvaG54zssM7kc4CfzbPTfe2tsCk4EViSH22jMs1d4RUopb5E0AvlpAZAFNTNQbsZnTAVNzgKR3OXmai7uWlp1w==,iv:uFaU3Qg4+FP9q2fOMcn6RI4FRHr7DRhe/aYQi0c/rx0=,tag:M9pNchrgfpqQnxkvGJD/DA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T12:36:10Z"
    mac: ENC[AES256_GCM,data:9Mg+PXTvzQgYgXccVa9YEAFDbK0bxgHe9p6t/0K68qOpU21zxgzokdAukyM5Q0FSm2FXIHL3yS2WZH02I3aI++aC2i8lQ62Mxl8rlvAFxnuICpDgmCRWmwO3G4gXVcMyTzgmogLC/efHOXBxIqe+NNRysX+hsm9dAIs/5FfIjlk=,iv:WIaLoNgGCRafFKedY8HsdhUgqvHUcprnbCmRHSjCVk4=,tag:oVCchz+89aQGFs45aelZSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
