---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: opencloud
  interval: 30m

  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          opencloud:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 3.6.0@sha256:6732f01b1411fe9ba6efca6a7e72e98f1801f75b533eb34a96e48c0fefb1afaa
            command:
              - "/bin/sh"
              - "-c"
              - "opencloud init || true; opencloud server"
            env:
              IDM_CREATE_DEMO_USERS: false
              IDM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secrets
                    key: idm-admin-password
              OC_ENABLE_OCM: false
              OC_LOG_LEVEL: info
              OC_URL: https://files.offene.cloud
              # do not use SSL between the reverse proxy and OpenCloud
              PROXY_TLS: false
              # INSECURE: needed if OpenCloud / reverse proxy is using self generated certificates
              OC_INSECURE: false
              # enable to allow using the banned passwords list
              #OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
              # control the password enforcement and policy for public shares
              OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
              OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: false
              #OC_PASSWORD_POLICY_DISABLED: false
              #OC_PASSWORD_POLICY_MIN_CHARACTERS: 12
              #OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: 1
              #OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: 1
              #OC_PASSWORD_POLICY_MIN_DIGITS: 1
              #OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: 1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: "ECDSA"
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: files.offene.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - files.offene.cloud
            secretName: opencloud-tls

    persistence:
      data:
        existingClaim: opencloud-pvc
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
          - path: /etc/opencloud
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
