apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:96B3t6NROyYyDPhXUHtLoAJyTtOtb486/3tpoPOZb/UOTyEY,iv:y3N0qkiyA+/c7rBE6Vja6h7atM4UkRfnAPJ9k7mGjsM=,tag:G6cN3ab1t5ouqMlln8E7DA==,type:str]
    client-secret: ENC[AES256_GCM,data:wQ8x45ViTArE2ES7VC6fXLrZJjtRY6o/k7p5WriClpI=,iv:TsCUTGbY/BDQl29KqdwadJTLhH4/pwyv6EW5gMbDeHA=,tag:k7cwedFLEVTuvGwryog9dQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T18:10:44Z"
    mac: ENC[AES256_GCM,data:4PgGudOZ4ApGdqloH4w1XqrVBfTg2E/ZPSVtEDJtxDnLDSxqlxGQdBnk0eY+2+5VlxQJdRqwOuwg756QxnFfHgI/yLuz3qQHcGt26HtKEyZgcnUiWGATdiOePdQMyYuIHyRP0QJuODlg8zRo4BW463dY50OO933gmevEKzs+49A=,iv:6vhpnE/MxZZPSfHFOWb9oFfR1DmWMVDuV5gev9FBTHY=,tag:rkJe8bksNDgrXBtMsBlA+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
