---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: mosquitto

  values:
    controllers:
      mosquitto:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${VOLSYNC_UID}
            runAsGroup: ${VOLSYNC_GID}
            fsGroup: ${VOLSYNC_GID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

    service:
      app:
        type: LoadBalancer
        ports:
          http:
            port: 1883

    configMaps:
      config:
        data:
          mosquitto.conf: |
            allow_anonymous true
            autosave_interval 60
            connection_messages false
            listener 1883
            persistence true
            persistence_location /data

    persistence:
      config:
        type: configMap
        name: mosquitto
        advancedMounts:
          mosquitto:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
                readOnly: true
      data:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /data
