---
secrets:
  age_key:
    file: /opt/doco-cd/age_key
  api_secret:
    file: /opt/doco-cd/api_secret
  webhook_secret:
    file: /opt/doco-cd/webhook_secret

services:
  app:
    image: ghcr.io/kimdre/doco-cd:0.88.0
    container_name: doco-cd
    restart: unless-stopped
    environment:
      API_SECRET_FILE: /run/secrets/api_secret
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      SOPS_AGE_KEY_FILE: /run/secrets/age_key
      DEPLOY_CONFIG_BASE_DIR: ./docker/maulwurf/
      HTTP_PORT: 8880
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://code.offene.cloud/homelab/kops.git
          reference: main
          interval: 3600
      TZ: Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    secrets:
      - age_key
      - api_secret
      - webhook_secret
    healthcheck:
      test: [CMD, /doco-cd, healthcheck]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data: {}

networks:
  default:
    name: edge
    external: true
