---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      useListenerPortAsContainerPort: true
      envoyService:
        type: ClusterIP
      envoyDaemonSet:
        patch:
          value:
            spec:
              template:
                spec:
                  hostNetwork: true
                  dnsPolicy: ClusterFirstWithHostNet
        container:
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 81
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 444
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: offene-cloud-tls

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compression:
    - type: Brotli
    - type: Gzip
    - type: Zstd
  connection:
    bufferLimit: 8Mi
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  connection:
    bufferLimit: 8Mi
    maxAcceptPerSocketEvent: 0
  http2:
    initialStreamWindowSize: 2Mi
    initialConnectionWindowSize: 32Mi
    onInvalidMessage: TerminateStream
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 0s
  http3: {}
  #  Required for Collabora WebSocket paths with encoded URLs
  path:
    escapedSlashesAction: KeepUnchanged
    disableMergeSlashes: true
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  headers:
    earlyRequestHeaders:
      set:
        - name: X-Real-IP
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
        - name: X-Forwarded-Proto
          value: https
        - name: X-Forwarded-Host
          value: "%REQ(:authority)%"
        - name: X-Forwarded-Uri
          value: "%REQ(:path)%"
    lateResponseHeaders:
      remove:
        - "x-powered-by"
        - "x-xss-protection"
      set:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
        - name: Referrer-Policy
          value: same-origin, strict-origin-when-cross-origin
        - name: X-Content-Type-Options
          value: nosniff
        - name: X-Frame-Options
          value: SAMEORIGIN
        - name: server
          value: "UwU"
        - name: X-Robots-tag
          value: "noindex, nofollow"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: headscale-upgrade
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-external
  type: JSONPatch
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/envoy-external/https
      operation:
        op: add
        path: /filter_chains/0/filters/0/typed_config/upgrade_configs/-
        value:
          upgrade_type: tailscale-control-protocol
