---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app arr-stack
spec:
  interval: 1h
  path: ./clusters/home/apps/media/arr-stack/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-kopia-secret
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: arr-stack-config
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
