---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arr-stack
spec:
  interval: 1h
  path: ./clusters/home/apps/selfhosted/arr-stack/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: arr-stack
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
