---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
  interval: 1h
  path: ./kubernetes/home/apps/cert-manager/cert-manager/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
  timeout: 5m
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-webhook-netcup
  namespace: cert-manager
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager-webhook-netcup
  dependsOn:
    - name: cert-manager
  interval: 1h
  path: ./kubernetes/home/apps/cert-manager/cert-manager/netcup
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
  timeout: 5m
  wait: true
