---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf

spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bentopdf

  values:
    controllers:
      bentopdf:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/alam00000/bentopdf-simple
              tag: v1.15.4@sha256:ed728002dede243e99da3b5f66a88ef4aa842962d5fc1313a75ab841cc9af237
            env:
              TZ: ${TZ}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames: ["pdf.${EXTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
            subPath: cache
          - path: /etc/nginx/tmp
            subPath: tmp
