---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst-3"
spec:
  trigger:
    manual: restore-once
  kopia:
    copyMethod: Direct
    restoreAsOf: "2026-08-30T00:00:00Z"
    destinationPVC: ${APP}-1
    accessModes:
      - ${KOPIUR_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${KOPIUR_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${KOPIUR_CAPACITY:=5Gi}
    cacheStorageClassName: ${KOPIUR_CACHE_STORAGECLASS:=local-hostpath}
    capacity: ${KOPIUR_CAPACITY:=5Gi}
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: ${KOPIUR_UID:=1000}
      runAsGroup: ${KOPIUR_GID:=1000}
      fsGroup: ${KOPIUR_GID:=1000}
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    repository: volsync-kopia-secret
    sourceIdentity:
      sourceName: ${APP}-backup
    storageClassName: ${VOLSYNC_STORAGECLASS:=local-hostpath}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-local-hostpath}
