---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/home/apps/media/jellyfin/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: jellyfin
      KOPIUR_CAPACITY: 50Gi
      KOPIUR_PUID: "2000"
      KOPIUR_PGID: "2000"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
