---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
  namespace: &namespace development
spec:
  targetNamespace: *namespace
  path: ./kubernetes/hcloud/apps/development/forgejo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runner
  namespace: &namespace development
spec:
  targetNamespace: *namespace
  path: ./kubernetes/hcloud/apps/development/forgejo/runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  interval: 30m
  retryInterval: 1m
  timeout: 3m
