---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale

spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: headscale

  values:
    controllers:
      headscale:
        type: statefulset
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: v0.27.1
            command: [headscale, serve]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"

        hosts:
          - host: "headscale.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "headscale.offene.cloud"
            secretName: headscale-tls

    persistence:
      config:
        type: secret
        name: headscale-secret
        globalMounts:
          - path: /etc/headscale/config.yaml
            subPath: config.yaml
            readOnly: true
      data:
        type: persistentVolumeClaim
        existingClaim: headscale-pvc
        globalMounts:
          - path: /var/lib/headscale
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/run/headscale
            subPath: run
            readOnly: false
