---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  chartRef:
    kind: OCIRepository
    name: headscale
  interval: 30m

  values:
    controllers:
      headscale:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: v0.27.0
            command: [headscale serve]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: "headscale.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "headscale.offene.cloud"
            secretName: headscale-tls

    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: headscale-pvc
        globalMounts:
          - path: /var/lib/headscale
            subPath: data
      config:
        type: configMap
        name: headscale-cm
        globalMounts:
          - path: /etc/headscale/config.yaml
            subPath: config.yaml
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/run/headscale
            subPath: run
            readOnly: false
