apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: selfhosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:plclU01kVm9yaSt84mai1oLaa8DMZf+lII5WsBquJSyabtu/SJMwd/q2rHXQGBhUAwdIbH89rR6D2UEeq8NvffOHTdVGurZOAJnzNVhreYmmXgi3ivMHlVMISNpP9vaL7NXOf/yE9fcVnVd0eESm64zoPlMxpg==,iv:oFZJOUGlp4ecCGdVZLRniMyH4F9H3bS8Yo4N15nWHH4=,tag:RbDgSPkiFtUBlDhhnbCAyg==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:E0YP/+qv7Ex61eBaH0guUNb95aX7qPSEXqb1G+JlHmaewfdl,iv:PgNtkJ1BzFSScHIBc5Smn9tup1GCIXlzL1e58E2lu/o=,tag:jPyUDiuiDGoCEazn//dV/g==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:k7D/dnjxFKskivn9MMUc+kf2d5PQIkBJAA2z1YYxq5s=,iv:K3NIyEwNun3h/DIY5ge+0jUFA5HqaBWNUgtB+DMbC1I=,tag:wgvCBK/L2Uzztdz6E5aBfw==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:AEn9id2OGYyirQPd2GgOtoF5iFEfofI=,iv:MVdNORImy/7f523sIZWAK0jowXokW9vl4z06uta4TTM=,tag:N+4XpxhZWkQ00HmeYSNFHw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T18:52:19Z"
    mac: ENC[AES256_GCM,data:sSzv7xBXrBIiuqpEtzrEBJGnxZBBD64yz5u6RexBzXaghCOx0Bw116KSPT39ZwQg4kAcF4L8g4ob4WQx3sEIHaAfuUvoBAwfnPjrsEiVKjAGwC2+8cfVc1G0x1EpiqcPFsQM6fl+M82wQgD1p3Hl0EuTHb3NRwyBOvfV+I7Khjg=,iv:MI32B5Sd5tDTKJXQhsbw8kB7ChR7yUBFCfQF+nnenaA=,tag:eZ2XvBrItSGB367Z62vVLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
