apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: seflhosted
stringData:
    zigbee_ext_pan_id: ENC[AES256_GCM,data:5y6Z6Skm5C5nNL/AjMi/wm4bw5cJI7oSsUKv,iv:zNqWC8TixNV+HRC3XB0eL5V29zHGQx7tlTPFIExLxB8=,tag:gsDhpLSj1HivsuBc/Xqwyw==,type:str]
    zigbee_network_key: ENC[AES256_GCM,data:cbpb/p///U6HNGWLQ3HWwMke9434wS0WafiB4u1hxzCXo99HmRJNLlrqjpDSFSq+vxuEwosucQ==,iv:gYneZbjZH5pZKDdpy5vlf1vWCEwSbSmxQYb0es9NKiE=,tag:8qvwDIbAL1C0DRbT34vP3A==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:w5f7sIg=,iv:7n9PicLLWJIhD7WVu3RSUobUZuvJsiEExlv0l7havS4=,tag:Rdcw3iUMoHwWKuzrJWeKUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtBeDhNNFZF
            a000QjJzOWJqWkRGMVBNV3lzaGZUZnZvSWlORlFwQ3hwU3VBRDJvZXZOR2NLaTdX
            b3JxR2Vja1AzM09xREtLRkNpd2N4Sjlad0RyQ01mZm9YV3MwVjNYM3RVc1k5d2g5
            ZFJZWVFtZG5TMTF0Q2VYOTZmTytaeDI4MVF2Z083aEdqZWxDSWkvN2J6Y3A1SUVp
            a1g5b3RMQmg3ZCs2SjZLa1BrRi9oMGovMGRCMndoditmR1o0QU14MjlkL3Z3bHd1
            YlBGdVNteEtlZEQvSldSQmo5ZzRMcDVoNC9wZkhNd2lxZUJlZkVKWnE4TzZ3Wmx5
            ZGpIM2pvTUZud2g4MEdWaUFxRlJyV3FyUFJMdllXeUZIQnY2UDVOeUJMV3lqaXVz
            WlJjZXgvdXAySGRKbnd2akxDMURDUnVnaWxGSnE3MzRIcVdCdzkrV1JzcnRLZ2FJ
            Nkp0NUZOd1BqQVFFWGkwRE03YnBVeTZ0N053TXVnUGs1K0NwUlowbzk5N2VHdFdo
            RnNGRlpqb1c1YUR3aWlkcUhVSG9MQmhLaGJBL20yNGVrWnBtUTNEOHU3c0pSL2JB
            aDJtRkx6YkxSdnFtQm94blJqYnRYWTJ2MEF0elFQZnpHUVJkS1dhMTZyekJ2TThL
            RmlBUWV3ckEzc2dJWllrQ0pMUHE2L2ttSEZiU2liMnlHOTJXcTEyaXpjRlhEWjZE
            cXIyOW9meS9WYWtINkxXUzhpNlZxQklQbU0xNmJqeWE1bEx1b3JIRE5qZnhhU0Z2
            d2FIczhYMUo1K3crZHNWZTAwYTY1OWFobU5ndnRNVnoyZGxNM1dtc0ticXNQTDNH
            V0czditXa3pXWXY4T2tKRDZ0SDJqZU1BM3VvYm9yRGFBZUpEeExWR3NjLzdQNEpj
            TGJuRlJKWkFZSENPL2VhVVFpd2R0VGpUZDM1ZmJsRlVVQm9YdGtyMHA2VXE5L3E0
            dHdKYkUyTTh2RzhNcEdBa3AxZDNCRnRtMUFKaGN5eDhxRmlKNTNwU1VkNVRyUXJG
            VFFZaXJseWtYVGQ4Y2tiWTFDdFgrQWtSQkhCZ016RWpHL2hsVEVObkYybUQxN2dN
            WUdxSFlTSjZ1eW9XNXorbVYrTWQ5WlJMaVI4YkMxZ05TNnMrdERXTTlSYldUbDNk
            VDZQQjVoOGM0ZGluMFZrRndac0Y3VHNJN29lNmx3TFo4MVdKWkV5WWVLRTBXQkF3
            OGdkdzdkMGtkaWQrcDd1L1hSeVJnV3hWclJITHp2aERHcm9JS3p4b09BaEN4cHM1
            SS9ZNHBQYTd0VjNtekZlZGlZQzZvamhHalRBQlY4cUM4NmhuNituc01PRm5Qa3VR
            OHF6RXZIWHVWTngxYXlXc0k0NUNPVVV0d3pKQnY3T1B2Q29HVy94VnREMU9XOFdE
            Z1pVdERtd3JjMXZXdGE2am4xeHB1UUdPVEV3YkRoUHZwODZMUDFkcGVyMEdmZ3R1
            OGdQZjRCa1lJZmVzSG05bjZpcUlEQmtqWlBMVzlOSEMxUC9YWjJtd28vOU5STFRB
            WWFoZFljY1B6MW94NzhaVTFLSGlIb1JET1ZlcEtWVkI2ckZBKzFzbDlZVDFJVzVk
            dWxZU1NFU2FRdmIyY3NSMlRkdm1LOStBLzV5VitjTytXZTl3YitNeDIwTllaSjg5
            ZmFBQUdGQUV6a0tSdDNGemUzbXkzYkRqVXE1V0NwV0dMS3RUTHB6MU9VYlBlNE5P
            bEZtUy9KaUVaSlk1YTVJY0Y1K0pMVVpDdFVxekpYRHcxdlR2QU5kKzJJa3BXWHVC
            ekFGamZLQ2IzK3kydE1UK1lZM3JqdGwxN0xDSWFZRUF6SU5BZDVWM0plaldYQ1k3
            bVdLZFJiWXdXbU83L2lHWW5VTjM0ZlRXVEowOS9yS2FUb2ZqdDM0WEFkZEp5dEx1
            UnI2RXBteDNiOWpjZEszc2MzektGMEFvQmFEVjN4bG4zcUQxQm5WRjB6NmREUQpE
            Ykh4ZENhQ2FqRDYyUHJmOVZ2Q3JKM3JoRFEzWHJYR0FiNFRvK1hyL2dzCi0tLSBB
            emg0SG9ieVNvL3AxWTR2WmdMSWw2bVVYSXYyME5pVEdZOURGV1ZJeDNzCo9og8CW
            0eTqwe4g2SQtSetUdbSl/vtUaNRPCP23GA0BkU6OjGwj6PZOnLi6SGGxmHZwKra2
            qFZeQB7DZ+D8llI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T21:38:33Z"
    mac: ENC[AES256_GCM,data:tQY/sOFKVfXU5vcnZDgiEaA36J6hprTyYuB57g4s7MGZIJc9Y1oiP2w9tmJyg01jKPHlKvdjvzPu52Pw0eBo0+ttKUSgJ7GAOmMB3MneNqb2lynCQc/+qiMzPfug+NkMq1+8gT26+jMldMKwz+8BuXSm3ZSHEap+HdQ0XKOyrvc=,iv:5FlAcU/nBS0iNLmzZf8DporThKMZaN6AtakARv9cjEo=,tag:Q1slNtXPMW9DXbrsaarEGg==,type:str]
    version: 3.13.3
