---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
spec:
  interval: 1h
  timeout: 5m
  wait: false
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  path: ./clusters/home/apps/volsync-system/volsync/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync-maintenance
spec:
  interval: 1h
  timeout: 5m
  wait: false
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: volsync
  path: ./clusters/home/apps/volsync-system/volsync/maintenance
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
