---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo-runner
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      forgejo-runner:
        replicas: 2
        initContainers:
          runner-register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 11.1.1@sha256:e435bb347f07ae0d1ed580afd993105e2470af83b3e9af3495ac6dcce7972f28
            command: ["sh", "-c"]
            args:
              - |
                forgejo-runner register --no-interactive --token $(RUNNER_TOKEN) --name $(RUNNER_NAME) --instance $(FORGEJO_INSTANCE_URL) --labels self-hosted:host,docker:docker://ghcr.io/catthehacker/ubuntu:act-24.04,ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-24.04,ubuntu-24.04:docker://ghcr.io/catthehacker/ubuntu:act-24.04,renovate:docker://ghcr.io/catthehacker/ubuntu:act-24.04 ;
                forgejo-runner generate-config > /data/config.yml ;
                sed -i -e "s|network: .*|network: host|" /data/config.yml ;
                sed -i -e "s|^  envs:$$|  envs:\n    DOCKER_HOST: tcp://localhost:2376\n    DOCKER_TLS_VERIFY: 1\n    DOCKER_CERT_PATH: /certs/client|" /data/config.yml ;
                sed -i -e "s|^  options:|  options: -v /certs/client:/certs/client|" /data/config.yml ;
                sed -i -e "s|  valid_volumes: \[\]$$|  valid_volumes:\n    - /certs/client|" /data/config.yml ;
            env:
              - name: RUNNER_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: RUNNER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: RUNNER_TOKEN
              - name: FORGEJO_INSTANCE_URL
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: FORGEJO_INSTANCE_URL
        containers:
          daemon:
            image:
              repository: docker
              tag: 28.4.0-dind@sha256:2ceb471176ad51e37145d43ce7cbf0fa5d644a2b185bd537f0ef695fb3a37497
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 11.1.1@sha256:e435bb347f07ae0d1ed580afd993105e2470af83b3e9af3495ac6dcce7972f28
            command:
              [
                "sh",
                "-c",
                "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /data/config.yml daemon",
              ]
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "0"
            securityContext:
              privileged: true
        annotations:
          reloader.stakater.com/auto: "true"

    service:
      app:
        controller: forgejo-runner
        ports:
          http:
            port: 45315

    persistence:
      docker-certs:
        type: emptyDir
        globalMounts:
          - path: /certs
      runner-data:
        type: emptyDir
        globalMounts:
          - path: /data
