apiVersion: v1
kind: Secret
metadata:
    name: towonel-hub-secret
type: Opaque
stringData:
    TOWONEL_HUB_KEK: ENC[AES256_GCM,data:cWCHMaAKGFIr3+HnlvSmUDMr9bqCNy9XnRLzYUrju+dh8/dxN4/tBi6BOJXbLbl8K9+by/cdHdauCj0w6q//TA==,iv:MqX4S/39n4DCSfOJ0wGNuPZlE5+ljOrMWeBN0WqinH0=,tag:ZBBbtUVxHnSurOWVlzDUmA==,type:str]
    TOWONEL_HUB_LINK_PSK: ENC[AES256_GCM,data:p0RwG9U/wolH+Uw9GBdlNd/p1B6DbLYJQHeIIdcpU/FDhqHoG3pCPxt4jym6jrBolb7rAemqtYhdYw+t6HiIoA==,iv:M5Ky2ArMsQSpTfUafNWN6KsS1lrVb71Uz6lfjyBDPOw=,tag:ZGr4RVE3BCHF0hcf9+f9BA==,type:str]
    TOWONEL_INVITE_HASH_KEY: ENC[AES256_GCM,data:cSi1pUmDtRu38roOMd9C2wtJiv6g91T7Ml50gANxnTl/ApxB6MQ7kcvwzsJ30zuO+HbNFloO13rnZGAz9PgSPg==,iv:LU6s11B8gS113dmVyn+lWc/j9Y1CJijG7llTkfonDIU=,tag:rTQn0bKx+3zrQQt9xMRHaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOVJ0YjJNd09JVUFRME1W
            RE8xVE1CbXFhcDBRam1OSllNWS9GZDhzdW04CkFxVi9YdHRyZ1ZNbjRER0JyTThT
            cWxyNjhDNGxKK01DQjlZSWphOWt3SzAKLS0tIFJRbkV5UmpoQWowYW9QQ0huakw0
            WERlYmxwdlZ6ekxyT1l0S0puWUxjbVUKkKzxjOIOaidUa2r59vxt+8/allp/G2Zo
            ShI6c2kyR1fEJ/q2kMk8t/WeOh3/9IRCrh7pIVzFm1kvtrt9N63wJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T12:13:37Z"
    mac: ENC[AES256_GCM,data:Yf6MY6EmvzURbW5ozxhItgUlJIfZ+zjGhuIX+obXYntPOXCjW2lRLOlnl5C348AyE6nDHsDo2spITfhuKabyxYVuUF87MXRu9Kd6aiKPemtT0HpB19AwlVSbEUQMuF5XHJkQWroD4y3TG6Vd3Oepi5LVR3tjw38oq/CpVKDErJw=,iv:O2oC1D7Cb7EdcnXY1ej5aYkG18gwDNP4Y/l4qJOEFiY=,tag:Gn5COICTyOp3tGTqEotCqg==,type:str]
    version: 3.13.3
