---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      enabled: true
    dns01RecursiveNameservers: "185.12.64.1:53"
    dns01RecursiveNameserversOnly: true
    cainjector:
      replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "185.12.64.1"
      - "185.12.64.2"
