---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-netcup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager-webhook-netcup
  values:
    groupName: com.netcup.webhook
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    image:
      repository: ghcr.io/aellwein/cert-manager-webhook-netcup
      tag: 1.0.49
      type: ClusterIP
      port: 443
