---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 30m

  values:
    controllers:
      forgejo-runner:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: Recreate

        initContainers:
          daemon:
            image:
              repository: docker
              tag: 29.9.0-dind@sha256:0b6d18a4a222e71c88be6034926b4f6cde2fc33c2218643d03ccfddc65995470
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 2
                  tcpSocket:
                    port: 2376
            restartPolicy: Always
            securityContext:
              privileged: true

        containers:
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 13.2.0@sha256:ca3d5eea46004789a175d1369eec6829d3ea9bfbe2011a06625b4bdaa55f7552
            command: ["forgejo-runner", "daemon", "--config", "/config/config.yml"]
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"

    persistence:
      docker-certs:
        type: emptyDir
        globalMounts:
          - path: /certs
      config:
        type: secret
        name: forgejo-runner-secret
        advancedMounts:
          forgejo-runner:
            app:
              - path: /config
                readOnly: true
