apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: development
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:1J+dwn20E0+SZG+VNxewEPcUmKTwWZePh82Sn47HZbE8HEoLhizWxyavVzgnHrDEqDlwkLxP/QoHU0vj+NezgPW9NU3Oe7g8WHJKlQPAeurlgUT+LVUpVGzd4bKOPiJqWvt0aKoqNHneOurMTl5sdLtzjtx2cQRF/Ce7hhVPgxh6Jk/KwTadeOwJ8RQ5uJj1oi1owCvn7MLsnku41puQ5XUgk/xGKListNW+jxC+itoyR12Qu5mdPIlNhsG0VEpQgDAa5N8MIFDhqoIWmNXsEv45U56M0wJ3QG8KiyyaFUoe365R7OQlqhYILzmM/fmt+vEL6/04WMNMRX7i5F9IerMRXDO2WjnGAOl5/2uS524TJ/f9dwDpb1LtUvpciT6NOpXrlhLWLApsdTdbjalzSh25uvmhGNlxfbr7+lTVD6T851BNWR9gXVt9qh7PkDjCov7kvguxNrz39hJapKOpW3YJFXwz5JOOTe2prrRzroBT9Dwo2xi93626v9yP3HJkOWyXy96J1mI6WHw3ouRTuKEsK8eJW4ZPdQvEQRFKYeYjsyIVR/CZwC9hB3cKfx6R3dH73Qew8cyo4szRL7HnI7cQ4qYPcWpa2rNIsNcqWCiIzJE/8UIaPVMU794kwqVeoTBa2CJM2jRW5NshXxJN55Td3RqVCJLuS9DjB9T4+xxJfg/CWPD49fetwrHp02+9A6hD5QpzD3UDyvwsHiqZPcy5IPUCie1KkvLSNdmag5IwOVWvylb//5Jdk3HMHqeFhMFbeyu12b0lvQIF57h1HIeFUOPMAjLX+eezWqqi5M8CCDV+8q6iGqkVODu6J1I257Rv2CE/DNsJI4MINqcmKgHkRctXAKaL7wPHCq2bq/DMVuj9soPeEoaC459SLbUDej3cmaQAAFu35r2T+SUt2rFwEtsc63DZIFWd5k8bYN8mXiMt32JCG27LlegGYF/D5CdVCwOVCVqUlweBE7XUnQ2W,iv:rBDNRYeA6j2j6dHkXvcm2LntR0zHkc8vqvHBnfpC69A=,tag:QpnyI0GZiIeJpqCxdr/Pbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbkl6eFlsODFhTHJ3V0pU
            WmdwM0F3d2tNemxvb2NoZFJ6R3c0Y1dINlVFClBqWGJocEtkLzhWeVk5dWFVZjM3
            RXNJVzZjMkxHVHZCcGNGUHhMVmY2R2MKLS0tIEFmbXg5alR3UStCTWR6STVybEw4
            alp2eU9CVHFCYjJLcUZJUUJKdnBtdHMKIFE3H517FwlGAF/eGw7K9S3tU+nK2S7c
            oUCgWODx0FqGi1IVeEYzIs0e3NO0zsDWq5SwTVDzJ0lMpx7rUER0Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T20:18:27Z"
    mac: ENC[AES256_GCM,data:8st/B5VDZfWhT3niy3JUPY36BCFWOVd7Fb1InN7aHCzz14+lJ7dXghGFb3z9rY1dy1Ydthhzb7S1eS96YL9ZRR76WHQ/B/6d+zl+5zjoTvh3nhIFdGdCZjfLkFn7vrjIk19PeZA1JFMxwrcRBu61JqC7LwzlRlc062CWqYBEVVQ=,iv:Wsbf9y6oS0/DrlbFLz4NPVrg41kjB+ALTnHOefrmC8c=,tag:zu3m9ddVfhGhuQYQug59pg==,type:str]
    version: 3.13.3
