---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mollysocket
spec:
  chartRef:
    kind: OCIRepository
    name: mollysocket
  interval: 30m

  values:
    controllers:
      mollysocket:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/mollyim/mollysocket
              tag: 1.6.0@sha256:f5659c534cef45809f310757878b2ae51db7f57df150acc2711d7bc5a87d99c4
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            args: ["server"]
            workingDir: /data
            env:
              - name: TZ
                value: Europe/Berlin
              - name: MOLLY_ALLOWED_ENDPOINTS
                valueFrom:
                  secretKeyRef:
                    name: mollysocket-secrets
                    key: allowed_endpoints
              - name: MOLLY_VAPID_PRIVKEY
                valueFrom:
                  secretKeyRef:
                    name: mollysocket-secrets
                    key: vapid_privkey
              - name: MOLLY_ALLOWED_UUIDS
                valueFrom:
                  secretKeyRef:
                    name: mollysocket-secrets
                    key: allowed_uuids
              - name: MOLLY_DB
                value: "/data/mollysocket.db"
              - name: MOLLY_HOST
                value: "0.0.0.0"
              - name: MOLLY_PORT
                value: "8020"
              - name: RUST_LOG
                value: "info"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: 8020

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: "molly.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "molly.offene.cloud"
            secretName: mollysocket-tls

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: mollysocket-pvc
