---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
spec:
  interval: 1h
  timeout: 5m
  path: ./clusters/home/apps/selfhosted/home-assistant/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-kopia-secret
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: home-assistant-data
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_GID: "2000"
      VOLSYNC_UID: "2000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
spec:
  interval: 1h
  timeout: 5m
  path: ./clusters/home/apps/selfhosted/zigbee2mqtt/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-kopia-secret
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: zigbee2mqtt-data
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_GID: "2000"
      VOLSYNC_UID: "2000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
