---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: jellyfin
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.2@sha256:749972be6e7d440a47531ee36c9e38ea7a6271c875f42e8a52851c39862b0773
            env:
              TZ: ${TZ}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 8Gi

        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: jellyfin
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "jellyfin.${INTERNAL_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: jellyfin-cache
        globalMounts:
          - path: /config/metadata
      media:
        existingClaim: media-nfs
        globalMounts:
          - path: /media
            readOnly: true
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /config/log
                subPath: log
              - path: /tmp
                subPath: tmp
