---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-hostpath
