apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TuRwWgtNMU3tPDICEFQv8GGVFkl3RDYeQQfNCI8tFbSL5fje8nmle0wRzJgFs7AC1I5vQlNfrxan0E08kFRExNW4QHnRtBJQfq94KZ4qXcNnMPblOqeZaUGexyhoyjr0qcNHkKISHn44/KHUr/jyPdSgWljBWQ==,iv:5XK/Ng1QDJD+NmeZOHzH2o1AriwJ2PH0sUQ9LYQWpFc=,tag:BsIZoWTfhvLNHPgvC9pYvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZvgOfjNXRl6g6sWvU4wM25VKrYGVHp1sZBigxgh4BuwDVxGGT2cSSGjgyRAYq00a28OvE8PMx0PotET6O24DTw==,iv:/WQ8pw9O5lOLFQ1vCIWTe2fm8r6HNhS5m+/trj1i2Xk=,tag:7GszC7lFZBKCMPtWbgSREQ==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T20:06:23Z"
    mac: ENC[AES256_GCM,data:UEmqyad2C0HBt37kUV1wEUMAc1bEC981f+tvSHNBGvP+3l+XtmX/GDqFWg0UVa23rcSjPPqu96nef5X9wGEQMsIJX4R7fpGIIXAseAU2UNGwMny03WjWdtF7RcR1OOc+E8g8TRns7J/IaFIPTmGFKVr8W9h6PeLciZc7eLUTcDo=,iv:1xFOwVPHmNus8Ddyd/hpZlM8CgoS1S5kilhmW4GuL08=,tag:D/J9UQsZcxboebHb2MsQHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
