apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TuRwWgtNMU3tPDICEFQv8GGVFkl3RDYeQQfNCI8tFbSL5fje8nmle0wRzJgFs7AC1I5vQlNfrxan0E08kFRExNW4QHnRtBJQfq94KZ4qXcNnMPblOqeZaUGexyhoyjr0qcNHkKISHn44/KHUr/jyPdSgWljBWQ==,iv:5XK/Ng1QDJD+NmeZOHzH2o1AriwJ2PH0sUQ9LYQWpFc=,tag:BsIZoWTfhvLNHPgvC9pYvA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T16:28:19Z"
    mac: ENC[AES256_GCM,data:3faMTygWIIGgFxxJ1RpXi9Ke9mZwOB8ce31RzbeFE8sTDTiSWe1VBg8Bji59XAEP48538hM9fE9frQjDaK9qM2MuPEnfa2F+5jCty75kZYHrKc8xaBNH4fdzuOQyvJrercKtfkKFdvpAec6tbki3LINzmdw4MF8rj4B7AEawiT0=,iv:LzXmopA9BBONVBRZQo6iB7KYPalvlyWFfZfmggaFSy0=,tag:qmz+BqE1yYhgQ9apaRmHhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
