---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
type: Opaque
stringData:
  KOPIA_REPOSITORY: s3:https://${S3_DOMAIN_EXTERNAL}
  KOPIA_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_S3_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_S3_SECRET_KEY}

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-backup
spec:
  sourcePVC: ${VOLSYNC_CLAIM}
  trigger:
    schedule: "0 17 * * *"  # Daily at 5 PM
  kopia:
    repository: volsync-kopia
    username: ${APP}-kopia
    copyMethod: Snapshot
    compression: "zstd"
    cacheCapacity: ${VOLSYNC_CAPACITY}
    volumeSnapshotClassName: csi-local-hostpath
    cacheStorageClassName: local-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: local-hostpath
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID}
      runAsGroup: ${VOLSYNC_GID}
      fsGroup: ${VOLSYNC_GID}
    retain:
      daily: 7        # Keep 7 daily snapshots
      weekly: 4       # Keep 4 weekly snapshots
      monthly: 12     # Keep 12 monthly snapshots
