apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: media
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R72PtYk2wA==,iv:rlafMDCdc/V5gQBnNeRjamOxSW3a2kNH/rjkCl4hkMY=,tag:bWvd0fdZa9DZHrHaXpBqDA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:Umu6e9vgrjo+,iv:btg2P4ub/V1Ue34ZPwxUYHYnd0HnFX3Yd8eM4MZBkuE=,tag:cXq4blXGHTTRO7KCG1bhsQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:2PXjFxm0lFn5GxhLqrUWGsQhQZtTHZIFFxXpO4pv2lVBNuGpv/IfkwcEV/M=,iv:Y6WmBRi2W6pEDWCAcvtU6U7uDe9fYB1xU6Qp6zVpxSs=,tag:zZDpWd373dNe/e5JF5OWzQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:VJEqqOCuNtoGjKRPbk0Mog==,iv:LF6Nipt7ILxt6JWcN12nXTzNbjfghWugPp30ilxjzUM=,tag:wNLv8yQiaXwn3lQU1BYONg==,type:str]
    OWNED_ONLY: ENC[AES256_GCM,data:jT/0,iv:IABX50+xbuqWw9DB9QrLatkhwOd//qsRRBngVIW35fI=,tag:+Ny/FzuxhwwvPYOUUMQh3Q==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:+X2PXl8fJ9+NjHg=,iv:yFICb9FvqFNdLp0eJDCQYSwweR4YVdq2nHnnawmxCuU=,tag:110QMk0hVMX9QaLlQ/uaMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERoNHhPRUla
            UFQwaWVRTmVuM2drQk02S0xnR1g1aEo5WUZ5aEVnK1lMM0NpZGNISHFMb3U3dGdO
            RFEybHBya1NPbWVpaWo2MUdreVhhWFE2ajRWay95T2ZmdXNoaHlyc29vNG9GVmR3
            VjNBT0I5RVRkRFlzUkRaQjZCQVdsSjEzWnpXSnFUcW9hWDRJRkpxdWVqMVBqOXFl
            REhCSExGS3NsNGd0VDFsbkcrYlBMRi80NkFnbjdoSFJQWG0vZDZSNmhaWlIyVm9U
            RTVTOE5RcFA3UmpMeGpBS2VrVzRham1iS0VBVWtOVlNPd3Z4MlJZd1pYUnkySW1m
            aStYYWJpeFNNMUlPTzFsRjk0TDRNODBEWk51YlJjaDFBYzByUDY0U3BVNlhtNklz
            ZTBKbURybEVyQVU1N0MzT1k3d1Q3R2p6Zmd3OFoyZ2w3SkZLbklOekV2NHlESTFP
            U20xU2RldjRnbHhGTkxxc0t4TzNHaG5Sc01iOW85K2VtOC81VjdPL0hhMkFCL0l1
            czdUWHk2YlFlR1ZvamJJS29tOW5OQThLZVIybzZHRjRRbmJzY3k1Zm9BZ1FhMjJu
            TWhROWF0Nlo3T2QrQ21adzNCRjhvZzBEbEFGUUdaT2xMbjQ4Q1F5QTFpMVArU3hC
            VGJ2bTBBV0dxNThTb251UUlSZWVKblhRc2UvUE1Cczd6bnlHckpXY2JKTWdvWXR3
            R3NsTGRBNlFoQXYza2pmN2l2TjBsV0JWOFlwUForc0FvSzRVaVNYTlB2ZENtTXFH
            ZHczOUVkNXJ0blNzamFzdXNtb01tanl0a0xRdTZnQm1Ha3hsdWFkdk16N0tTbFll
            ZDFGS1h4WGtmTGZsbzg1YjFWaUtqc1dmNVVYZGJIMVoxR0ZCM3Jwd2doa0FWT2hB
            ZWVGQWhTbDJqa1Fld0FRUmFzVnJtRXozS0k0SThoMWNVb1M0ZjI1MjFhSHl1dEYx
            dFVRcEtGOTdkZkh4d2VWUFB5NS9xRGdYdmxUWUQ0UCtReTgzcWY4UXB1SUlGSEpF
            N2dlNWo3OHowd0VvYlR0MFkwUUdiTEE1VDU5eTU4TmsyWXZ6T3l4RVY5bVJRdFRI
            Z1J5NFFaVlZQdGxrTlpaWHVPVUdHZWF0WXZkb3pxd0ViWEdCVG5QVGUxcFZTNlAv
            cnVua0lkMUljdE4wVnVjcjRBbDFiSFZ0Sld6K2YvYzlJWGNBZG1mNWhTM09EcmRH
            WnJJYmEzVVZNRlZCdFdUS3ZOY0xTdG5BMjdJR1Y4OW5aak1icGZxS1JCQkg4T0sy
            cFJxbTNkK2V5NWwrWjVNblQ0ZGpOK3RDeVlkSzFNRGtTam9DYjd5U3VrVXBvRlJ2
            blNQR0QvdHNHWDhjcW5sa09NSHlFYzJ1QWg5L0hpQmo5R09LUzJ0QzZ2Z1NnVnpN
            VUhET09BWjQ4dHhNWkI2UTJudlppUkVTdE9qMWdtYjlPdmdFNnczZU1paVF0UGxv
            SzdPV0ptWFhodVRCYm90dzhGcUoxdHZVQncrK3VuT2hQNWtOTjFqRlAyV3l6K2Jj
            SjY4N3krYUVqSDk1WExHN3EwZVJUeEFsWEFiZ0FsbEhjdUY2emh2VGhDRmhGdis3
            aTZTdkhmU1pjcVlmZjVBQU5SK2tnZ2FtZC9TZWNENGdHcjlmY3oyVUtjR0R2Zjdh
            K1dMbVgwZ3k3c1grSzk5MXA0d1VvZy85NUkzUlgyRHlabm1GMTR2VkVzckhIYzI3
            K2d2ZE5oanRzYXdwbXBpR3JHS2ZmblhYMGZXOEpmTStQS1hpeEpLSS9sQzl4N0V1
            cVVLVzg5NE4yV2czWmpIQUczaWh6S0MwTWZCZXhzMkd2eXlOY0d5UGVwTGptL1Nk
            Uk1jNTFteEJYL1FKRkJCaWU3eHRiWU5pbXBEZXQ5eFF3TUdpTmwrb3pzOEdZYjJy
            SlJuMG42emkxbzRjZGxEdG45VnFHZXVjSm9vejlPLzM0QjJ6NGo2aUZUdkJQUQp6
            THZGUGlkOUR5ajIvS1YvQjViU3MyWlZBN3VlTUY0S2xhREx4eFphYmVnCi0tLSB1
            NXIrUUU2ckN5QTBlNnEyMTNLcTErQ2ViWkhBc1BTa0U0V1dZL2gwaGNNCmdz9COq
            4cbbo2FiieLNbNddyiFYKSUvcPyIz4fv/cTeCgz9r0jRU5hN4Kw2ts2yAVb4O98r
            uZhsPlD/s4OORhs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-19T23:32:31Z"
    mac: ENC[AES256_GCM,data:1UTOHyXWSOkp+/UKb1a8bivVO9clEi2eQEGMN7ztV94W6AR4riP8vwc8DE7+FLBnkXPszisurufYXjQUMpC16WlgJxBlli41py6Fy6UcyaYwiwKzm4DIjYQjN6xIEDouAX+eZiGFaa3J2UbZUK8tPJxd8cm8FBKXeWjcYsg5eZI=,iv:1NQkoGmZ5hUnX/I+joJUsexA5ogBYvElSra2QRAX+j4=,tag:xBWSXht8kI0f0Esv34TKeA==,type:str]
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:osJoJSVA2oXGVx9S7fA/hTDs20EGP0AVZkcslucI+UzLpbsV,iv:SpuofUyymYnq+6AfBpUCjZMu66KOlugnksGATM4MMPQ=,tag:7Wvm/ZpZAtYGjnQxxJCM3w==,type:str]
    client-secret: ENC[AES256_GCM,data:Cx8Qq1sS5i4mtKILmrVvVOFQn7xHBEkcgY4Ak+9OjmQ=,iv:BW733ipTbQ6vAOqG27sFGyIzOF7bqz4pLG2kDDweMbc=,tag:7Q1mWK3V1AGp2CE/9KBM5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERoNHhPRUla
            UFQwaWVRTmVuM2drQk02S0xnR1g1aEo5WUZ5aEVnK1lMM0NpZGNISHFMb3U3dGdO
            RFEybHBya1NPbWVpaWo2MUdreVhhWFE2ajRWay95T2ZmdXNoaHlyc29vNG9GVmR3
            VjNBT0I5RVRkRFlzUkRaQjZCQVdsSjEzWnpXSnFUcW9hWDRJRkpxdWVqMVBqOXFl
            REhCSExGS3NsNGd0VDFsbkcrYlBMRi80NkFnbjdoSFJQWG0vZDZSNmhaWlIyVm9U
            RTVTOE5RcFA3UmpMeGpBS2VrVzRham1iS0VBVWtOVlNPd3Z4MlJZd1pYUnkySW1m
            aStYYWJpeFNNMUlPTzFsRjk0TDRNODBEWk51YlJjaDFBYzByUDY0U3BVNlhtNklz
            ZTBKbURybEVyQVU1N0MzT1k3d1Q3R2p6Zmd3OFoyZ2w3SkZLbklOekV2NHlESTFP
            U20xU2RldjRnbHhGTkxxc0t4TzNHaG5Sc01iOW85K2VtOC81VjdPL0hhMkFCL0l1
            czdUWHk2YlFlR1ZvamJJS29tOW5OQThLZVIybzZHRjRRbmJzY3k1Zm9BZ1FhMjJu
            TWhROWF0Nlo3T2QrQ21adzNCRjhvZzBEbEFGUUdaT2xMbjQ4Q1F5QTFpMVArU3hC
            VGJ2bTBBV0dxNThTb251UUlSZWVKblhRc2UvUE1Cczd6bnlHckpXY2JKTWdvWXR3
            R3NsTGRBNlFoQXYza2pmN2l2TjBsV0JWOFlwUForc0FvSzRVaVNYTlB2ZENtTXFH
            ZHczOUVkNXJ0blNzamFzdXNtb01tanl0a0xRdTZnQm1Ha3hsdWFkdk16N0tTbFll
            ZDFGS1h4WGtmTGZsbzg1YjFWaUtqc1dmNVVYZGJIMVoxR0ZCM3Jwd2doa0FWT2hB
            ZWVGQWhTbDJqa1Fld0FRUmFzVnJtRXozS0k0SThoMWNVb1M0ZjI1MjFhSHl1dEYx
            dFVRcEtGOTdkZkh4d2VWUFB5NS9xRGdYdmxUWUQ0UCtReTgzcWY4UXB1SUlGSEpF
            N2dlNWo3OHowd0VvYlR0MFkwUUdiTEE1VDU5eTU4TmsyWXZ6T3l4RVY5bVJRdFRI
            Z1J5NFFaVlZQdGxrTlpaWHVPVUdHZWF0WXZkb3pxd0ViWEdCVG5QVGUxcFZTNlAv
            cnVua0lkMUljdE4wVnVjcjRBbDFiSFZ0Sld6K2YvYzlJWGNBZG1mNWhTM09EcmRH
            WnJJYmEzVVZNRlZCdFdUS3ZOY0xTdG5BMjdJR1Y4OW5aak1icGZxS1JCQkg4T0sy
            cFJxbTNkK2V5NWwrWjVNblQ0ZGpOK3RDeVlkSzFNRGtTam9DYjd5U3VrVXBvRlJ2
            blNQR0QvdHNHWDhjcW5sa09NSHlFYzJ1QWg5L0hpQmo5R09LUzJ0QzZ2Z1NnVnpN
            VUhET09BWjQ4dHhNWkI2UTJudlppUkVTdE9qMWdtYjlPdmdFNnczZU1paVF0UGxv
            SzdPV0ptWFhodVRCYm90dzhGcUoxdHZVQncrK3VuT2hQNWtOTjFqRlAyV3l6K2Jj
            SjY4N3krYUVqSDk1WExHN3EwZVJUeEFsWEFiZ0FsbEhjdUY2emh2VGhDRmhGdis3
            aTZTdkhmU1pjcVlmZjVBQU5SK2tnZ2FtZC9TZWNENGdHcjlmY3oyVUtjR0R2Zjdh
            K1dMbVgwZ3k3c1grSzk5MXA0d1VvZy85NUkzUlgyRHlabm1GMTR2VkVzckhIYzI3
            K2d2ZE5oanRzYXdwbXBpR3JHS2ZmblhYMGZXOEpmTStQS1hpeEpLSS9sQzl4N0V1
            cVVLVzg5NE4yV2czWmpIQUczaWh6S0MwTWZCZXhzMkd2eXlOY0d5UGVwTGptL1Nk
            Uk1jNTFteEJYL1FKRkJCaWU3eHRiWU5pbXBEZXQ5eFF3TUdpTmwrb3pzOEdZYjJy
            SlJuMG42emkxbzRjZGxEdG45VnFHZXVjSm9vejlPLzM0QjJ6NGo2aUZUdkJQUQp6
            THZGUGlkOUR5ajIvS1YvQjViU3MyWlZBN3VlTUY0S2xhREx4eFphYmVnCi0tLSB1
            NXIrUUU2ckN5QTBlNnEyMTNLcTErQ2ViWkhBc1BTa0U0V1dZL2gwaGNNCmdz9COq
            4cbbo2FiieLNbNddyiFYKSUvcPyIz4fv/cTeCgz9r0jRU5hN4Kw2ts2yAVb4O98r
            uZhsPlD/s4OORhs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-19T23:32:31Z"
    mac: ENC[AES256_GCM,data:1UTOHyXWSOkp+/UKb1a8bivVO9clEi2eQEGMN7ztV94W6AR4riP8vwc8DE7+FLBnkXPszisurufYXjQUMpC16WlgJxBlli41py6Fy6UcyaYwiwKzm4DIjYQjN6xIEDouAX+eZiGFaa3J2UbZUK8tPJxd8cm8FBKXeWjcYsg5eZI=,iv:1NQkoGmZ5hUnX/I+joJUsexA5ogBYvElSra2QRAX+j4=,tag:xBWSXht8kI0f0Esv34TKeA==,type:str]
    version: 3.11.0
