---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: continuwuity
spec:
  chartRef:
    kind: OCIRepository
    name: continuwuity
  interval: 30m

  values:
    controllers:
      continuwuity:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: v0.5.0-rc.7
            env:
              CONTINUWUITY_SERVER_NAME: chat.offene.cloud
              CONTINUWUITY_DATABASE_PATH: /data/db
              CONTINUWUITY_MAX_REQUEST_SIZE: '104857600' # in bytes, ~104 MB
              CONTINUWUITY_ALLOW_REGISTRATION: 'true'
              CONTINUWUITY_ALLOW_FEDERATION: 'true'
              CONTINUWUITY_ALLOW_CHECK_FOR_UPDATES: 'true'
              CONTINUWUITY_TRUSTED_SERVERS: '["matrix.org"]'
              CONTINUWUITY_ADDRESS: 0.0.0.0
              CONTINUWUITY_WELL_KNOWN__CLIENT: https://chat.offene.cloud
              CONTINUWUITY_WELL_KNOWN__SERVER: chat.offene.cloud:443
            envFrom:
              - secretRef:
                  name: continuwuity-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"

        hosts:
          - host: "chat.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "chat.offene.cloud"
            secretName: continuwuity-tls

    persistence:
      data:
        existingClaim: continuwuity-pvc
        globalMounts:
          - path: /data
            subPath: data
