---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: configarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: configarr

  values:
    controllers:
      configarr:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        cronjob:
          schedule: "0 17 * * *"
          timeZone: ${TZ}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          app:
            image:
              repository: ghcr.io/raydak-labs/configarr
              tag: 1.19.0@sha256:dd7f44d10f6705f7c1d8cd03f3edf8a5c6390482d0770785f36dbf93df435869
            env:
              TZ: ${TZ}
            envFrom:
              - secretRef:
                  name: configarr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    persistence:
      config:
        enabled: true
        type: configMap
        name: configarr-configmap
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
      repos:
        type: emptyDir
        globalMounts:
          - path: /app/repos