apiVersion: v1
kind: Secret
metadata:
    name: configarr-secret
stringData:
    #ENC[AES256_GCM,data:lrNTa5blBGA9shID8mEMKNaW,iv:uVSceVc9b38vZ3JSykVY1pKjGowrpvn4oqb1LhU4Rzw=,tag:AkBVYTyURiTV9dnhlkpZHA==,type:comment]
    SONARR_API_KEY: ENC[AES256_GCM,data:hxpEcRTyN0Ex7otff0IwBgM/FEE/mXXVJceNHgIph+A=,iv:UaL0Zc9L0qvQLyc1+/6UIhFFLP3f8TDPpcCr33/yQUo=,tag:3egomnjqx6QEd0ITXedXBg==,type:str]
    SONARR_ANIMES_API_KEY: ENC[AES256_GCM,data:T0qqJAQiSP3uRZfXIA0DdV/Vu0yRvOGmwwgbHCARbLE=,iv:h9CbTeGanqnnatOTAmEBPBaVhZgw0GJrNkYiRbW0940=,tag:C8i/6s/4PN9JHLHBHushHA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:13:00Z"
    mac: ENC[AES256_GCM,data:kSi9ss3AOEQ+0/HiPEblSxPNPprMALDe/ijGh/KnORHFaEfhR6FcQrpe7wY3Wv89ro4gEl7eWu2p1OsyRoyf4dGpKnRNCkvrbALN09zY8aU79+4hk7dVnMzx9l/PEdcaCKfWh2gsaCM9zJQbSYzMtdKyPvSXxhQ+/a1sQhNMhv0=,iv:cojwh4BkIqJbRfXI5VN1ghY2nceKMT1ozt0EAIblAdM=,tag:ntCzlnmSmv7RvZdRmdkfhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
