apiVersion: v1
kind: Secret
metadata:
    name: configarr-secret
stringData:
    RADARR_API_KEY: ""
    SONARR_API_KEY: ""
    SONARR_ANIMES_API_KEY: ""
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T00:41:11Z"
    mac: ENC[AES256_GCM,data:9Dww5O2nrr5vbZVgsEoJA82E639B/isWj+AuBUrtolXHSvn4gRZ571Msdh6b/BrjISiuOzww7vO4SR2nPyhtmSrxCZD/+0f0FJKq6MptCCp38CRrU5M+FuAqK/FCJ9idssU3TJOb2xzh4kZqcGbM9RmMi1hc3ySQTEOMJeRlitA=,iv:TNKsZ5uu2VMXCHVPBwcQvOAEMTd0p7Ewv86GHqMYotQ=,tag:7ljRPeMlubUVaPic6PVrxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
