---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
spec:
  components:
    - ../../../../components/dragonfly
  dependsOn:
    - name: litellm-operator
      namespace: ai
  interval: 15m
  path: ./kubernetes/hcloud/apps/ai/litellm/app
  postBuild:
    substitute:
      APP: litellm
      DRAGONFLY_REPLICAS: "1"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
