---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: immich

  values:
    controllers:
      immich:
        forceRename: immich
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${VOLSYNC_UID}
            runAsGroup: ${VOLSYNC_GID}
            fsGroup: ${VOLSYNC_GID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1
            env:
              TZ: ${TZ}
              DB_HOSTNAME: immich-postgresql
              DB_DATABASE_NAME: immich
              DB_USERNAME: immich
              REDIS_HOSTNAME: immich-valkey
              IMMICH_LOG_LEVEL: verbose
            envFrom:
              - secretRef:
                  name: immich-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 6Gi

      machine-learning:
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
            env:
              TZ: ${TZ}
              DB_HOSTNAME: immich-postgresql
              DB_PORT: "5432"
              IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
              DB_DATABASE_NAME: immich
              DB_USERNAME: immich
              REDIS_HOSTNAME: immich-valkey
              REDIS_PORT: "6379"
            envFrom:
              - secretRef:
                  name: immich-secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 6Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true

      valkey:
        containers:
          app:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.1
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec: &probe-exec { command: ["sh", "-c", "valkey-cli ping | grep PONG"] }
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  exec: *probe-exec
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  exec: *probe-exec
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30

      postgresql:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/postgres
              tag: 18-vectorchord0.5.3-pgvector0.8.1
            env:
              POSTGRES_DB: immich
              POSTGRES_USER: immich
              POSTGRES_PASSWORD: ${DB_PASSWORD}
              PGDATA: /var/lib/postgresql/data
            envFrom:
              - secretRef:
                  name: immich-secret
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1024Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      immich:
        controller: immich
        ports:
          http:
            port: 2283
          metrics-api:
            port: 8081
          metrics-ms:
            port: 8082
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379
      postgresql:
        controller: postgresql
        ports:
          postgresql:
            port: 5432

    route:
      immich:
        hostnames: ["photos.${INTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: immich
                port: 2283

    persistence:
      immich:
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          immich:
            app:
              - path: /data
                subPath: data

      machine-learning:
        type: emptyDir
        advancedMounts:
          machine-learning:
            app:
              - path: /cache

      postgresql:
        existingClaim: ${APP}-postgres-data
        advancedMounts:
          postgresql:
            app:
              - path: /var/lib/postgresql/data
                subPath: data
