apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:nZalx5FA6yYIJIMHSwq9PfrmWlAscpPfnrTaYwbE/UtgZR//Mo+cxfGkY57haFu1ZZWVq9Z7dXiKknhbGGgiow==,iv:seDo4E2e6HwyVP3YG3Lrh6l0NwbaNbwuVnEN8XlxJ9A=,tag:2UzkVeJCaCb+vzqVxFpDOg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T00:56:22Z"
    mac: ENC[AES256_GCM,data:ki7GxiaSxhrT2kzk/Jy9agz6/knv5fQE56X+meFhEk45o7ci8qpBpWhBn33n640MIHE4oz3zYR7h0df4NVaPQz9d9KG3bjMbe5fiqQXkLFFBtkpnFLitesZ8Z2pi0k+4QlpQdgYryBZG1wIE5YOIhrs8X5MvlBqe3sW6bWerLr4=,iv:hU8xpFoB7G8miiFPLd81wzSWRmjz0KYD7N8IpTbUkyM=,tag:koGpu3q5mNROgCX8fMlX2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
