---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: vaultwarden
  interval: 1h
  path: ./kubernetes/hcloud/apps/selfhosted/vaultwarden/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
