---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chartRef:
    kind: OCIRepository
    name: reloader
  interval: 1h
  values:
    fullnameOverride: reloader
    reloader:
      enableHA: true
      deployment:
        replicas: 1
      readOnlyRootFileSystem: true
