---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-postgres
  namespace: selfhosted
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  #superuserSecret:
  #  name: pg-credentials
  storage:
    size: 5Gi
    storageClass: openebs-hostpath
  postgresql:
    parameters:
      max_connections: "100"
      work_mem: 128MB
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 150Mi
  #  limits:
  #    memory: 300Mi

  bootstrap:
    initdb:
      database: tandoor
      owner: tandoor
      secret:
        name: tandoor-db-secrets
