---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  chartRef:
    kind: OCIRepository
    name: tandoor
  interval: 30m

  values:
    controllers:
      tandoor:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 2.3.3@sha256:af6bd76e703d644748a93d581da05c25159d742b94b2da9eddadaaec93555858
            env:
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-secrets
                    key: secret-key
              TZ: ${TIMEZONE}
              DEBUG: 0
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_HOST: tandoor-postgres-rw.selfhosted.svc.cluster.local
              POSTGRES_DB: tandoor
              POSTGRES_PORT: 5432
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-db-secrets
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-db-secrets
                    key: password
              ALLOWED_HOSTS: rezepte.offene.cloud
              CSRF_TRUSTED_ORIGINS: 'https://rezepte.offene.cloud'
              TANDOOR_PORT: 80
              ENABLE_SIGNUP: 0
              SPACE_AI_ENABLED: 0
            securityContext:
            #  allowPrivilegeEscalation: false
            #  readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1024Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 80

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: "rezepte.offene.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "rezepte.offene.cloud"
            secretName: tandoor-tls

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: tandoor-data-pvc
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
                readOnly: false
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
                readOnly: false
      tmpfs:
        enabled: true
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/cookbook/static/django_js_reverse
                subPath: django_js_reverse
              - path: /var/lib/nginx/logs
                subPath: nginx_logs
              - path: /var/lib/nginx/tmp
                subPath: nginx_tmp
              - path: /tmp
                subPath: tmp
