apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secrets
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:r7cYm09v6YIBHVz1bFjc4U3YlCuBfKa/Oq19hcgWa0ctuWhAOI0qI6AESPMPja9QDZs=,iv:VtldwYLhOobWtzT1imbWkgURodnOFT1xOy0ifXJjQUA=,tag:uU/C7Pl8678bukphBzlutg==,type:str]
    SOCIAL_PROVIDERS: ENC[AES256_GCM,data:Z4fSHyktkgS749icuynhEhWIrFYThyMsE85oEKDLF2F0nXCgn+6AVX4tMONp4Q==,iv:OOpfs/bAM6ri2b+T6jm5uGwHH1ERfiqDdjsBtZOWxwA=,tag:CIXf4ORlIKttnnzclaMQUQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Ttt0KMH6AM+KdBJvheY/GfOy4J7dZ5EVt2N/pwaJgokSWsvL9wW4u8/yF+hIWZ7cEcXXpVI3G5ED2o0V+hbgqubpYVy/3Cdu5nDJeBldOdzsr1pUj+a0nNaP4M/jidBqngipn6Fc11wQFFzDBkT6NCKhOX6GNeNN84P2d0uBajkaHpHu+hJZHB76maYebtf1E4H3Eilg/B3apebpqBuufp0vd67d1raSMlX9d5KZpMFR/uUCLQkWybT4g+F7FFMETE8wT+UxGU6uymzfMZJQ13K6cw3MqTEq8wfFnKRJCaXgi1iO5iQS4OQZMacAGVWrbN6w43H4zR92MHfuaABaXQ==,iv:edo7dRmhqcUbl1lVBeZU+EAZAwTet754opOU8G4IsWk=,tag:uaeEyAfcpLonSlQJ83Ss/A==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:16:11Z"
    mac: ENC[AES256_GCM,data:2hUcbVIwur9iiQ4KTfGXHnSFRKybC49sk6Hk8dSCcfyemzRmD6i7ZYy4/kIPrKPvtK5WdUaKGgmYJXgW9e9aCIpAcNXxvLD5+cSs9lo65Zu9c78wBwFWk9i3YzZg8b1kJHtxRCCYjoGzDaUpn2x33wdl08qdk6FOGE1/OCB0PZM=,iv:oYKU0q3434+KNH4+jPCncSuTNWdLbkPjphZ7do0EP/k=,tag:7d835hECUi8tVwKX7ilntQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: tandoor-db-secrets
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cKT55cBbPQ==,iv:dyUE6RVBRqdglkoBSpLf7B9vnYO0VBlp45siSgtWy6o=,tag:oHdA494tjr0BtAVzv6YTNg==,type:str]
    password: ENC[AES256_GCM,data:OjkXH0Z85w1tBw/+rp3fYlAJfLw1zgjZa0CeWpdr9CYH3dUD+oQEwK2GY971V8E26RwE9m5VP3Lt9okIGU4=,iv:xXB3FEq4V4VE8AsxWRa5G2grfTxUPQXDmYJiyNSUrY4=,tag:GwAaVS0UVCNFbHH7/JmVjw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:16:11Z"
    mac: ENC[AES256_GCM,data:2hUcbVIwur9iiQ4KTfGXHnSFRKybC49sk6Hk8dSCcfyemzRmD6i7ZYy4/kIPrKPvtK5WdUaKGgmYJXgW9e9aCIpAcNXxvLD5+cSs9lo65Zu9c78wBwFWk9i3YzZg8b1kJHtxRCCYjoGzDaUpn2x33wdl08qdk6FOGE1/OCB0PZM=,iv:oYKU0q3434+KNH4+jPCncSuTNWdLbkPjphZ7do0EP/k=,tag:7d835hECUi8tVwKX7ilntQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
