apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IVLiQiC7TG4O,iv:1UXVOIu4WP1GPxRG65sJxXkSG8zZmjIOMM2EIMdVUqE=,tag:oDV4zTx1gumucJAAweBAoQ==,type:comment]
    username: ENC[AES256_GCM,data:cKT55cBbPQ==,iv:dyUE6RVBRqdglkoBSpLf7B9vnYO0VBlp45siSgtWy6o=,tag:oHdA494tjr0BtAVzv6YTNg==,type:str]
    password: ENC[AES256_GCM,data:OjkXH0Z85w1tBw/+rp3fYlAJfLw1zgjZa0CeWpdr9CYH3dUD+oQEwK2GY971V8E26RwE9m5VP3Lt9okIGU4=,iv:xXB3FEq4V4VE8AsxWRa5G2grfTxUPQXDmYJiyNSUrY4=,tag:GwAaVS0UVCNFbHH7/JmVjw==,type:str]
    #ENC[AES256_GCM,data:1Yb+LJuUkvY=,iv:hm+e+PQj9PiUw/kV0estu70ov8DzZlFYmMAKSiBFLvM=,tag:/ruCyXEo4C3oo7u5YjezEg==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:GD5V9Szw3qjQoCfaBT7K3sASkTssKaJz/r0f4uD+A6BXd22askHL4zi8GMUPEoP7uuE=,iv:WD4Ysa+dUIQ/U/QG7VEu7v99NzHoQvqGHFNJoqAnbRY=,tag:ZgcjJ7JV1uC1ep+n7jBCoA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T15:21:24Z"
    mac: ENC[AES256_GCM,data:bUbwyWAoYhk6PEXFiqP51Dt82RwMWyFQDz9+qhpQd87ZcUtHN6x5bd+9CQ8a6g9f8iPhKAo1H5WlraHdrwrfoXpBfAVIoyoKmr7H3uceTSTQ1tp49wG17NxomFVPcjRtI6wVPnMpXscnqrML8d5k2WNL/EjWqIunv2jAAuB7LKw=,iv:UxWRz0l2vmpv+6kYU2Y7GbcCJbpUgXEQnvzFnfE1k2c=,tag:/Y3rCTzaXVIvOLzQTfOB1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
