apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:GD5V9Szw3qjQoCfaBT7K3sASkTssKaJz/r0f4uD+A6BXd22askHL4zi8GMUPEoP7uuE=,iv:WD4Ysa+dUIQ/U/QG7VEu7v99NzHoQvqGHFNJoqAnbRY=,tag:ZgcjJ7JV1uC1ep+n7jBCoA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T13:22:28Z"
    mac: ENC[AES256_GCM,data:N8JWGWQTZ6OyEuxLT7q4MtLweYrjKmyad3Z2jKcpwKwbSkwSAmxMKMdrNoFchoXaMagqn/xEueL1RMUNIRhYlJe6staWE0TTLa46TPwO6ZRHcILsnnGxwDH9aXgN2vRVY2+LAS4H46yOOBPrzZNYIwgGvvYDkDyf9lfNc0Eu9xY=,iv:D0s2IBPYlEzGmSXNv8GnvEdsJGrxNx0qDufz5YjgyFM=,tag:zhnQCbjQfFNkURjQ2PAkLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
