apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:hZRy1wdHog==,iv:P18lZABT0rO7onKJo04n1ok1NbmR9AZZsxAaA83yhWA=,tag:JBjs461GJ1gEaIVNy9ydvQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:J5zRtbJJluaed3NbNN8AgX/LJy7Emxk6tZ8XPxiH01vlpxqYIzJwVNRjGasVdSZ26hOsv/gIXGfFMfdD,iv:VX6jHE/U+XH8n2LctA0s1hKh8E9iB4w7j/aL36/duOc=,tag:ZMtp529obWzM+8Ue9o3U7g==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:09/HPyxRSSz54CW0mr9cYc/hn+zaoT3rb2+xruhDJLYT+e+M,iv:JBUpd/ZvzgXSzjGSutnjguYKO8c3DzE6jlKm5KmUHYU=,tag:CC92hmYTwHiQoY8MqYHSAw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ABUY6tydpwUmahFVOFqGSMVW3X/Pmax9SUCTzUemBls=,iv:7qnc4Pm5WyGyy6yK6N+Od2nXzCEKpe9Th1EzeEDJx2U=,tag:WXhYjabLWY0NXWO3td4S8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL3JJTXlYRWdwS0xwRXRQ
            Z0F1MTU3OGk0bGFYUW5hSTBuMXloSkREUkJZCmhDNFN6RmZWL2cySmxDUXR2K3E0
            eHZXdlBBd2lvRlhUelFaNUZVa3cyd1EKLS0tIEJJcGh2UzZOaXN5cGJUVjBvMS9V
            aUY2K1g5d0g5dVRFK1MzSFNzZDBNaE0KVAQy/yiLtCbfoFYH5FjPluoVMqFFc2rD
            Tygd6771r+vW7XanPbDaFtCPyREocArFCFpFH6t9Kz+/35YaAbAsRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T19:15:05Z"
    mac: ENC[AES256_GCM,data:coPAEyGleQmJ9V/BRawmfp5CpZFE9YZ9fVg2yqCNTF1mJE2Yg4SkS/Y81nc4C1/jPq78lfweH4fsNT8iNwqB1aD3m9syPX9v2/9J1l9AEv24Xn8ebglalUsnoRHpyIDcGrevGSbWY9cA+adLl7O2S22W0TvHzN70dEMNzwUv1QA=,iv:pV7H8CHJoMnJJAhLFr15w+S7+m45a6kC1rm9sZtGvj0=,tag:hmUOCSR2EBLjOguzKaN3uQ==,type:str]
    version: 3.13.3
