---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
  namespace: renovate
spec:
  discoveryFilters:
    - homelab/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle"]
  image: ghcr.io/renovatebot/renovate:43.186.0@sha256:66fcdb3e51ea1071e853842a9b3f9598e62ebe6b0bee46b078fd176fa35cda8d
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://code.${EXTERNAL_DOMAIN}/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: false
