apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: development
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:CYhgx3oxPTn30wiJDBDCFY+5snuyvfKpiBcTt3M/hAr0TT8oxNDllw==,iv:ZTDB9fPjbiIKEAzODAfDIhjc0Yuv5FZ+8Dw9kd2SQD4=,tag:eu7ZmWcVNkuuc6l0ZOD5Pg==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:7MQGR+4DxYJwIYXS/5KJhiCRcBDGESu5sj4sv1qREThZcQa4jfxdinKfXM96S1PtMqO34zahJjqE25wW/4HGXH8kVZsngVE4kDsXRhdTUNtgmRb4MGjJeZadtaaw,iv:Z8A8DANudZj9keUex4K3BLobX9DqauAvRuBOo+zTUh8=,tag:115GH/wJZHwcNpMu3VRq5Q==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T18:14:58Z"
    mac: ENC[AES256_GCM,data:pgdJy9hoebeS3VEmePWOwfJQdF20/ppE5hA1+tI+TJAtngx2dX0qAvJP3NN9potS7gVOv2lfMqZhZrrsnRtAlehqax0sKe+TwRzWg8tqE1PzsT3BJaS0E6Fb3l09pGsh5uQpOwH2xaCnDyEfxkFZMTCG1ExghJENFNDids4ZrTY=,iv:Lk2aShEN1vS1Wk1WU78/RIEsqOf6fROkAVWxLavYWKk=,tag:Yh5VLpymt2oB3fo1W2FJXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
