apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:CYhgx3oxPTn30wiJDBDCFY+5snuyvfKpiBcTt3M/hAr0TT8oxNDllw==,iv:ZTDB9fPjbiIKEAzODAfDIhjc0Yuv5FZ+8Dw9kd2SQD4=,tag:eu7ZmWcVNkuuc6l0ZOD5Pg==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:7MQGR+4DxYJwIYXS/5KJhiCRcBDGESu5sj4sv1qREThZcQa4jfxdinKfXM96S1PtMqO34zahJjqE25wW/4HGXH8kVZsngVE4kDsXRhdTUNtgmRb4MGjJeZadtaaw,iv:Z8A8DANudZj9keUex4K3BLobX9DqauAvRuBOo+zTUh8=,tag:115GH/wJZHwcNpMu3VRq5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T13:07:10Z"
    mac: ENC[AES256_GCM,data:l1Gpu62HIaXPIhT6M2pOHU6AC0zq9P/rEaoNk15n2FZPgzOnR8/OD6NyMpP5lKTbGWFYJC+orTtPiJcKRLivF+MEqWg5j6NVGrwkBU4L8My7Zdeux9z9QF7Z22IAie+fBzv2EjbpgqHuto4J+f725VctPShLyVRIzNhi7RHW9PQ=,iv:lba9PAxepKtl1yL9xahj8tvaeTx48yPnVfLc3RMHWE0=,tag:sQ+WVoGljLm0Y3NCUd85NQ==,type:str]
    version: 3.13.1
