apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:CYhgx3oxPTn30wiJDBDCFY+5snuyvfKpiBcTt3M/hAr0TT8oxNDllw==,iv:ZTDB9fPjbiIKEAzODAfDIhjc0Yuv5FZ+8Dw9kd2SQD4=,tag:eu7ZmWcVNkuuc6l0ZOD5Pg==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:7MQGR+4DxYJwIYXS/5KJhiCRcBDGESu5sj4sv1qREThZcQa4jfxdinKfXM96S1PtMqO34zahJjqE25wW/4HGXH8kVZsngVE4kDsXRhdTUNtgmRb4MGjJeZadtaaw,iv:Z8A8DANudZj9keUex4K3BLobX9DqauAvRuBOo+zTUh8=,tag:115GH/wJZHwcNpMu3VRq5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpIME5SajJz
            RmJVUFpKR3Nad2JtbzlZZCtPdnhTUTNmZjN5TklxRkRKWUZQeFVNUGxJRVR5a0U4
            SkZTRTUxUUdBck5pd2ZQcjJhOVZoNGowOXlUL2U2WkhldkJwZHhrQk9GazcrSFVH
            L2lwOHhnSE5Xcm9KRzFyTjIrTzhJVDU3ZjBPYVJ0Uk96QUxtZGp3OWhDWlpRZVUw
            U3BLc1lTSmkyRlVnSFpydGx6UktmVmVaZ2hlZTM0ZG9ITmlxM1JnR08wblA2b1NR
            YjhvMGxoSGRiWEpZWGt1K0FGVGNTc0wwRFptSnhEb2RJaVNMN0paYXplQjU1S3Rq
            OGV4L0k5M3RKMGg3b0pIeFZPeEY4RmNsdC9valZEQXRCZFlRR2pjRmZpd2crTkN0
            Y2lhOHgwL2owZTJvV2o4YTlqYWN5VHFoRXlBQVN4a2dzZzVqM3R0Z1B1ekc3WVhV
            YXZWNlY2OFRkVFdROHlTMEJiQ29LTk9ERm9zUlBCRWQ5ZUR0RkYxNkVTUXNSbmVK
            RFZxMG04WE1EQ0ZOTDF3YUU0UDRXQ1djS2hEeXV4MFFNN2NKOFlrcWFuK21nLzdG
            NXVZVHc5UDJrVGpyYTdSZUJYSUtXK0hrUEdZdmNZSkdwRXQzZE5EYmU0VStzVWM5
            U2IyUFk4cjBva1h5MzV2bmJHdE5LR1I4Z05MTDBPREFMUGFkYTQ0QUhKeTFhemVz
            ckZoSWZOdUhQcGNMZTJhYy85dE5ubmxRQUpiQzhaUkJ0alI3TEE1UUxaOHpNblQz
            RE1qdlZ0MGVOTm5IbFNWUWlJK3FPbHQwOVRHQkk0SmwvUjBvTXhxWFVuQ2c0UW1P
            K3k0UHhmb2wvZE9GaWk5bjlPSDdFdi8wdEhjekEvZjJIL2s2a3NRdE1mdHlYZ1hT
            QzJYb3JLRkdJZGdveHRWQjcwRWRIUi9GUmUvOXRYSWRzUVNaQWVtY3FwbWFTeG9X
            SEJmVzd4bnJnL2ZQc3RlREI2cWdqcHBzZGpadzkyMUZxWTBZOVNhU3dHMW9TTmNo
            R2lSUk1uZjdxT2haOWpDRW5RSUU3L2RFODBvdnN6Vmd2Qk9USzU1dTRUVGx5dmxm
            NTZ4MGdycmNUMVdyTk81a24zb2JqN3dpUE9VbFpIQlRHREp2ZkNjRGhEUWNxb1F0
            RnFwQ2I0U294TEVzU2JoTkJlTnBVSFBnaUliMmpiczliaXUraU9tL05PaHQ2U3JD
            V0R6YllORnQ2MGRYcDJ3YS91eWp6bGpUY1BvTTRDWWpxTkhiZkZKSUJyTkl2dzJH
            VG04dlJxNTNSQ1VyUHVIMDNzWVRVWTFJcGVmbkxRd1I5Z29xQ25aeXdzVGs1UGc0
            WjBaa2o4Wm1UTkV3K0VMY1FJMEhoaXEwU1NPSEZMeWpEaW9qWFpJU2xnMjZldjlj
            b2tNT09FcS81SDZtYllYeUdvdDJlSlhqaUc5VlNCbDBUa1VHSkxpU05FaUJKVzcv
            VnhNOWJvSUc3UjRTNWVseis1N29yNlh5ZnJUVXRrS0tPaVc0NTB2YmxqTS9PRElJ
            RWJoMWZhK2hoNkhjVm1ZWjRwUU9KQlNsKzdmTjlCdWduakJFZ1FDdzd4QkQ1ek1j
            amgyRCtJT1owU3A5Z25tVnBJakxLV2ZsM2hTMVpuZFFwNkd1c3FyRVRjcVpMZThD
            U2NIWTJvMk1VQVV4UXI1NG5rTXVVeENVeUJPMzA1Qld1QTBkMFVmRDZJdmZrcXBq
            ZE9lWmRxVjBlQVB1NUY3V2x5c1ppREpxdXlsWnlCNGJHaE9xYjFIRTJISkZLYzZ4
            ejJrQzZSRXJ2OEc1VkJ0ZkdoREdYVHBLZEZ3aUNMc0IzRnlDekdCZ25Ka2NrVVFZ
            Nkx4YWc3S0FuUGRBSEp2ZHlnTEdZRGcvV29meEVEWmdvdFVBY2x2ZTRwRWd0aWg5
            cURqazV2Ris0NitTWkp0ZWkzUHh0Z0Q1Um1QbEtNM0ZaYVhIWExWZTBaUXBFZwpF
            NDBqTCtXc21EWkI5U1N4Mkw4VU43OXQyTmFCMDIydWU3SGNWWGR1T3NRCi0tLSA3
            VS8yd0ZLRUt5a3RFMzVnK1pYclFSNmttdnowWnM2QXlyUzJML0dQRldFCr3nL6o5
            lCe+blKHAvocQTwOZ2b+VHro13Ij+YWIZ1dbBx61x/seqpMEU5aP9ARtG8q1FD5S
            Z3Qw7CNFZnuvdHs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1nfmv9z8k88cywtygvuyv846t8dsmvg954f5y0vdyw9wraff0qafu4j2e8m5ujm9wly6d92ev9gp6ff9vyjswf32xgn9rwvv55q922t62pu8h2g9nhrzzj4xfdswg5ay95e57pq9gl2mde8r9nxg9w9ve5xqg5xmwujhrdcm9va5r0rqew4hrenypj3kmq9rgcfa8pckf94v2gk79ufv6t9nh9j3vm3xmr2h7x0al8f35fvfvha3h0cp8jffnsueagaqy472u0l7rwlghwvaxrq9x5jtsusyd3fmgk9qskgae2hc4rr8tm7ysxcqf2swyfhx89jfadzag793fnr96cl82f6rpzfgg48xmsyugvdgr8ftkgm35r8s74puff95ravagex9ukp8sj4pm0qsj5hzacy9tz7s2nnrakhgm6ysj7wvj986yl06mgd9vkp96n09lmcgzjcpr2qwy4vdlzvmulzqlv6qf695j230phr5hr8s86gzcg3mq3q692fjqd9dq304flqpued2lgkymnmeuvdnrpw87m30stny08qeh99tv4amtyy6wk9h3m8qdccdjq629z50jxs8p69s6xzf66myfgulkchm6fvy3z5tm3lqjrhccq9c8dqnsxwdf2vpksv65znrpumk4kfarevdk3yrgv6njw0dtzvn38kdcy2xndwktldkpcvup9qsxg2332mppvjuzq75ej3fxfw2meawpkztk5dkdacry5042nhans2ky83ktwzx3czc7kyvr8jugtuus4z02mz7hy7677rtglhqpjcha3gryf2809eg9nlpjh003raxacyrv9j0mms9rnnufgh38eqx45mkrkx2yfkm5npaktt9sgwkcdy5f2fj6hyxwtqdm0nqu0se93xfgg25e99sxu0uj4rynpnjy8jsu2cqud9fgy7c37vvp0qcc99cnw6ndjzysumnhk87nvzpu4x60pjta37jvh85pp0r42g235l2pvf3l79g92mg2sumfx4gp5cxmw59vtawzt0m84z6r27l73w6t4tqu26t4cf3reykmd8f7w2mk62tngzvnkvzxra9uvu534vu5lt8ewwk8snckvpp95kl2e2v573pj5z6n8eu3dtk9twy9kfzetxqkgpvkx4p9ptcpr7fv43nsgsseysvh60g5fwtf83lhzes6cwujccqm3je8yaxx4d9xtq9rhstvsjycp5qzl9868l9gxw5n6k6ywku66ne4ah3rqarhynmnh244tzxrcyzuqp65tjmdhtm9frzan9zhux4z0j3mr69sdwdswry74dwdff4ge9kzelga394lerp8zg3xhnykxd4hzewr0fqzzcph42svesqgaery8lnlketxhtqtvpuut5n9jw0xj20gqvwykg6djp45c4zslex256keg565x3rsnhp3r7jvd22uy93d39clg3x6q3ar7fu8qdxjxxkfveq5gudw5x70ktztwk6jyy0c9trgdpsgly7dm8c8lzs5hjfmw8cn7xwrelz8n2wt6arhhpk72zyy908mucwzjuuxmxkh0tsqtqyc5qvyd74mkvfzjgrh4a8fkfasdgjm8y6wjpzzvdf88jgjegqhz5kpgv9j5sr8egmzc3r5g9mawyucpm9vzh2vjuukhtsh5qm4sxqcrxf5qf9hhsy2y5v9vsls8g76jggc8w92wk8yhl73hwp5kgmhrxn7nmc9tmm6tnhy9xu76cf37pjalzkpsc0vgj8s5kdu8ykx5a3lng2nrrar4antjpuhcwglz43ff3atgf0y8883qkgx2yttn3mh75nh3u9zdnw4pycsq5j5ahzj3lcmz0km3ql8f8akkg320pggef7ugpcserv36tuuqff9rcujzq8dd6rq96xsav2k2grufql0ph53nmv7fdmkxs992fndxtlryvle2afe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T13:07:10Z"
    mac: ENC[AES256_GCM,data:l1Gpu62HIaXPIhT6M2pOHU6AC0zq9P/rEaoNk15n2FZPgzOnR8/OD6NyMpP5lKTbGWFYJC+orTtPiJcKRLivF+MEqWg5j6NVGrwkBU4L8My7Zdeux9z9QF7Z22IAie+fBzv2EjbpgqHuto4J+f725VctPShLyVRIzNhi7RHW9PQ=,iv:lba9PAxepKtl1yL9xahj8tvaeTx48yPnVfLc3RMHWE0=,tag:sQ+WVoGljLm0Y3NCUd85NQ==,type:str]
    version: 3.13.1
